# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditShot.ui'
#
# Created: Sat Sep  2 16:57:51 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_dlg_EditShot(object):
    def setupUi(self, dlg_EditShot):
        dlg_EditShot.setObjectName("dlg_EditShot")
        dlg_EditShot.resize(436, 371)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_EditShot)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_shotName = QtWidgets.QWidget(dlg_EditShot)
        self.w_shotName.setObjectName("w_shotName")
        self.gridLayout = QtWidgets.QGridLayout(self.w_shotName)
        self.gridLayout.setContentsMargins(-1, 10, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.b_showSeq = QtWidgets.QToolButton(self.w_shotName)
        self.b_showSeq.setMaximumSize(QtCore.QSize(25, 16777215))
        self.b_showSeq.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_showSeq.setText("")
        self.b_showSeq.setArrowType(QtCore.Qt.DownArrow)
        self.b_showSeq.setObjectName("b_showSeq")
        self.gridLayout.addWidget(self.b_showSeq, 0, 3, 1, 1)
        self.l_seq = QtWidgets.QLabel(self.w_shotName)
        self.l_seq.setObjectName("l_seq")
        self.gridLayout.addWidget(self.l_seq, 0, 1, 1, 1)
        self.e_sequence = QtWidgets.QLineEdit(self.w_shotName)
        self.e_sequence.setObjectName("e_sequence")
        self.gridLayout.addWidget(self.e_sequence, 0, 2, 1, 1)
        self.e_shotName = QtWidgets.QLineEdit(self.w_shotName)
        self.e_shotName.setObjectName("e_shotName")
        self.gridLayout.addWidget(self.e_shotName, 1, 2, 1, 1)
        self.l_shot = QtWidgets.QLabel(self.w_shotName)
        self.l_shot.setObjectName("l_shot")
        self.gridLayout.addWidget(self.l_shot, 1, 1, 1, 1)
        self.l_seqIcon = QtWidgets.QLabel(self.w_shotName)
        self.l_seqIcon.setText("")
        self.l_seqIcon.setObjectName("l_seqIcon")
        self.gridLayout.addWidget(self.l_seqIcon, 0, 0, 1, 1)
        self.l_shotIcon = QtWidgets.QLabel(self.w_shotName)
        self.l_shotIcon.setText("")
        self.l_shotIcon.setObjectName("l_shotIcon")
        self.gridLayout.addWidget(self.l_shotIcon, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.w_shotName)
        self.w_range = QtWidgets.QWidget(dlg_EditShot)
        self.w_range.setObjectName("w_range")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.w_range)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.w_range)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.w_range)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sp_startFrame = QtWidgets.QSpinBox(self.w_range)
        self.sp_startFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_startFrame.setMaximum(99999)
        self.sp_startFrame.setProperty("value", 1001)
        self.sp_startFrame.setObjectName("sp_startFrame")
        self.horizontalLayout.addWidget(self.sp_startFrame)
        self.label_3 = QtWidgets.QLabel(self.w_range)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sp_endFrame = QtWidgets.QSpinBox(self.w_range)
        self.sp_endFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_endFrame.setMaximum(99999)
        self.sp_endFrame.setProperty("value", 1100)
        self.sp_endFrame.setObjectName("sp_endFrame")
        self.horizontalLayout.addWidget(self.sp_endFrame)
        self.verticalLayout.addWidget(self.w_range)
        self.w_preview = QtWidgets.QWidget(dlg_EditShot)
        self.w_preview.setObjectName("w_preview")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.w_preview)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.w_preview)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.l_shotPreview = QtWidgets.QLabel(self.w_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_shotPreview.sizePolicy().hasHeightForWidth())
        self.l_shotPreview.setSizePolicy(sizePolicy)
        self.l_shotPreview.setMinimumSize(QtCore.QSize(300, 169))
        self.l_shotPreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_shotPreview.setObjectName("l_shotPreview")
        self.horizontalLayout_2.addWidget(self.l_shotPreview)
        self.verticalLayout.addWidget(self.w_preview)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.widget = QtWidgets.QWidget(dlg_EditShot)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_deleteShot = QtWidgets.QPushButton(self.widget)
        self.b_deleteShot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteShot.setObjectName("b_deleteShot")
        self.horizontalLayout_4.addWidget(self.b_deleteShot)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(dlg_EditShot)
        QtCore.QMetaObject.connectSlotsByName(dlg_EditShot)
        dlg_EditShot.setTabOrder(self.e_sequence, self.b_showSeq)
        dlg_EditShot.setTabOrder(self.b_showSeq, self.sp_startFrame)
        dlg_EditShot.setTabOrder(self.sp_startFrame, self.sp_endFrame)

    def retranslateUi(self, dlg_EditShot):
        dlg_EditShot.setWindowTitle(QtWidgets.QApplication.translate("", "Edit shot", None, -1))
        self.b_showSeq.setToolTip(QtWidgets.QApplication.translate("", "Existing sequence names", None, -1))
        self.l_seq.setText(QtWidgets.QApplication.translate("", "Sequence:", None, -1))
        self.e_sequence.setPlaceholderText(QtWidgets.QApplication.translate("", "sq_010", None, -1))
        self.e_shotName.setPlaceholderText(QtWidgets.QApplication.translate("", "sh_010", None, -1))
        self.l_shot.setText(QtWidgets.QApplication.translate("", "Shot:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("", "Framerange:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "start:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("", "end:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("", "Thumbnail:", None, -1))
        self.l_shotPreview.setText(QtWidgets.QApplication.translate("", "Preview image", None, -1))
        self.b_deleteShot.setText(QtWidgets.QApplication.translate("", "Delete shot", None, -1))

