# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExternalTask.ui'
#
# Created: Tue Mar  7 10:10:40 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_dlg_ExternalTask(object):
    def setupUi(self, dlg_ExternalTask):
        dlg_ExternalTask.setObjectName("dlg_ExternalTask")
        dlg_ExternalTask.resize(708, 185)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_ExternalTask)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(dlg_ExternalTask)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.w_taskName = QtWidgets.QWidget(self.widget_3)
        self.w_taskName.setObjectName("w_taskName")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.w_taskName)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.e_taskName = QtWidgets.QLineEdit(self.w_taskName)
        self.e_taskName.setObjectName("e_taskName")
        self.horizontalLayout_2.addWidget(self.e_taskName)
        self.horizontalLayout_3.addWidget(self.w_taskName)
        self.w_versionName = QtWidgets.QWidget(self.widget_3)
        self.w_versionName.setObjectName("w_versionName")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.w_versionName)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.w_versionName)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.e_versionName = QtWidgets.QLineEdit(self.w_versionName)
        self.e_versionName.setObjectName("e_versionName")
        self.horizontalLayout_4.addWidget(self.e_versionName)
        self.horizontalLayout_3.addWidget(self.w_versionName)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.w_taskPath = QtWidgets.QWidget(self.widget_4)
        self.w_taskPath.setObjectName("w_taskPath")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.w_taskPath)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.e_taskPath = QtWidgets.QLineEdit(self.w_taskPath)
        self.e_taskPath.setObjectName("e_taskPath")
        self.horizontalLayout.addWidget(self.e_taskPath)
        self.b_browseFile = QtWidgets.QPushButton(self.w_taskPath)
        self.b_browseFile.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseFile.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseFile.setObjectName("b_browseFile")
        self.horizontalLayout.addWidget(self.b_browseFile)
        self.b_browseFolder = QtWidgets.QPushButton(self.w_taskPath)
        self.b_browseFolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseFolder.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseFolder.setObjectName("b_browseFolder")
        self.horizontalLayout.addWidget(self.b_browseFolder)
        self.verticalLayout_2.addWidget(self.w_taskPath)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(dlg_ExternalTask)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.rb_copy = QtWidgets.QRadioButton(self.widget_5)
        self.rb_copy.setChecked(True)
        self.rb_copy.setObjectName("rb_copy")
        self.horizontalLayout_6.addWidget(self.rb_copy)
        self.rb_move = QtWidgets.QRadioButton(self.widget_5)
        self.rb_move.setObjectName("rb_move")
        self.horizontalLayout_6.addWidget(self.rb_move)
        self.rb_link = QtWidgets.QRadioButton(self.widget_5)
        self.rb_link.setObjectName("rb_link")
        self.horizontalLayout_6.addWidget(self.rb_link)
        self.verticalLayout.addWidget(self.widget_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlg_ExternalTask)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dlg_ExternalTask)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlg_ExternalTask.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlg_ExternalTask.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_ExternalTask)

    def retranslateUi(self, dlg_ExternalTask):
        dlg_ExternalTask.setWindowTitle(QtWidgets.QApplication.translate("", "Add external media", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("", "Identifier:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "External path:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("", "Versionname:", None, -1))
        self.b_browseFile.setText(QtWidgets.QApplication.translate("", "...(file)", None, -1))
        self.b_browseFolder.setText(QtWidgets.QApplication.translate("", "...(folder)", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("", "Action:", None, -1))
        self.rb_copy.setText(QtWidgets.QApplication.translate("", "Copy", None, -1))
        self.rb_move.setText(QtWidgets.QApplication.translate("", "Move", None, -1))
        self.rb_link.setText(QtWidgets.QApplication.translate("", "Link", None, -1))

