# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectBrowser.ui'
#
# Created: Mon May 22 12:24:24 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_mw_ProjectBrowser(object):
    def setupUi(self, mw_ProjectBrowser):
        mw_ProjectBrowser.setObjectName("mw_ProjectBrowser")
        mw_ProjectBrowser.resize(1074, 618)
        mw_ProjectBrowser.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(mw_ProjectBrowser)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1054, 577))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lo_scrollArea = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.lo_scrollArea.setObjectName("lo_scrollArea")
        self.w_header = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_header.setObjectName("w_header")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.w_header)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbw_project = QtWidgets.QTabWidget(self.w_header)
        self.tbw_project.setObjectName("tbw_project")
        self.verticalLayout.addWidget(self.tbw_project)
        self.lo_scrollArea.addWidget(self.w_header)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_17.addWidget(self.scrollArea)
        mw_ProjectBrowser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mw_ProjectBrowser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        mw_ProjectBrowser.setMenuBar(self.menubar)
        self.actionPrismSettings = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionPrismSettings.setObjectName("actionPrismSettings")
        self.actionRefresh = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionAssets = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionAssets.setCheckable(True)
        self.actionAssets.setChecked(True)
        self.actionAssets.setObjectName("actionAssets")
        self.actionShots = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionShots.setCheckable(True)
        self.actionShots.setChecked(True)
        self.actionShots.setObjectName("actionShots")
        self.actionFiles = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionFiles.setCheckable(True)
        self.actionFiles.setChecked(True)
        self.actionFiles.setObjectName("actionFiles")
        self.actionRecent = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionRecent.setCheckable(True)
        self.actionRecent.setChecked(True)
        self.actionRecent.setObjectName("actionRecent")
        self.actionOpenOnStart = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionOpenOnStart.setCheckable(True)
        self.actionOpenOnStart.setChecked(True)
        self.actionOpenOnStart.setObjectName("actionOpenOnStart")
        self.actionRenderWatch = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionRenderWatch.setObjectName("actionRenderWatch")
        self.actionStateManager = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionStateManager.setObjectName("actionStateManager")
        self.actionCloseAfterLoad = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionCloseAfterLoad.setCheckable(True)
        self.actionCloseAfterLoad.setChecked(True)
        self.actionCloseAfterLoad.setObjectName("actionCloseAfterLoad")
        self.actionAutoplay = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionAutoplay.setCheckable(True)
        self.actionAutoplay.setChecked(False)
        self.actionAutoplay.setObjectName("actionAutoplay")
        self.actionMedia = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionMedia.setCheckable(True)
        self.actionMedia.setChecked(True)
        self.actionMedia.setObjectName("actionMedia")
        self.actionTest = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionTest.setObjectName("actionTest")
        self.actionCheckForUpdates = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionCheckForUpdates.setCheckable(True)
        self.actionCheckForUpdates.setChecked(True)
        self.actionCheckForUpdates.setObjectName("actionCheckForUpdates")
        self.actionCheckForShotFrameRange = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionCheckForShotFrameRange.setCheckable(True)
        self.actionCheckForShotFrameRange.setChecked(True)
        self.actionCheckForShotFrameRange.setObjectName("actionCheckForShotFrameRange")
        self.actionProjectSettings = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionProjectSettings.setObjectName("actionProjectSettings")
        self.actionRefreshCurrentTabOnly = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionRefreshCurrentTabOnly.setCheckable(True)
        self.actionRefreshCurrentTabOnly.setObjectName("actionRefreshCurrentTabOnly")
        self.actionRefreshWhenSwitchingTabs = QtWidgets.QAction(mw_ProjectBrowser)
        self.actionRefreshWhenSwitchingTabs.setCheckable(True)
        self.actionRefreshWhenSwitchingTabs.setObjectName("actionRefreshWhenSwitchingTabs")
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionOpenOnStart)
        self.menuTools.addAction(self.actionCheckForUpdates)
        self.menuTools.addAction(self.actionCheckForShotFrameRange)
        self.menuTools.addAction(self.actionCloseAfterLoad)
        self.menuTools.addAction(self.actionAutoplay)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionStateManager)
        self.menuTools.addAction(self.actionPrismSettings)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(mw_ProjectBrowser)
        self.tbw_project.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(mw_ProjectBrowser)

    def retranslateUi(self, mw_ProjectBrowser):
        mw_ProjectBrowser.setWindowTitle(QtWidgets.QApplication.translate("", "ProjectBrowser", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("", "Options", None, -1))
        self.actionPrismSettings.setText(QtWidgets.QApplication.translate("", "Settings...", None, -1))
        self.actionRefresh.setText(QtWidgets.QApplication.translate("", "Refresh", None, -1))
        self.actionAssets.setText(QtWidgets.QApplication.translate("", "Assets", None, -1))
        self.actionShots.setText(QtWidgets.QApplication.translate("", "Shots", None, -1))
        self.actionFiles.setText(QtWidgets.QApplication.translate("", "Files", None, -1))
        self.actionRecent.setText(QtWidgets.QApplication.translate("", "Recent", None, -1))
        self.actionOpenOnStart.setText(QtWidgets.QApplication.translate("", "Open on startup", None, -1))
        self.actionRenderWatch.setText(QtWidgets.QApplication.translate("", "RenderWatch", None, -1))
        self.actionStateManager.setText(QtWidgets.QApplication.translate("", "State Manager...", None, -1))
        self.actionCloseAfterLoad.setText(QtWidgets.QApplication.translate("", "Close after loading", None, -1))
        self.actionAutoplay.setText(QtWidgets.QApplication.translate("", "Autoplay preview", None, -1))
        self.actionMedia.setText(QtWidgets.QApplication.translate("", "Media", None, -1))
        self.actionTest.setText(QtWidgets.QApplication.translate("", "test", None, -1))
        self.actionCheckForUpdates.setText(QtWidgets.QApplication.translate("", "Check for latest import version", None, -1))
        self.actionCheckForShotFrameRange.setText(QtWidgets.QApplication.translate("", "Check for shot frame range", None, -1))
        self.actionProjectSettings.setText(QtWidgets.QApplication.translate("", "Project Settings...", None, -1))
        self.actionRefreshCurrentTabOnly.setText(QtWidgets.QApplication.translate("", "Refresh current tab only", None, -1))
        self.actionRefreshWhenSwitchingTabs.setText(QtWidgets.QApplication.translate("", "Refresh when switching tabs", None, -1))

