# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectBrowser.ui'
#
# Created: Tue Nov  3 14:54:15 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mw_ProjectBrowser(object):
    def setupUi(self, mw_ProjectBrowser):
        mw_ProjectBrowser.setObjectName("mw_ProjectBrowser")
        mw_ProjectBrowser.resize(1311, 870)
        mw_ProjectBrowser.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(mw_ProjectBrowser)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1309, 847))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tbw_browser = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tbw_browser.setTabPosition(QtGui.QTabWidget.North)
        self.tbw_browser.setTabShape(QtGui.QTabWidget.Rounded)
        self.tbw_browser.setTabsClosable(False)
        self.tbw_browser.setMovable(True)
        self.tbw_browser.setObjectName("tbw_browser")
        self.t_assets = QtGui.QWidget()
        self.t_assets.setObjectName("t_assets")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.t_assets)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.w_assetHierarchy = QtGui.QWidget(self.t_assets)
        self.w_assetHierarchy.setMinimumSize(QtCore.QSize(140, 0))
        self.w_assetHierarchy.setMaximumSize(QtCore.QSize(200, 16777215))
        self.w_assetHierarchy.setObjectName("w_assetHierarchy")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.w_assetHierarchy)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtGui.QWidget(self.w_assetHierarchy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_aHierarchy = QtGui.QLabel(self.widget_3)
        self.l_aHierarchy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_aHierarchy.setObjectName("l_aHierarchy")
        self.horizontalLayout_2.addWidget(self.l_aHierarchy)
        self.b_assetSearch = QtGui.QToolButton(self.widget_3)
        self.b_assetSearch.setText("")
        self.b_assetSearch.setCheckable(True)
        self.b_assetSearch.setAutoRaise(True)
        self.b_assetSearch.setObjectName("b_assetSearch")
        self.horizontalLayout_2.addWidget(self.b_assetSearch)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.w_assetSearch = QtGui.QWidget(self.w_assetHierarchy)
        self.w_assetSearch.setObjectName("w_assetSearch")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.w_assetSearch)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.e_assetSearch = QtGui.QLineEdit(self.w_assetSearch)
        self.e_assetSearch.setObjectName("e_assetSearch")
        self.horizontalLayout_6.addWidget(self.e_assetSearch)
        self.verticalLayout_3.addWidget(self.w_assetSearch)
        self.tw_aHierarchy = QtGui.QTreeWidget(self.w_assetHierarchy)
        self.tw_aHierarchy.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_aHierarchy.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_aHierarchy.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_aHierarchy.setObjectName("tw_aHierarchy")
        self.tw_aHierarchy.headerItem().setText(0, "1")
        self.tw_aHierarchy.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.tw_aHierarchy)
        self.horizontalLayout_3.addWidget(self.w_assetHierarchy)
        self.verticalWidget_3 = QtGui.QWidget(self.t_assets)
        self.verticalWidget_3.setMaximumSize(QtCore.QSize(272, 16777215))
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalWidget_2 = QtGui.QWidget(self.verticalWidget_3)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_23 = QtGui.QWidget(self.horizontalWidget_2)
        self.widget_23.setMinimumSize(QtCore.QSize(80, 0))
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.widget_23)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.l_aStep = QtGui.QLabel(self.widget_23)
        self.l_aStep.setObjectName("l_aStep")
        self.verticalLayout_22.addWidget(self.l_aStep)
        self.lw_aPipeline = QtGui.QListWidget(self.widget_23)
        self.lw_aPipeline.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_aPipeline.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lw_aPipeline.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_aPipeline.setObjectName("lw_aPipeline")
        self.verticalLayout_22.addWidget(self.lw_aPipeline)
        self.horizontalLayout_13.addWidget(self.widget_23)
        self.w_aCategory = QtGui.QWidget(self.horizontalWidget_2)
        self.w_aCategory.setMinimumSize(QtCore.QSize(182, 0))
        self.w_aCategory.setMaximumSize(QtCore.QSize(182, 16777215))
        self.w_aCategory.setObjectName("w_aCategory")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.w_aCategory)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.l_aCategory = QtGui.QLabel(self.w_aCategory)
        self.l_aCategory.setObjectName("l_aCategory")
        self.verticalLayout_23.addWidget(self.l_aCategory)
        self.lw_aCategory = QtGui.QListWidget(self.w_aCategory)
        self.lw_aCategory.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.lw_aCategory.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_aCategory.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lw_aCategory.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_aCategory.setObjectName("lw_aCategory")
        self.verticalLayout_23.addWidget(self.lw_aCategory)
        self.horizontalLayout_13.addWidget(self.w_aCategory)
        self.verticalLayout_21.addWidget(self.horizontalWidget_2)
        self.gb_assetInfo = QtGui.QGroupBox(self.verticalWidget_3)
        self.gb_assetInfo.setMinimumSize(QtCore.QSize(0, 220))
        self.gb_assetInfo.setMaximumSize(QtCore.QSize(16777215, 220))
        self.gb_assetInfo.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gb_assetInfo.setObjectName("gb_assetInfo")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.gb_assetInfo)
        self.verticalLayout_24.setSpacing(15)
        self.verticalLayout_24.setContentsMargins(9, 18, 9, 9)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.l_aDescription = QtGui.QLabel(self.gb_assetInfo)
        self.l_aDescription.setText("")
        self.l_aDescription.setObjectName("l_aDescription")
        self.verticalLayout_24.addWidget(self.l_aDescription)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem)
        self.widget_8 = QtGui.QWidget(self.gb_assetInfo)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.l_assetPreview = QtGui.QLabel(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_assetPreview.sizePolicy().hasHeightForWidth())
        self.l_assetPreview.setSizePolicy(sizePolicy)
        self.l_assetPreview.setMinimumSize(QtCore.QSize(100, 100))
        self.l_assetPreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_assetPreview.setText("")
        self.l_assetPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_assetPreview.setObjectName("l_assetPreview")
        self.horizontalLayout_14.addWidget(self.l_assetPreview)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_24.addWidget(self.widget_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem3)
        self.verticalLayout_21.addWidget(self.gb_assetInfo)
        self.horizontalLayout_3.addWidget(self.verticalWidget_3)
        self.widget_4 = QtGui.QWidget(self.t_assets)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_aFiles = QtGui.QLabel(self.widget_4)
        self.l_aFiles.setObjectName("l_aFiles")
        self.verticalLayout_4.addWidget(self.l_aFiles)
        self.tw_aFiles = QtGui.QTableView(self.widget_4)
        self.tw_aFiles.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_aFiles.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_aFiles.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tw_aFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tw_aFiles.setTextElideMode(QtCore.Qt.ElideRight)
        self.tw_aFiles.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_aFiles.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_aFiles.setSortingEnabled(True)
        self.tw_aFiles.setObjectName("tw_aFiles")
        self.tw_aFiles.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_aFiles.horizontalHeader().setHighlightSections(False)
        self.tw_aFiles.horizontalHeader().setSortIndicatorShown(True)
        self.tw_aFiles.horizontalHeader().setStretchLastSection(False)
        self.tw_aFiles.verticalHeader().setVisible(False)
        self.tw_aFiles.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tw_aFiles)
        self.w_aShowFormats = QtGui.QWidget(self.widget_4)
        self.w_aShowFormats.setObjectName("w_aShowFormats")
        self.horizontalLayout = QtGui.QHBoxLayout(self.w_aShowFormats)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_aShow = QtGui.QLabel(self.w_aShowFormats)
        self.l_aShow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.l_aShow.setObjectName("l_aShow")
        self.horizontalLayout.addWidget(self.l_aShow)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.w_aShowFormats)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.tbw_browser.addTab(self.t_assets, "")
        self.t_shots = QtGui.QWidget()
        self.t_shots.setObjectName("t_shots")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.t_shots)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.w_shots = QtGui.QWidget(self.t_shots)
        self.w_shots.setMinimumSize(QtCore.QSize(160, 0))
        self.w_shots.setMaximumSize(QtCore.QSize(200, 16777215))
        self.w_shots.setObjectName("w_shots")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.w_shots)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_9 = QtGui.QWidget(self.w_shots)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.l_sShot = QtGui.QLabel(self.widget_9)
        self.l_sShot.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_sShot.setObjectName("l_sShot")
        self.horizontalLayout_15.addWidget(self.l_sShot)
        self.b_shotSearch = QtGui.QToolButton(self.widget_9)
        self.b_shotSearch.setText("")
        self.b_shotSearch.setCheckable(True)
        self.b_shotSearch.setAutoRaise(True)
        self.b_shotSearch.setObjectName("b_shotSearch")
        self.horizontalLayout_15.addWidget(self.b_shotSearch)
        self.verticalLayout_18.addWidget(self.widget_9)
        self.w_shotSearch = QtGui.QWidget(self.w_shots)
        self.w_shotSearch.setObjectName("w_shotSearch")
        self.verticalLayout = QtGui.QVBoxLayout(self.w_shotSearch)
        self.verticalLayout.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.e_shotSearch = QtGui.QLineEdit(self.w_shotSearch)
        self.e_shotSearch.setObjectName("e_shotSearch")
        self.verticalLayout.addWidget(self.e_shotSearch)
        self.verticalLayout_18.addWidget(self.w_shotSearch)
        self.tw_sShot = QtGui.QTreeWidget(self.w_shots)
        self.tw_sShot.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_sShot.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_sShot.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_sShot.setIndentation(10)
        self.tw_sShot.setObjectName("tw_sShot")
        self.tw_sShot.headerItem().setText(0, "1")
        self.tw_sShot.header().setVisible(False)
        self.verticalLayout_18.addWidget(self.tw_sShot)
        self.horizontalLayout_7.addWidget(self.w_shots)
        self.verticalWidget_2 = QtGui.QWidget(self.t_shots)
        self.verticalWidget_2.setMaximumSize(QtCore.QSize(272, 16777215))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalWidget = QtGui.QWidget(self.verticalWidget_2)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_22 = QtGui.QWidget(self.horizontalWidget)
        self.widget_22.setMinimumSize(QtCore.QSize(80, 0))
        self.widget_22.setMaximumSize(QtCore.QSize(80, 16777215))
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.widget_22)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.l_sStep = QtGui.QLabel(self.widget_22)
        self.l_sStep.setObjectName("l_sStep")
        self.verticalLayout_16.addWidget(self.l_sStep)
        self.lw_sPipeline = QtGui.QListWidget(self.widget_22)
        self.lw_sPipeline.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.lw_sPipeline.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_sPipeline.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lw_sPipeline.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_sPipeline.setObjectName("lw_sPipeline")
        self.verticalLayout_16.addWidget(self.lw_sPipeline)
        self.horizontalLayout_9.addWidget(self.widget_22)
        self.widget_15 = QtGui.QWidget(self.horizontalWidget)
        self.widget_15.setMinimumSize(QtCore.QSize(120, 0))
        self.widget_15.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_15)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.l_sCategory = QtGui.QLabel(self.widget_15)
        self.l_sCategory.setObjectName("l_sCategory")
        self.verticalLayout_9.addWidget(self.l_sCategory)
        self.lw_sCategory = QtGui.QListWidget(self.widget_15)
        self.lw_sCategory.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.lw_sCategory.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_sCategory.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lw_sCategory.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_sCategory.setObjectName("lw_sCategory")
        self.verticalLayout_9.addWidget(self.lw_sCategory)
        self.horizontalLayout_9.addWidget(self.widget_15)
        self.verticalLayout_17.addWidget(self.horizontalWidget)
        self.gb_shotInfo = QtGui.QGroupBox(self.verticalWidget_2)
        self.gb_shotInfo.setMinimumSize(QtCore.QSize(0, 220))
        self.gb_shotInfo.setMaximumSize(QtCore.QSize(16777215, 220))
        self.gb_shotInfo.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gb_shotInfo.setObjectName("gb_shotInfo")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.gb_shotInfo)
        self.verticalLayout_19.setSpacing(15)
        self.verticalLayout_19.setContentsMargins(9, 18, 9, 9)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.l_framerange = QtGui.QLabel(self.gb_shotInfo)
        self.l_framerange.setObjectName("l_framerange")
        self.verticalLayout_19.addWidget(self.l_framerange)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem5)
        self.widget = QtGui.QWidget(self.gb_shotInfo)
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.l_shotPreview = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_shotPreview.sizePolicy().hasHeightForWidth())
        self.l_shotPreview.setSizePolicy(sizePolicy)
        self.l_shotPreview.setMinimumSize(QtCore.QSize(100, 100))
        self.l_shotPreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_shotPreview.setText("")
        self.l_shotPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_shotPreview.setObjectName("l_shotPreview")
        self.horizontalLayout_8.addWidget(self.l_shotPreview)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_19.addWidget(self.widget)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem8)
        self.verticalLayout_17.addWidget(self.gb_shotInfo)
        self.horizontalLayout_7.addWidget(self.verticalWidget_2)
        self.widget_11 = QtGui.QWidget(self.t_shots)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_11)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_16 = QtGui.QWidget(self.widget_11)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_16)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.l_sFiles = QtGui.QLabel(self.widget_16)
        self.l_sFiles.setObjectName("l_sFiles")
        self.verticalLayout_10.addWidget(self.l_sFiles)
        self.tw_sFiles = QtGui.QTableView(self.widget_16)
        self.tw_sFiles.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_sFiles.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_sFiles.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tw_sFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tw_sFiles.setTextElideMode(QtCore.Qt.ElideRight)
        self.tw_sFiles.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_sFiles.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_sFiles.setSortingEnabled(True)
        self.tw_sFiles.setObjectName("tw_sFiles")
        self.tw_sFiles.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_sFiles.horizontalHeader().setHighlightSections(False)
        self.tw_sFiles.horizontalHeader().setSortIndicatorShown(True)
        self.tw_sFiles.horizontalHeader().setStretchLastSection(False)
        self.tw_sFiles.verticalHeader().setVisible(False)
        self.tw_sFiles.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_10.addWidget(self.tw_sFiles)
        self.verticalLayout_6.addWidget(self.widget_16)
        self.w_sShowFormats = QtGui.QWidget(self.widget_11)
        self.w_sShowFormats.setObjectName("w_sShowFormats")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.w_sShowFormats)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_sShow = QtGui.QLabel(self.w_sShowFormats)
        self.l_sShow.setObjectName("l_sShow")
        self.horizontalLayout_12.addWidget(self.l_sShow)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_6.addWidget(self.w_sShowFormats)
        self.horizontalLayout_7.addWidget(self.widget_11)
        self.tbw_browser.addTab(self.t_shots, "")
        self.t_recent = QtGui.QWidget()
        self.t_recent.setObjectName("t_recent")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.t_recent)
        self.horizontalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tw_recent = QtGui.QTableView(self.t_recent)
        self.tw_recent.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_recent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tw_recent.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_recent.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tw_recent.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tw_recent.setTextElideMode(QtCore.Qt.ElideNone)
        self.tw_recent.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_recent.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_recent.setSortingEnabled(False)
        self.tw_recent.setObjectName("tw_recent")
        self.tw_recent.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_recent.horizontalHeader().setHighlightSections(False)
        self.tw_recent.horizontalHeader().setSortIndicatorShown(False)
        self.tw_recent.horizontalHeader().setStretchLastSection(True)
        self.tw_recent.verticalHeader().setVisible(False)
        self.tw_recent.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.tw_recent)
        self.tbw_browser.addTab(self.t_recent, "")
        self.verticalLayout_14.addWidget(self.tbw_browser)
        self.gb_renderings = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_renderings.sizePolicy().hasHeightForWidth())
        self.gb_renderings.setSizePolicy(sizePolicy)
        self.gb_renderings.setObjectName("gb_renderings")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.gb_renderings)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_5 = QtGui.QWidget(self.gb_renderings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.l_task = QtGui.QLabel(self.widget_5)
        self.l_task.setObjectName("l_task")
        self.verticalLayout_8.addWidget(self.l_task)
        self.lw_task = QtGui.QListWidget(self.widget_5)
        self.lw_task.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_task.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lw_task.setObjectName("lw_task")
        self.verticalLayout_8.addWidget(self.lw_task)
        self.widget1 = QtGui.QWidget(self.widget_5)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chb_autoUpdate = QtGui.QCheckBox(self.widget1)
        self.chb_autoUpdate.setChecked(True)
        self.chb_autoUpdate.setObjectName("chb_autoUpdate")
        self.horizontalLayout_10.addWidget(self.chb_autoUpdate)
        self.b_refresh = QtGui.QPushButton(self.widget1)
        self.b_refresh.setEnabled(False)
        self.b_refresh.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_refresh.setObjectName("b_refresh")
        self.horizontalLayout_10.addWidget(self.b_refresh)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_8.addWidget(self.widget1)
        self.horizontalLayout_5.addWidget(self.widget_5)
        self.widget_2 = QtGui.QWidget(self.gb_renderings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.l_version = QtGui.QLabel(self.widget_2)
        self.l_version.setObjectName("l_version")
        self.verticalLayout_11.addWidget(self.l_version)
        self.lw_version = QtGui.QListWidget(self.widget_2)
        self.lw_version.setMaximumSize(QtCore.QSize(16777215, 9999))
        self.lw_version.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_version.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lw_version.setObjectName("lw_version")
        self.verticalLayout_11.addWidget(self.lw_version)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.verticalWidget_21 = QtGui.QWidget(self.gb_renderings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_21.sizePolicy().hasHeightForWidth())
        self.verticalWidget_21.setSizePolicy(sizePolicy)
        self.verticalWidget_21.setObjectName("verticalWidget_21")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.verticalWidget_21)
        self.verticalLayout_15.setContentsMargins(1, 9, 10, 9)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.l_layer = QtGui.QLabel(self.verticalWidget_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_layer.sizePolicy().hasHeightForWidth())
        self.l_layer.setSizePolicy(sizePolicy)
        self.l_layer.setMaximumSize(QtCore.QSize(16777215, 13))
        self.l_layer.setObjectName("l_layer")
        self.verticalLayout_15.addWidget(self.l_layer)
        self.cb_layer = QtGui.QComboBox(self.verticalWidget_21)
        self.cb_layer.setObjectName("cb_layer")
        self.verticalLayout_15.addWidget(self.cb_layer)
        self.l_compare = QtGui.QLabel(self.verticalWidget_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_compare.sizePolicy().hasHeightForWidth())
        self.l_compare.setSizePolicy(sizePolicy)
        self.l_compare.setMaximumSize(QtCore.QSize(16777215, 16))
        self.l_compare.setObjectName("l_compare")
        self.verticalLayout_15.addWidget(self.l_compare)
        self.lw_compare = QtGui.QListWidget(self.verticalWidget_21)
        self.lw_compare.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lw_compare.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_compare.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lw_compare.setObjectName("lw_compare")
        self.verticalLayout_15.addWidget(self.lw_compare)
        self.w_rvButtons = QtGui.QWidget(self.verticalWidget_21)
        self.w_rvButtons.setObjectName("w_rvButtons")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.w_rvButtons)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.b_addRV = QtGui.QPushButton(self.w_rvButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_addRV.sizePolicy().hasHeightForWidth())
        self.b_addRV.setSizePolicy(sizePolicy)
        self.b_addRV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_addRV.setFont(font)
        self.b_addRV.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addRV.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_addRV.setCheckable(False)
        self.b_addRV.setObjectName("b_addRV")
        self.horizontalLayout_11.addWidget(self.b_addRV)
        self.b_compareRV = QtGui.QPushButton(self.w_rvButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_compareRV.sizePolicy().hasHeightForWidth())
        self.b_compareRV.setSizePolicy(sizePolicy)
        self.b_compareRV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_compareRV.setFont(font)
        self.b_compareRV.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_compareRV.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_compareRV.setCheckable(False)
        self.b_compareRV.setObjectName("b_compareRV")
        self.horizontalLayout_11.addWidget(self.b_compareRV)
        self.b_combineVersions = QtGui.QPushButton(self.w_rvButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_combineVersions.sizePolicy().hasHeightForWidth())
        self.b_combineVersions.setSizePolicy(sizePolicy)
        self.b_combineVersions.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_combineVersions.setFont(font)
        self.b_combineVersions.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_combineVersions.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_combineVersions.setCheckable(False)
        self.b_combineVersions.setObjectName("b_combineVersions")
        self.horizontalLayout_11.addWidget(self.b_combineVersions)
        self.b_clearRV = QtGui.QPushButton(self.w_rvButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_clearRV.sizePolicy().hasHeightForWidth())
        self.b_clearRV.setSizePolicy(sizePolicy)
        self.b_clearRV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_clearRV.setFont(font)
        self.b_clearRV.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_clearRV.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_clearRV.setCheckable(False)
        self.b_clearRV.setObjectName("b_clearRV")
        self.horizontalLayout_11.addWidget(self.b_clearRV)
        self.verticalLayout_15.addWidget(self.w_rvButtons)
        self.horizontalLayout_5.addWidget(self.verticalWidget_21)
        self.widget_7 = QtGui.QWidget(self.gb_renderings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(309, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(309, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.w_info = QtGui.QWidget(self.widget_7)
        self.w_info.setMaximumSize(QtCore.QSize(16777215, 35))
        self.w_info.setObjectName("w_info")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.w_info)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.l_info = QtGui.QLabel(self.w_info)
        self.l_info.setMaximumSize(QtCore.QSize(16777215, 13))
        self.l_info.setText("")
        self.l_info.setObjectName("l_info")
        self.verticalLayout_20.addWidget(self.l_info)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem11)
        self.l_date = QtGui.QLabel(self.w_info)
        self.l_date.setMaximumSize(QtCore.QSize(16777215, 13))
        self.l_date.setText("")
        self.l_date.setObjectName("l_date")
        self.verticalLayout_20.addWidget(self.l_date)
        self.verticalLayout_12.addWidget(self.w_info)
        self.l_preview = QtGui.QLabel(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_preview.sizePolicy().hasHeightForWidth())
        self.l_preview.setSizePolicy(sizePolicy)
        self.l_preview.setMinimumSize(QtCore.QSize(300, 169))
        self.l_preview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_preview.setText("")
        self.l_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_preview.setObjectName("l_preview")
        self.verticalLayout_12.addWidget(self.l_preview)
        self.sl_preview = QtGui.QSlider(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sl_preview.sizePolicy().hasHeightForWidth())
        self.sl_preview.setSizePolicy(sizePolicy)
        self.sl_preview.setMinimumSize(QtCore.QSize(299, 0))
        self.sl_preview.setOrientation(QtCore.Qt.Horizontal)
        self.sl_preview.setObjectName("sl_preview")
        self.verticalLayout_12.addWidget(self.sl_preview)
        self.horizontalLayout_5.addWidget(self.widget_7)
        self.verticalLayout_14.addWidget(self.gb_renderings)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.scrollArea)
        mw_ProjectBrowser.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mw_ProjectBrowser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1311, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuRecentProjects = QtGui.QMenu(self.menuTools)
        self.menuRecentProjects.setObjectName("menuRecentProjects")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        mw_ProjectBrowser.setMenuBar(self.menubar)
        self.actionPrismSettings = QtGui.QAction(mw_ProjectBrowser)
        self.actionPrismSettings.setObjectName("actionPrismSettings")
        self.actionRefresh = QtGui.QAction(mw_ProjectBrowser)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionAssets = QtGui.QAction(mw_ProjectBrowser)
        self.actionAssets.setCheckable(True)
        self.actionAssets.setChecked(True)
        self.actionAssets.setObjectName("actionAssets")
        self.actionShots = QtGui.QAction(mw_ProjectBrowser)
        self.actionShots.setCheckable(True)
        self.actionShots.setChecked(True)
        self.actionShots.setObjectName("actionShots")
        self.actionFiles = QtGui.QAction(mw_ProjectBrowser)
        self.actionFiles.setCheckable(True)
        self.actionFiles.setChecked(True)
        self.actionFiles.setObjectName("actionFiles")
        self.actionRecent = QtGui.QAction(mw_ProjectBrowser)
        self.actionRecent.setCheckable(True)
        self.actionRecent.setChecked(True)
        self.actionRecent.setObjectName("actionRecent")
        self.actionOpenOnStart = QtGui.QAction(mw_ProjectBrowser)
        self.actionOpenOnStart.setCheckable(True)
        self.actionOpenOnStart.setChecked(True)
        self.actionOpenOnStart.setObjectName("actionOpenOnStart")
        self.actionRenderWatch = QtGui.QAction(mw_ProjectBrowser)
        self.actionRenderWatch.setObjectName("actionRenderWatch")
        self.actionStateManager = QtGui.QAction(mw_ProjectBrowser)
        self.actionStateManager.setObjectName("actionStateManager")
        self.actionCloseAfterLoad = QtGui.QAction(mw_ProjectBrowser)
        self.actionCloseAfterLoad.setCheckable(True)
        self.actionCloseAfterLoad.setChecked(True)
        self.actionCloseAfterLoad.setObjectName("actionCloseAfterLoad")
        self.actionAutoplay = QtGui.QAction(mw_ProjectBrowser)
        self.actionAutoplay.setCheckable(True)
        self.actionAutoplay.setChecked(False)
        self.actionAutoplay.setObjectName("actionAutoplay")
        self.actionRenderings = QtGui.QAction(mw_ProjectBrowser)
        self.actionRenderings.setCheckable(True)
        self.actionRenderings.setChecked(True)
        self.actionRenderings.setObjectName("actionRenderings")
        self.actionTest = QtGui.QAction(mw_ProjectBrowser)
        self.actionTest.setObjectName("actionTest")
        self.actionCheckForUpdates = QtGui.QAction(mw_ProjectBrowser)
        self.actionCheckForUpdates.setCheckable(True)
        self.actionCheckForUpdates.setChecked(True)
        self.actionCheckForUpdates.setObjectName("actionCheckForUpdates")
        self.actionCheckForShotFrameRange = QtGui.QAction(mw_ProjectBrowser)
        self.actionCheckForShotFrameRange.setCheckable(True)
        self.actionCheckForShotFrameRange.setChecked(True)
        self.actionCheckForShotFrameRange.setObjectName("actionCheckForShotFrameRange")
        self.menuTools.addAction(self.actionOpenOnStart)
        self.menuTools.addAction(self.actionCheckForUpdates)
        self.menuTools.addAction(self.actionCheckForShotFrameRange)
        self.menuTools.addAction(self.actionCloseAfterLoad)
        self.menuTools.addAction(self.actionAutoplay)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionStateManager)
        self.menuTools.addAction(self.actionPrismSettings)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuRecentProjects.menuAction())
        self.menuView.addAction(self.actionAssets)
        self.menuView.addAction(self.actionShots)
        self.menuView.addAction(self.actionRecent)
        self.menuView.addAction(self.actionRenderings)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(mw_ProjectBrowser)
        self.tbw_browser.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mw_ProjectBrowser)

    def retranslateUi(self, mw_ProjectBrowser):
        mw_ProjectBrowser.setWindowTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "ProjectBrowser", None, QtGui.QApplication.UnicodeUTF8))
        self.l_aHierarchy.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Assets:", None, QtGui.QApplication.UnicodeUTF8))
        self.e_assetSearch.setPlaceholderText(QtGui.QApplication.translate("mw_ProjectBrowser", "Search...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_aStep.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_aCategory.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Categories:", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_assetInfo.setTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "Assetinfo", None, QtGui.QApplication.UnicodeUTF8))
        self.l_aFiles.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_aShow.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Show file types:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbw_browser.setTabText(self.tbw_browser.indexOf(self.t_assets), QtGui.QApplication.translate("mw_ProjectBrowser", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sShot.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Shots:", None, QtGui.QApplication.UnicodeUTF8))
        self.e_shotSearch.setPlaceholderText(QtGui.QApplication.translate("mw_ProjectBrowser", "Search...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sStep.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sCategory.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Categories:", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_shotInfo.setTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "Shotinfo", None, QtGui.QApplication.UnicodeUTF8))
        self.l_framerange.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Framerange:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sFiles.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sShow.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Show file types:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbw_browser.setTabText(self.tbw_browser.indexOf(self.t_shots), QtGui.QApplication.translate("mw_ProjectBrowser", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.tbw_browser.setTabText(self.tbw_browser.indexOf(self.t_recent), QtGui.QApplication.translate("mw_ProjectBrowser", "Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_renderings.setTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "Renders", None, QtGui.QApplication.UnicodeUTF8))
        self.l_task.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Tasks:", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_autoUpdate.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Auto update", None, QtGui.QApplication.UnicodeUTF8))
        self.b_refresh.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Refresh Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.l_version.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Versions:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_layer.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Layers:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_compare.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Collected Versions:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addRV.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.b_compareRV.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Compare", None, QtGui.QApplication.UnicodeUTF8))
        self.b_combineVersions.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Combine", None, QtGui.QApplication.UnicodeUTF8))
        self.b_clearRV.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentProjects.setTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "Recent projects", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("mw_ProjectBrowser", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrismSettings.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Prism Settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAssets.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShots.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFiles.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenOnStart.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Open on startup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRenderWatch.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "RenderWatch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStateManager.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "State Manager...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseAfterLoad.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Close after loading", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoplay.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Autoplay preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRenderings.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Renderings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckForUpdates.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Check for latest import version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckForShotFrameRange.setText(QtGui.QApplication.translate("mw_ProjectBrowser", "Check for shot frame range", None, QtGui.QApplication.UnicodeUTF8))

