# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SceneBrowser.ui'
#
# Created: Tue Mar  7 10:20:23 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_w_sceneBrowser(object):
    def setupUi(self, w_sceneBrowser):
        w_sceneBrowser.setObjectName("w_sceneBrowser")
        w_sceneBrowser.resize(801, 499)
        self.horizontalLayout = QtWidgets.QHBoxLayout(w_sceneBrowser)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_5 = QtWidgets.QSplitter(w_sceneBrowser)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.verticalWidget_3 = QtWidgets.QWidget(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_3.sizePolicy().hasHeightForWidth())
        self.verticalWidget_3.setSizePolicy(sizePolicy)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.verticalWidget_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.splitter = QtWidgets.QSplitter(self.horizontalWidget_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_23 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.w_departmentsHeader = QtWidgets.QWidget(self.widget_23)
        self.w_departmentsHeader.setObjectName("w_departmentsHeader")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.w_departmentsHeader)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_departments = QtWidgets.QLabel(self.w_departmentsHeader)
        self.l_departments.setObjectName("l_departments")
        self.verticalLayout_3.addWidget(self.l_departments)
        self.verticalLayout_22.addWidget(self.w_departmentsHeader)
        self.lw_departments = QtWidgets.QListWidget(self.widget_23)
        self.lw_departments.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_departments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lw_departments.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw_departments.setObjectName("lw_departments")
        self.verticalLayout_22.addWidget(self.lw_departments)
        self.w_tasks = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_tasks.sizePolicy().hasHeightForWidth())
        self.w_tasks.setSizePolicy(sizePolicy)
        self.w_tasks.setObjectName("w_tasks")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.w_tasks)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.w_tasksHeader = QtWidgets.QWidget(self.w_tasks)
        self.w_tasksHeader.setObjectName("w_tasksHeader")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.w_tasksHeader)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.l_tasks = QtWidgets.QLabel(self.w_tasksHeader)
        self.l_tasks.setObjectName("l_tasks")
        self.verticalLayout_5.addWidget(self.l_tasks)
        self.verticalLayout_23.addWidget(self.w_tasksHeader)
        self.lw_tasks = QtWidgets.QListWidget(self.w_tasks)
        self.lw_tasks.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.lw_tasks.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_tasks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lw_tasks.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw_tasks.setObjectName("lw_tasks")
        self.verticalLayout_23.addWidget(self.lw_tasks)
        self.horizontalLayout_13.addWidget(self.splitter)
        self.gb_entityInfo = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gb_entityInfo.sizePolicy().hasHeightForWidth())
        self.gb_entityInfo.setSizePolicy(sizePolicy)
        self.gb_entityInfo.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gb_entityInfo.setObjectName("gb_entityInfo")
        self.lo_entityDetails = QtWidgets.QVBoxLayout(self.gb_entityInfo)
        self.lo_entityDetails.setSpacing(15)
        self.lo_entityDetails.setContentsMargins(9, 18, 9, 0)
        self.lo_entityDetails.setObjectName("lo_entityDetails")
        self.w_entityInfo = QtWidgets.QWidget(self.gb_entityInfo)
        self.w_entityInfo.setObjectName("w_entityInfo")
        self.lo_entityInfo = QtWidgets.QGridLayout(self.w_entityInfo)
        self.lo_entityInfo.setContentsMargins(0, 0, 0, 0)
        self.lo_entityInfo.setObjectName("lo_entityInfo")
        self.lo_entityDetails.addWidget(self.w_entityInfo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.lo_entityDetails.addItem(spacerItem)
        self.widget_8 = QtWidgets.QWidget(self.gb_entityInfo)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.l_entityPreview = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_entityPreview.sizePolicy().hasHeightForWidth())
        self.l_entityPreview.setSizePolicy(sizePolicy)
        self.l_entityPreview.setMinimumSize(QtCore.QSize(100, 100))
        self.l_entityPreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_entityPreview.setText("")
        self.l_entityPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_entityPreview.setObjectName("l_entityPreview")
        self.horizontalLayout_14.addWidget(self.l_entityPreview)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.lo_entityDetails.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.widget_4 = QtWidgets.QWidget(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.w_scenefileHeader = QtWidgets.QWidget(self.widget_4)
        self.w_scenefileHeader.setObjectName("w_scenefileHeader")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.w_scenefileHeader)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_scenefiles = QtWidgets.QLabel(self.w_scenefileHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_scenefiles.sizePolicy().hasHeightForWidth())
        self.l_scenefiles.setSizePolicy(sizePolicy)
        self.l_scenefiles.setObjectName("l_scenefiles")
        self.horizontalLayout_12.addWidget(self.l_scenefiles)
        self.widget = QtWidgets.QWidget(self.w_scenefileHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_sceneLayoutItems = QtWidgets.QToolButton(self.widget)
        self.b_sceneLayoutItems.setCheckable(True)
        self.b_sceneLayoutItems.setObjectName("b_sceneLayoutItems")
        self.horizontalLayout_2.addWidget(self.b_sceneLayoutItems)
        self.b_sceneLayoutList = QtWidgets.QToolButton(self.widget)
        self.b_sceneLayoutList.setCheckable(True)
        self.b_sceneLayoutList.setChecked(False)
        self.b_sceneLayoutList.setObjectName("b_sceneLayoutList")
        self.horizontalLayout_2.addWidget(self.b_sceneLayoutList)
        self.horizontalLayout_12.addWidget(self.widget)
        self.b_scenefilter = QtWidgets.QToolButton(self.w_scenefileHeader)
        self.b_scenefilter.setArrowType(QtCore.Qt.DownArrow)
        self.b_scenefilter.setObjectName("b_scenefilter")
        self.horizontalLayout_12.addWidget(self.b_scenefilter)
        self.verticalLayout_4.addWidget(self.w_scenefileHeader)
        self.sw_scenefiles = QtWidgets.QStackedWidget(self.widget_4)
        self.sw_scenefiles.setObjectName("sw_scenefiles")
        self.w_scenePage1 = QtWidgets.QWidget()
        self.w_scenePage1.setObjectName("w_scenePage1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.w_scenePage1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tw_scenefiles = QtWidgets.QTableView(self.w_scenePage1)
        self.tw_scenefiles.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_scenefiles.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_scenefiles.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_scenefiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_scenefiles.setTextElideMode(QtCore.Qt.ElideRight)
        self.tw_scenefiles.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_scenefiles.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_scenefiles.setSortingEnabled(True)
        self.tw_scenefiles.setObjectName("tw_scenefiles")
        self.tw_scenefiles.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_scenefiles.horizontalHeader().setHighlightSections(False)
        self.tw_scenefiles.horizontalHeader().setSortIndicatorShown(True)
        self.tw_scenefiles.horizontalHeader().setStretchLastSection(False)
        self.tw_scenefiles.verticalHeader().setVisible(False)
        self.tw_scenefiles.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.tw_scenefiles)
        self.sw_scenefiles.addWidget(self.w_scenePage1)
        self.w_scenePage2 = QtWidgets.QWidget()
        self.w_scenePage2.setObjectName("w_scenePage2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.w_scenePage2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sa_scenefileItems = QtWidgets.QScrollArea(self.w_scenePage2)
        self.sa_scenefileItems.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sa_scenefileItems.setWidgetResizable(True)
        self.sa_scenefileItems.setObjectName("sa_scenefileItems")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 554, 451))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.sa_scenefileItems.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sa_scenefileItems)
        self.sw_scenefiles.addWidget(self.w_scenePage2)
        self.verticalLayout_4.addWidget(self.sw_scenefiles)
        self.horizontalLayout.addWidget(self.splitter_5)

        self.retranslateUi(w_sceneBrowser)
        self.sw_scenefiles.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(w_sceneBrowser)

    def retranslateUi(self, w_sceneBrowser):
        w_sceneBrowser.setWindowTitle(QtWidgets.QApplication.translate("", "Scene Browser", None, -1))
        self.l_departments.setText(QtWidgets.QApplication.translate("", "Departments:", None, -1))
        self.l_tasks.setText(QtWidgets.QApplication.translate("", "Tasks:", None, -1))
        self.gb_entityInfo.setTitle(QtWidgets.QApplication.translate("", "Entityinfo", None, -1))
        self.l_scenefiles.setText(QtWidgets.QApplication.translate("", "Files:", None, -1))
        self.b_sceneLayoutItems.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.b_sceneLayoutList.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.b_scenefilter.setText(QtWidgets.QApplication.translate("", "...", None, -1))

