# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskSelection.ui',
# licensing of 'TaskSelection.ui' applies.
#
# Created: Wed Nov 25 17:14:38 2020
#      by: pyside2-uic  running on PySide2 5.9.0a1.dev1528389443
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dlg_TaskSelection(object):
    def setupUi(self, dlg_TaskSelection):
        dlg_TaskSelection.setObjectName("dlg_TaskSelection")
        dlg_TaskSelection.resize(1294, 696)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(dlg_TaskSelection)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(dlg_TaskSelection)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_paths = QtWidgets.QWidget(self.widget)
        self.w_paths.setObjectName("w_paths")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.w_paths)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l_paths = QtWidgets.QLabel(self.w_paths)
        self.l_paths.setObjectName("l_paths")
        self.horizontalLayout_3.addWidget(self.l_paths)
        self.cb_paths = QtWidgets.QComboBox(self.w_paths)
        self.cb_paths.setObjectName("cb_paths")
        self.horizontalLayout_3.addWidget(self.cb_paths)
        self.verticalLayout.addWidget(self.w_paths)
        self.tbw_entity = QtWidgets.QTabWidget(self.widget)
        self.tbw_entity.setObjectName("tbw_entity")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tw_assets = QtWidgets.QTreeWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_assets.sizePolicy().hasHeightForWidth())
        self.tw_assets.setSizePolicy(sizePolicy)
        self.tw_assets.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_assets.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_assets.setObjectName("tw_assets")
        self.tw_assets.headerItem().setText(0, "1")
        self.tw_assets.header().setVisible(False)
        self.verticalLayout_5.addWidget(self.tw_assets)
        self.tbw_entity.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tw_shots = QtWidgets.QTreeWidget(self.tab_2)
        self.tw_shots.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.tw_shots.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_shots.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_shots.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_shots.setIndentation(10)
        self.tw_shots.setObjectName("tw_shots")
        self.tw_shots.headerItem().setText(0, "1")
        self.tw_shots.header().setVisible(False)
        self.verticalLayout_6.addWidget(self.tw_shots)
        self.tbw_entity.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tbw_entity)
        self.b_custom = QtWidgets.QPushButton(self.widget)
        self.b_custom.setObjectName("b_custom")
        self.verticalLayout.addWidget(self.b_custom)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lw_tasks = QtWidgets.QListWidget(self.widget_2)
        self.lw_tasks.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_tasks.setObjectName("lw_tasks")
        self.verticalLayout_3.addWidget(self.lw_tasks)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_version = QtWidgets.QLabel(self.widget_5)
        self.l_version.setObjectName("l_version")
        self.horizontalLayout.addWidget(self.l_version)
        self.l_versionRight = QtWidgets.QLabel(self.widget_5)
        self.l_versionRight.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_versionRight.setText("")
        self.l_versionRight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_versionRight.setObjectName("l_versionRight")
        self.horizontalLayout.addWidget(self.l_versionRight)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.tw_versions = QtWidgets.QTableWidget(self.widget_3)
        self.tw_versions.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_versions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_versions.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_versions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_versions.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_versions.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_versions.setObjectName("tw_versions")
        self.tw_versions.setColumnCount(0)
        self.tw_versions.setRowCount(0)
        self.tw_versions.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_versions.horizontalHeader().setHighlightSections(False)
        self.tw_versions.horizontalHeader().setMinimumSectionSize(0)
        self.tw_versions.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tw_versions)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.widget_4)

        self.retranslateUi(dlg_TaskSelection)
        self.tbw_entity.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlg_TaskSelection)

    def retranslateUi(self, dlg_TaskSelection):
        dlg_TaskSelection.setWindowTitle(QtWidgets.QApplication.translate("dlg_TaskSelection", "Import Task", None, -1))
        self.l_paths.setText(QtWidgets.QApplication.translate("dlg_TaskSelection", "Location:", None, -1))
        self.tbw_entity.setTabText(self.tbw_entity.indexOf(self.tab), QtWidgets.QApplication.translate("dlg_TaskSelection", "Assets", None, -1))
        self.tbw_entity.setTabText(self.tbw_entity.indexOf(self.tab_2), QtWidgets.QApplication.translate("dlg_TaskSelection", "Shots", None, -1))
        self.b_custom.setText(QtWidgets.QApplication.translate("dlg_TaskSelection", "Import custom files", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dlg_TaskSelection", "Tasks:", None, -1))
        self.l_version.setText(QtWidgets.QApplication.translate("dlg_TaskSelection", "Version:", None, -1))
        self.tw_versions.setSortingEnabled(True)

