# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateProject.ui'
#
# Created: Tue Aug  8 18:12:49 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_dlg_createProject(object):
    def setupUi(self, dlg_createProject):
        dlg_createProject.setObjectName("dlg_createProject")
        dlg_createProject.resize(726, 418)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(dlg_createProject)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(dlg_createProject)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sw_project = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.sw_project.setObjectName("sw_project")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_start = QtWidgets.QWidget(self.page)
        self.w_start.setObjectName("w_start")
        self.gridLayout = QtWidgets.QGridLayout(self.w_start)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l_preset = QtWidgets.QLabel(self.w_start)
        self.l_preset.setObjectName("l_preset")
        self.gridLayout.addWidget(self.l_preset, 3, 0, 1, 1)
        self.l_name = QtWidgets.QLabel(self.w_start)
        self.l_name.setObjectName("l_name")
        self.gridLayout.addWidget(self.l_name, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 1)
        self.e_path = QtWidgets.QLineEdit(self.w_start)
        self.e_path.setObjectName("e_path")
        self.gridLayout.addWidget(self.e_path, 1, 1, 1, 1)
        self.b_browse = QtWidgets.QToolButton(self.w_start)
        self.b_browse.setObjectName("b_browse")
        self.gridLayout.addWidget(self.b_browse, 1, 2, 1, 1)
        self.l_path = QtWidgets.QLabel(self.w_start)
        self.l_path.setObjectName("l_path")
        self.gridLayout.addWidget(self.l_path, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.w_start)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.l_preview = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_preview.sizePolicy().hasHeightForWidth())
        self.l_preview.setSizePolicy(sizePolicy)
        self.l_preview.setMinimumSize(QtCore.QSize(300, 169))
        self.l_preview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_preview.setObjectName("l_preview")
        self.horizontalLayout_2.addWidget(self.l_preview)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addWidget(self.widget_4, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.w_start)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.e_name = QtWidgets.QLineEdit(self.w_start)
        self.e_name.setObjectName("e_name")
        self.gridLayout.addWidget(self.e_name, 0, 1, 1, 1)
        self.w_preset = QtWidgets.QWidget(self.w_start)
        self.w_preset.setObjectName("w_preset")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.w_preset)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.cb_preset = QtWidgets.QComboBox(self.w_preset)
        self.cb_preset.setObjectName("cb_preset")
        self.horizontalLayout_6.addWidget(self.cb_preset)
        self.b_reload = QtWidgets.QToolButton(self.w_preset)
        self.b_reload.setObjectName("b_reload")
        self.horizontalLayout_6.addWidget(self.b_reload)
        self.b_addPreset = QtWidgets.QToolButton(self.w_preset)
        self.b_addPreset.setObjectName("b_addPreset")
        self.horizontalLayout_6.addWidget(self.b_addPreset)
        self.b_managePresets = QtWidgets.QToolButton(self.w_preset)
        self.b_managePresets.setObjectName("b_managePresets")
        self.horizontalLayout_6.addWidget(self.b_managePresets)
        self.gridLayout.addWidget(self.w_preset, 3, 1, 1, 1)
        self.l_placeholder = QtWidgets.QLabel(self.w_start)
        self.l_placeholder.setText("")
        self.l_placeholder.setObjectName("l_placeholder")
        self.gridLayout.addWidget(self.l_placeholder, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.w_start)
        self.sw_project.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_32 = QtWidgets.QWidget(self.page_2)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_32)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tw_structure = QtWidgets.QTreeWidget(self.widget_32)
        self.tw_structure.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_structure.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_structure.setIndentation(10)
        self.tw_structure.setObjectName("tw_structure")
        self.tw_structure.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.tw_structure)
        self.b_settings = QtWidgets.QPushButton(self.widget_32)
        self.b_settings.setObjectName("b_settings")
        self.verticalLayout_6.addWidget(self.b_settings)
        self.verticalLayout_3.addWidget(self.widget_32)
        self.sw_project.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.sw_project)
        self.w_footer = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_footer.setObjectName("w_footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.w_footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.b_back = QtWidgets.QPushButton(self.w_footer)
        self.b_back.setObjectName("b_back")
        self.horizontalLayout_3.addWidget(self.b_back)
        self.b_next = QtWidgets.QPushButton(self.w_footer)
        self.b_next.setObjectName("b_next")
        self.horizontalLayout_3.addWidget(self.b_next)
        self.b_create = QtWidgets.QPushButton(self.w_footer)
        self.b_create.setObjectName("b_create")
        self.horizontalLayout_3.addWidget(self.b_create)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.w_footer)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_11.addWidget(self.scrollArea)

        self.retranslateUi(dlg_createProject)
        self.sw_project.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlg_createProject)
        dlg_createProject.setTabOrder(self.scrollArea, self.e_name)
        dlg_createProject.setTabOrder(self.e_name, self.e_path)
        dlg_createProject.setTabOrder(self.e_path, self.b_browse)

    def retranslateUi(self, dlg_createProject):
        dlg_createProject.setWindowTitle(QtWidgets.QApplication.translate("", "Create Project", None, -1))
        self.l_preset.setText(QtWidgets.QApplication.translate("", "Preset:", None, -1))
        self.l_name.setText(QtWidgets.QApplication.translate("", "Project Name:", None, -1))
        self.b_browse.setToolTip(QtWidgets.QApplication.translate("", "browse", None, -1))
        self.b_browse.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.l_path.setText(QtWidgets.QApplication.translate("", "Project Path:", None, -1))
        self.l_preview.setText(QtWidgets.QApplication.translate("", "Preview image", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("", "Image (optional):", None, -1))
        self.b_reload.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.b_addPreset.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.b_managePresets.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.b_settings.setText(QtWidgets.QApplication.translate("", "Customize Project Settings...", None, -1))
        self.b_back.setText(QtWidgets.QApplication.translate("", "Back", None, -1))
        self.b_next.setText(QtWidgets.QApplication.translate("", "Edit Settings", None, -1))
        self.b_create.setText(QtWidgets.QApplication.translate("", "Create", None, -1))

