# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectSettings.ui'
#
# Created: Sat Sep  2 16:16:29 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_dlg_ProjectSettings(object):
    def setupUi(self, dlg_ProjectSettings):
        dlg_ProjectSettings.setObjectName("dlg_ProjectSettings")
        dlg_ProjectSettings.resize(891, 759)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_ProjectSettings)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(dlg_ProjectSettings)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.lw_categories = QtWidgets.QListWidget(self.splitter)
        self.lw_categories.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw_categories.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw_categories.setObjectName("lw_categories")
        self.tw_settings = QtWidgets.QTabWidget(self.splitter)
        self.tw_settings.setObjectName("tw_settings")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_prjSettings = QtWidgets.QWidget(self.tab_general)
        self.w_prjSettings.setEnabled(True)
        self.w_prjSettings.setObjectName("w_prjSettings")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.w_prjSettings)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem)
        self.widget_5 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.e_curPname = QtWidgets.QLineEdit(self.widget_5)
        self.e_curPname.setMinimumSize(QtCore.QSize(300, 0))
        self.e_curPname.setObjectName("e_curPname")
        self.gridLayout.addWidget(self.e_curPname, 0, 2, 1, 1)
        self.l_curPname = QtWidgets.QLabel(self.widget_5)
        self.l_curPname.setObjectName("l_curPname")
        self.gridLayout.addWidget(self.l_curPname, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.widget_5)
        self.widget_19 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_19)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_curPpath = QtWidgets.QLabel(self.widget_19)
        self.l_curPpath.setText("")
        self.l_curPpath.setObjectName("l_curPpath")
        self.gridLayout_3.addWidget(self.l_curPpath, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.l_curPname_2 = QtWidgets.QLabel(self.widget_19)
        self.l_curPname_2.setObjectName("l_curPname_2")
        self.gridLayout_3.addWidget(self.l_curPname_2, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.widget_19)
        self.widget = QtWidgets.QWidget(self.w_prjSettings)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.l_preview = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_preview.sizePolicy().hasHeightForWidth())
        self.l_preview.setSizePolicy(sizePolicy)
        self.l_preview.setMinimumSize(QtCore.QSize(300, 169))
        self.l_preview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_preview.setObjectName("l_preview")
        self.horizontalLayout.addWidget(self.l_preview)
        self.verticalLayout_9.addWidget(self.widget)
        self.widget_10 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_10)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.chb_curPuseLocal = QtWidgets.QCheckBox(self.widget_10)
        self.chb_curPuseLocal.setText("")
        self.chb_curPuseLocal.setChecked(True)
        self.chb_curPuseLocal.setObjectName("chb_curPuseLocal")
        self.horizontalLayout_5.addWidget(self.chb_curPuseLocal)
        self.verticalLayout_9.addWidget(self.widget_10)
        self.widget_12 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.widget_12)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.chb_curPuseMaster = QtWidgets.QCheckBox(self.widget_12)
        self.chb_curPuseMaster.setText("")
        self.chb_curPuseMaster.setChecked(True)
        self.chb_curPuseMaster.setObjectName("chb_curPuseMaster")
        self.horizontalLayout_16.addWidget(self.chb_curPuseMaster)
        self.verticalLayout_9.addWidget(self.widget_12)
        self.w_useMasterRender = QtWidgets.QWidget(self.w_prjSettings)
        self.w_useMasterRender.setObjectName("w_useMasterRender")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.w_useMasterRender)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_8 = QtWidgets.QLabel(self.w_useMasterRender)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_18.addWidget(self.label_8)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.chb_curPuseMasterRender = QtWidgets.QCheckBox(self.w_useMasterRender)
        self.chb_curPuseMasterRender.setText("")
        self.chb_curPuseMasterRender.setChecked(False)
        self.chb_curPuseMasterRender.setObjectName("chb_curPuseMasterRender")
        self.horizontalLayout_18.addWidget(self.chb_curPuseMasterRender)
        self.verticalLayout_9.addWidget(self.w_useMasterRender)
        self.widget_16 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.l_backupPublishes = QtWidgets.QLabel(self.widget_16)
        self.l_backupPublishes.setObjectName("l_backupPublishes")
        self.horizontalLayout_20.addWidget(self.l_backupPublishes)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.chb_curPbackupPublishes = QtWidgets.QCheckBox(self.widget_16)
        self.chb_curPbackupPublishes.setText("")
        self.chb_curPbackupPublishes.setObjectName("chb_curPbackupPublishes")
        self.horizontalLayout_20.addWidget(self.chb_curPbackupPublishes)
        self.verticalLayout_9.addWidget(self.widget_16)
        self.widget_18 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.l_scenefileLocking = QtWidgets.QLabel(self.widget_18)
        self.l_scenefileLocking.setObjectName("l_scenefileLocking")
        self.horizontalLayout_22.addWidget(self.l_scenefileLocking)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.chb_curPscenefileLocking = QtWidgets.QCheckBox(self.widget_18)
        self.chb_curPscenefileLocking.setText("")
        self.chb_curPscenefileLocking.setObjectName("chb_curPscenefileLocking")
        self.horizontalLayout_22.addWidget(self.chb_curPscenefileLocking)
        self.verticalLayout_9.addWidget(self.widget_18)
        self.widget_20 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.l_matchScenefileVersions = QtWidgets.QLabel(self.widget_20)
        self.l_matchScenefileVersions.setObjectName("l_matchScenefileVersions")
        self.horizontalLayout_23.addWidget(self.l_matchScenefileVersions)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.chb_matchScenefileVersions = QtWidgets.QCheckBox(self.widget_20)
        self.chb_matchScenefileVersions.setText("")
        self.chb_matchScenefileVersions.setObjectName("chb_matchScenefileVersions")
        self.horizontalLayout_23.addWidget(self.chb_matchScenefileVersions)
        self.verticalLayout_9.addWidget(self.widget_20)
        self.widget_17 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.l_requirePublishComment = QtWidgets.QLabel(self.widget_17)
        self.l_requirePublishComment.setObjectName("l_requirePublishComment")
        self.horizontalLayout_21.addWidget(self.l_requirePublishComment)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.chb_curPRequirePublishComment = QtWidgets.QCheckBox(self.widget_17)
        self.chb_curPRequirePublishComment.setText("")
        self.chb_curPRequirePublishComment.setChecked(True)
        self.chb_curPRequirePublishComment.setObjectName("chb_curPRequirePublishComment")
        self.horizontalLayout_21.addWidget(self.chb_curPRequirePublishComment)
        self.sp_publishComment = QtWidgets.QSpinBox(self.widget_17)
        self.sp_publishComment.setSuffix("")
        self.sp_publishComment.setMinimum(1)
        self.sp_publishComment.setMaximum(999)
        self.sp_publishComment.setProperty("value", 3)
        self.sp_publishComment.setObjectName("sp_publishComment")
        self.horizontalLayout_21.addWidget(self.sp_publishComment)
        self.l_publishCommentChars = QtWidgets.QLabel(self.widget_17)
        self.l_publishCommentChars.setObjectName("l_publishCommentChars")
        self.horizontalLayout_21.addWidget(self.l_publishCommentChars)
        self.verticalLayout_9.addWidget(self.widget_17)
        self.widget_11 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.widget_11)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.cb_dependencies = QtWidgets.QComboBox(self.widget_11)
        self.cb_dependencies.setObjectName("cb_dependencies")
        self.cb_dependencies.addItem("")
        self.cb_dependencies.addItem("")
        self.cb_dependencies.addItem("")
        self.horizontalLayout_14.addWidget(self.cb_dependencies)
        self.verticalLayout_9.addWidget(self.widget_11)
        self.w_curPfps = QtWidgets.QWidget(self.w_prjSettings)
        self.w_curPfps.setObjectName("w_curPfps")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.w_curPfps)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.w_curPfps)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.chb_curPuseFps = QtWidgets.QCheckBox(self.w_curPfps)
        self.chb_curPuseFps.setText("")
        self.chb_curPuseFps.setChecked(False)
        self.chb_curPuseFps.setObjectName("chb_curPuseFps")
        self.horizontalLayout_6.addWidget(self.chb_curPuseFps)
        self.sp_curPfps = QtWidgets.QDoubleSpinBox(self.w_curPfps)
        self.sp_curPfps.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_curPfps.setDecimals(3)
        self.sp_curPfps.setMinimum(1.0)
        self.sp_curPfps.setMaximum(9999.99)
        self.sp_curPfps.setProperty("value", 24.0)
        self.sp_curPfps.setObjectName("sp_curPfps")
        self.horizontalLayout_6.addWidget(self.sp_curPfps)
        self.verticalLayout_9.addWidget(self.w_curPfps)
        self.w_prjResolution = QtWidgets.QWidget(self.w_prjSettings)
        self.w_prjResolution.setObjectName("w_prjResolution")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.w_prjResolution)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.l_prjResolution = QtWidgets.QLabel(self.w_prjResolution)
        self.l_prjResolution.setObjectName("l_prjResolution")
        self.horizontalLayout_13.addWidget(self.l_prjResolution)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.chb_prjResolution = QtWidgets.QCheckBox(self.w_prjResolution)
        self.chb_prjResolution.setText("")
        self.chb_prjResolution.setChecked(False)
        self.chb_prjResolution.setObjectName("chb_prjResolution")
        self.horizontalLayout_13.addWidget(self.chb_prjResolution)
        self.sp_prjResolutionWidth = QtWidgets.QSpinBox(self.w_prjResolution)
        self.sp_prjResolutionWidth.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_prjResolutionWidth.setMinimum(1)
        self.sp_prjResolutionWidth.setMaximum(100000)
        self.sp_prjResolutionWidth.setProperty("value", 1920)
        self.sp_prjResolutionWidth.setObjectName("sp_prjResolutionWidth")
        self.horizontalLayout_13.addWidget(self.sp_prjResolutionWidth)
        self.l_prjResolutionX = QtWidgets.QLabel(self.w_prjResolution)
        self.l_prjResolutionX.setObjectName("l_prjResolutionX")
        self.horizontalLayout_13.addWidget(self.l_prjResolutionX)
        self.sp_prjResolutionHeight = QtWidgets.QSpinBox(self.w_prjResolution)
        self.sp_prjResolutionHeight.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_prjResolutionHeight.setMinimum(1)
        self.sp_prjResolutionHeight.setMaximum(100000)
        self.sp_prjResolutionHeight.setProperty("value", 1080)
        self.sp_prjResolutionHeight.setObjectName("sp_prjResolutionHeight")
        self.horizontalLayout_13.addWidget(self.sp_prjResolutionHeight)
        self.verticalLayout_9.addWidget(self.w_prjResolution)
        self.w_reqPlugins = QtWidgets.QWidget(self.w_prjSettings)
        self.w_reqPlugins.setObjectName("w_reqPlugins")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.w_reqPlugins)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 1, 1, 1)
        self.e_reqPlugins = QtWidgets.QLineEdit(self.w_reqPlugins)
        self.e_reqPlugins.setMinimumSize(QtCore.QSize(300, 0))
        self.e_reqPlugins.setObjectName("e_reqPlugins")
        self.gridLayout_2.addWidget(self.e_reqPlugins, 0, 2, 1, 1)
        self.b_reqPlugins = QtWidgets.QToolButton(self.w_reqPlugins)
        self.b_reqPlugins.setArrowType(QtCore.Qt.DownArrow)
        self.b_reqPlugins.setObjectName("b_reqPlugins")
        self.gridLayout_2.addWidget(self.b_reqPlugins, 0, 3, 1, 1)
        self.l_reqPlugins = QtWidgets.QLabel(self.w_reqPlugins)
        self.l_reqPlugins.setObjectName("l_reqPlugins")
        self.gridLayout_2.addWidget(self.l_reqPlugins, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.w_reqPlugins)
        self.widget_15 = QtWidgets.QWidget(self.w_prjSettings)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.b_importSettings = QtWidgets.QToolButton(self.widget_15)
        self.b_importSettings.setObjectName("b_importSettings")
        self.horizontalLayout_11.addWidget(self.b_importSettings)
        self.b_exportSettings = QtWidgets.QToolButton(self.widget_15)
        self.b_exportSettings.setObjectName("b_exportSettings")
        self.horizontalLayout_11.addWidget(self.b_exportSettings)
        self.verticalLayout_9.addWidget(self.widget_15)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem15)
        self.verticalLayout_2.addWidget(self.w_prjSettings)
        self.tw_settings.addTab(self.tab_general, "")
        self.tab_departments = QtWidgets.QWidget()
        self.tab_departments.setObjectName("tab_departments")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_departments)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_9 = QtWidgets.QWidget(self.tab_departments)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_4 = QtWidgets.QWidget(self.widget_9)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.w_assetDepartmentHeader = QtWidgets.QWidget(self.widget_4)
        self.w_assetDepartmentHeader.setObjectName("w_assetDepartmentHeader")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.w_assetDepartmentHeader)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.w_assetDepartmentHeader)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.verticalLayout_5.addWidget(self.w_assetDepartmentHeader)
        self.tw_assetDepartments = QtWidgets.QTableWidget(self.widget_4)
        self.tw_assetDepartments.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_assetDepartments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_assetDepartments.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tw_assetDepartments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_assetDepartments.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_assetDepartments.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_assetDepartments.setCornerButtonEnabled(False)
        self.tw_assetDepartments.setColumnCount(2)
        self.tw_assetDepartments.setObjectName("tw_assetDepartments")
        self.tw_assetDepartments.setColumnCount(2)
        self.tw_assetDepartments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_assetDepartments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_assetDepartments.setHorizontalHeaderItem(1, item)
        self.tw_assetDepartments.horizontalHeader().setHighlightSections(False)
        self.tw_assetDepartments.horizontalHeader().setStretchLastSection(True)
        self.tw_assetDepartments.verticalHeader().setHighlightSections(False)
        self.verticalLayout_5.addWidget(self.tw_assetDepartments)
        self.horizontalLayout_10.addWidget(self.widget_4)
        self.widget_7 = QtWidgets.QWidget(self.widget_9)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.w_shotDepartmentHeader = QtWidgets.QWidget(self.widget_7)
        self.w_shotDepartmentHeader.setObjectName("w_shotDepartmentHeader")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.w_shotDepartmentHeader)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.w_shotDepartmentHeader)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.verticalLayout_6.addWidget(self.w_shotDepartmentHeader)
        self.tw_shotDepartments = QtWidgets.QTableWidget(self.widget_7)
        self.tw_shotDepartments.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_shotDepartments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_shotDepartments.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tw_shotDepartments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_shotDepartments.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_shotDepartments.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_shotDepartments.setCornerButtonEnabled(False)
        self.tw_shotDepartments.setColumnCount(2)
        self.tw_shotDepartments.setObjectName("tw_shotDepartments")
        self.tw_shotDepartments.setColumnCount(2)
        self.tw_shotDepartments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_shotDepartments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_shotDepartments.setHorizontalHeaderItem(1, item)
        self.tw_shotDepartments.horizontalHeader().setHighlightSections(False)
        self.tw_shotDepartments.horizontalHeader().setStretchLastSection(True)
        self.tw_shotDepartments.verticalHeader().setHighlightSections(False)
        self.verticalLayout_6.addWidget(self.tw_shotDepartments)
        self.horizontalLayout_10.addWidget(self.widget_7)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.widget_14 = QtWidgets.QWidget(self.tab_departments)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chb_allowAdditionalTasks = QtWidgets.QCheckBox(self.widget_14)
        self.chb_allowAdditionalTasks.setChecked(True)
        self.chb_allowAdditionalTasks.setObjectName("chb_allowAdditionalTasks")
        self.horizontalLayout_7.addWidget(self.chb_allowAdditionalTasks)
        self.verticalLayout_7.addWidget(self.widget_14)
        self.tw_settings.addTab(self.tab_departments, "")
        self.tab_locations = QtWidgets.QWidget()
        self.tab_locations.setObjectName("tab_locations")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_locations)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.w_exportLocationHeader = QtWidgets.QWidget(self.tab_locations)
        self.w_exportLocationHeader.setObjectName("w_exportLocationHeader")
        self.lo_exportLocationsHeader = QtWidgets.QHBoxLayout(self.w_exportLocationHeader)
        self.lo_exportLocationsHeader.setContentsMargins(0, 0, 0, 0)
        self.lo_exportLocationsHeader.setObjectName("lo_exportLocationsHeader")
        self.label_5 = QtWidgets.QLabel(self.w_exportLocationHeader)
        self.label_5.setObjectName("label_5")
        self.lo_exportLocationsHeader.addWidget(self.label_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lo_exportLocationsHeader.addItem(spacerItem16)
        self.verticalLayout_3.addWidget(self.w_exportLocationHeader)
        self.tw_exportPaths = QtWidgets.QTableWidget(self.tab_locations)
        self.tw_exportPaths.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_exportPaths.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_exportPaths.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_exportPaths.setColumnCount(2)
        self.tw_exportPaths.setObjectName("tw_exportPaths")
        self.tw_exportPaths.setColumnCount(2)
        self.tw_exportPaths.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exportPaths.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exportPaths.setHorizontalHeaderItem(1, item)
        self.tw_exportPaths.horizontalHeader().setStretchLastSection(True)
        self.tw_exportPaths.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tw_exportPaths)
        self.widget_6 = QtWidgets.QWidget(self.tab_locations)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.b_addExportPath = QtWidgets.QPushButton(self.widget_6)
        self.b_addExportPath.setObjectName("b_addExportPath")
        self.horizontalLayout_4.addWidget(self.b_addExportPath)
        self.b_removeExportPath = QtWidgets.QPushButton(self.widget_6)
        self.b_removeExportPath.setObjectName("b_removeExportPath")
        self.horizontalLayout_4.addWidget(self.b_removeExportPath)
        self.verticalLayout_3.addWidget(self.widget_6)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem18)
        self.w_renderLocationHeader = QtWidgets.QWidget(self.tab_locations)
        self.w_renderLocationHeader.setObjectName("w_renderLocationHeader")
        self.lo_renderLocationsHeader = QtWidgets.QHBoxLayout(self.w_renderLocationHeader)
        self.lo_renderLocationsHeader.setContentsMargins(0, 0, 0, 0)
        self.lo_renderLocationsHeader.setObjectName("lo_renderLocationsHeader")
        self.label_11 = QtWidgets.QLabel(self.w_renderLocationHeader)
        self.label_11.setObjectName("label_11")
        self.lo_renderLocationsHeader.addWidget(self.label_11)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lo_renderLocationsHeader.addItem(spacerItem19)
        self.verticalLayout_3.addWidget(self.w_renderLocationHeader)
        self.tw_renderPaths = QtWidgets.QTableWidget(self.tab_locations)
        self.tw_renderPaths.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_renderPaths.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tw_renderPaths.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_renderPaths.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_renderPaths.setColumnCount(2)
        self.tw_renderPaths.setObjectName("tw_renderPaths")
        self.tw_renderPaths.setColumnCount(2)
        self.tw_renderPaths.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_renderPaths.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_renderPaths.setHorizontalHeaderItem(1, item)
        self.tw_renderPaths.horizontalHeader().setStretchLastSection(True)
        self.tw_renderPaths.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tw_renderPaths)
        self.widget_8 = QtWidgets.QWidget(self.tab_locations)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem20 = QtWidgets.QSpacerItem(672, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.b_addRenderPath = QtWidgets.QPushButton(self.widget_8)
        self.b_addRenderPath.setObjectName("b_addRenderPath")
        self.horizontalLayout_17.addWidget(self.b_addRenderPath)
        self.b_removeRenderPath = QtWidgets.QPushButton(self.widget_8)
        self.b_removeRenderPath.setObjectName("b_removeRenderPath")
        self.horizontalLayout_17.addWidget(self.b_removeRenderPath)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.tw_settings.addTab(self.tab_locations, "")
        self.tab_folderStructure = QtWidgets.QWidget()
        self.tab_folderStructure.setObjectName("tab_folderStructure")
        self.lo_structureTab = QtWidgets.QGridLayout(self.tab_folderStructure)
        self.lo_structureTab.setObjectName("lo_structureTab")
        self.widget_3 = QtWidgets.QWidget(self.tab_folderStructure)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.b_resetStructure = QtWidgets.QToolButton(self.widget_3)
        self.b_resetStructure.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.b_resetStructure.setObjectName("b_resetStructure")
        self.horizontalLayout_3.addWidget(self.b_resetStructure)
        self.lo_structureTab.addWidget(self.widget_3, 1, 0, 1, 1)
        self.sa_structure = QtWidgets.QScrollArea(self.tab_folderStructure)
        self.sa_structure.setWidgetResizable(True)
        self.sa_structure.setObjectName("sa_structure")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 643, 620))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lo_structure = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.lo_structure.setObjectName("lo_structure")
        self.sa_structure.setWidget(self.scrollAreaWidgetContents)
        self.lo_structureTab.addWidget(self.sa_structure, 0, 0, 1, 1)
        self.tw_settings.addTab(self.tab_folderStructure, "")
        self.tab_environment = QtWidgets.QWidget()
        self.tab_environment.setObjectName("tab_environment")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_environment)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_environment)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.tw_environment = QtWidgets.QTableWidget(self.tab_environment)
        self.tw_environment.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_environment.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_environment.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_environment.setObjectName("tw_environment")
        self.tw_environment.setColumnCount(2)
        self.tw_environment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_environment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_environment.setHorizontalHeaderItem(1, item)
        self.tw_environment.horizontalHeader().setStretchLastSection(True)
        self.tw_environment.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tw_environment)
        self.widget_2 = QtWidgets.QWidget(self.tab_environment)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem21 = QtWidgets.QSpacerItem(374, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem21)
        self.b_showEnvironment = QtWidgets.QPushButton(self.widget_2)
        self.b_showEnvironment.setObjectName("b_showEnvironment")
        self.horizontalLayout_2.addWidget(self.b_showEnvironment)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.tw_settings.addTab(self.tab_environment, "")
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlg_ProjectSettings)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dlg_ProjectSettings)
        self.tw_settings.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlg_ProjectSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlg_ProjectSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_ProjectSettings)

    def retranslateUi(self, dlg_ProjectSettings):
        dlg_ProjectSettings.setWindowTitle(QtWidgets.QApplication.translate("", "Project Settings", None, -1))
        self.l_curPname.setText(QtWidgets.QApplication.translate("", "Project Name:", None, -1))
        self.l_curPname_2.setText(QtWidgets.QApplication.translate("", "Project Path:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "Image:", None, -1))
        self.l_preview.setText(QtWidgets.QApplication.translate("", "Preview image", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("", "Use additional local project folder:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("", "Use master product versions:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("", "Use master media versions:", None, -1))
        self.l_backupPublishes.setText(QtWidgets.QApplication.translate("", "Backup scenefiles on publish:", None, -1))
        self.l_scenefileLocking.setText(QtWidgets.QApplication.translate("", "Enable scenefile locking:", None, -1))
        self.l_matchScenefileVersions.setText(QtWidgets.QApplication.translate("", "Match product/media version to scenefile version number:", None, -1))
        self.l_requirePublishComment.setText(QtWidgets.QApplication.translate("", "Require publish comment:", None, -1))
        self.l_publishCommentChars.setText(QtWidgets.QApplication.translate("", "Characters", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("", "Track dependencies:", None, -1))
        self.cb_dependencies.setItemText(0, QtWidgets.QApplication.translate("", "Always", None, -1))
        self.cb_dependencies.setItemText(1, QtWidgets.QApplication.translate("", "On Publish", None, -1))
        self.cb_dependencies.setItemText(2, QtWidgets.QApplication.translate("", "Never", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("", "Frames per second:", None, -1))
        self.l_prjResolution.setText(QtWidgets.QApplication.translate("", "Resolution:", None, -1))
        self.l_prjResolutionX.setText(QtWidgets.QApplication.translate("", "x", None, -1))
        self.b_reqPlugins.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.l_reqPlugins.setText(QtWidgets.QApplication.translate("", "Required Plugins:", None, -1))
        self.b_importSettings.setToolTip(QtWidgets.QApplication.translate("", "Import Project Settings...", None, -1))
        self.b_importSettings.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.b_exportSettings.setToolTip(QtWidgets.QApplication.translate("", "Export Project settings...", None, -1))
        self.b_exportSettings.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_general), QtWidgets.QApplication.translate("", "General", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("", "Asset Departments:", None, -1))
        self.tw_assetDepartments.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("", "Department", None, -1))
        self.tw_assetDepartments.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("", "Default Tasks", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("", "Shot Departments:", None, -1))
        self.tw_shotDepartments.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("", "Department", None, -1))
        self.tw_shotDepartments.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("", "Default Tasks", None, -1))
        self.chb_allowAdditionalTasks.setText(QtWidgets.QApplication.translate("", "Allow creation of additional tasks", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_departments), QtWidgets.QApplication.translate("", "Departments", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("", "Additional Export Locations:", None, -1))
        self.tw_exportPaths.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("", "Name", None, -1))
        self.tw_exportPaths.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("", "Path", None, -1))
        self.b_addExportPath.setText(QtWidgets.QApplication.translate("", "Add", None, -1))
        self.b_removeExportPath.setText(QtWidgets.QApplication.translate("", "Remove", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("", "Additional Render Locations:", None, -1))
        self.tw_renderPaths.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("", "Name", None, -1))
        self.tw_renderPaths.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("", "Path", None, -1))
        self.b_addRenderPath.setText(QtWidgets.QApplication.translate("", "Add", None, -1))
        self.b_removeRenderPath.setText(QtWidgets.QApplication.translate("", "Remove", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_locations), QtWidgets.QApplication.translate("", "Locations", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("", "WARNING: Changing the project structure after the project is created can have unexpected effects for existing data in your project.", None, -1))
        self.b_resetStructure.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_folderStructure), QtWidgets.QApplication.translate("", "Folder Structure", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("", "Project specific environment variables:", None, -1))
        self.tw_environment.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("", "Variable", None, -1))
        self.tw_environment.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("", "Value", None, -1))
        self.b_showEnvironment.setText(QtWidgets.QApplication.translate("", "Show current environment", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_environment), QtWidgets.QApplication.translate("", "Environment", None, -1))

