# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetProject.ui'
#
# Created: Wed Oct 14 11:26:37 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlg_setProject(object):
    def setupUi(self, dlg_setProject):
        dlg_setProject.setObjectName("dlg_setProject")
        dlg_setProject.resize(993, 607)
        self.verticalLayout = QtGui.QVBoxLayout(dlg_setProject)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_project = QtGui.QLabel(dlg_setProject)
        self.l_project.setMinimumSize(QtCore.QSize(0, 100))
        self.l_project.setText("")
        self.l_project.setAlignment(QtCore.Qt.AlignCenter)
        self.l_project.setObjectName("l_project")
        self.verticalLayout.addWidget(self.l_project)
        self.w_setProject = QtGui.QWidget(dlg_setProject)
        self.w_setProject.setObjectName("w_setProject")
        self.horizontalLayout = QtGui.QHBoxLayout(self.w_setProject)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(9, 15, 9, 15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_open = QtGui.QPushButton(self.w_setProject)
        self.b_open.setMinimumSize(QtCore.QSize(0, 35))
        self.b_open.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_open.setObjectName("b_open")
        self.horizontalLayout.addWidget(self.b_open)
        self.b_create = QtGui.QPushButton(self.w_setProject)
        self.b_create.setMinimumSize(QtCore.QSize(0, 35))
        self.b_create.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_create.setObjectName("b_create")
        self.horizontalLayout.addWidget(self.b_create)
        self.verticalLayout.addWidget(self.w_setProject)
        self.gb_recent = QtGui.QGroupBox(dlg_setProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.gb_recent.sizePolicy().hasHeightForWidth())
        self.gb_recent.setSizePolicy(sizePolicy)
        self.gb_recent.setMinimumSize(QtCore.QSize(0, 190))
        self.gb_recent.setObjectName("gb_recent")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_recent)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(9, 18, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sa_recent = QtGui.QScrollArea(self.gb_recent)
        self.sa_recent.setWidgetResizable(True)
        self.sa_recent.setObjectName("sa_recent")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 971, 345))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scl_recent = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scl_recent.setSpacing(6)
        self.scl_recent.setContentsMargins(0, 0, 0, 0)
        self.scl_recent.setObjectName("scl_recent")
        self.sa_recent.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.sa_recent)
        self.verticalLayout.addWidget(self.gb_recent)
        self.w_startup = QtGui.QWidget(dlg_setProject)
        self.w_startup.setObjectName("w_startup")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.w_startup)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chb_startup = QtGui.QCheckBox(self.w_startup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chb_startup.sizePolicy().hasHeightForWidth())
        self.chb_startup.setSizePolicy(sizePolicy)
        self.chb_startup.setObjectName("chb_startup")
        self.verticalLayout_3.addWidget(self.chb_startup)
        self.verticalLayout.addWidget(self.w_startup)

        self.retranslateUi(dlg_setProject)
        QtCore.QMetaObject.connectSlotsByName(dlg_setProject)

    def retranslateUi(self, dlg_setProject):
        dlg_setProject.setWindowTitle(QtGui.QApplication.translate("dlg_setProject", "Set Project", None, QtGui.QApplication.UnicodeUTF8))
        self.b_open.setText(QtGui.QApplication.translate("dlg_setProject", "Open Existing Project", None, QtGui.QApplication.UnicodeUTF8))
        self.b_create.setText(QtGui.QApplication.translate("dlg_setProject", "Create New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_recent.setTitle(QtGui.QApplication.translate("dlg_setProject", "Recent projects:", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_startup.setText(QtGui.QApplication.translate("dlg_setProject", "Open on startup", None, QtGui.QApplication.UnicodeUTF8))

