# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hou_Dependency.ui'
#
# Created: Tue Mar  7 11:17:56 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_wg_Dependency(object):
    def setupUi(self, wg_Dependency):
        wg_Dependency.setObjectName("wg_Dependency")
        wg_Dependency.resize(340, 643)
        self.verticalLayout = QtWidgets.QVBoxLayout(wg_Dependency)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(wg_Dependency)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 18, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_name = QtWidgets.QLabel(self.widget_4)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_2.addWidget(self.l_name)
        self.e_name = QtWidgets.QLineEdit(self.widget_4)
        self.e_name.setObjectName("e_name")
        self.horizontalLayout_2.addWidget(self.e_name)
        self.l_class = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.l_class.setFont(font)
        self.l_class.setObjectName("l_class")
        self.horizontalLayout_2.addWidget(self.l_class)
        self.verticalLayout.addWidget(self.widget_4)
        self.f_manager = QtWidgets.QWidget(wg_Dependency)
        self.f_manager.setObjectName("f_manager")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.f_manager)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_manager = QtWidgets.QLabel(self.f_manager)
        self.l_manager.setObjectName("l_manager")
        self.horizontalLayout_8.addWidget(self.l_manager)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.cb_manager = QtWidgets.QComboBox(self.f_manager)
        self.cb_manager.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_manager.setObjectName("cb_manager")
        self.horizontalLayout_8.addWidget(self.cb_manager)
        self.verticalLayout.addWidget(self.f_manager)
        self.gb_dlDependency = QtWidgets.QGroupBox(wg_Dependency)
        self.gb_dlDependency.setObjectName("gb_dlDependency")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_dlDependency)
        self.verticalLayout_2.setContentsMargins(-1, 18, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_clear = QtWidgets.QWidget(self.gb_dlDependency)
        self.w_clear.setObjectName("w_clear")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.w_clear)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.l_clear = QtWidgets.QLabel(self.w_clear)
        self.l_clear.setObjectName("l_clear")
        self.horizontalLayout_4.addWidget(self.l_clear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.chb_clear = QtWidgets.QCheckBox(self.w_clear)
        self.chb_clear.setText("")
        self.chb_clear.setChecked(True)
        self.chb_clear.setObjectName("chb_clear")
        self.horizontalLayout_4.addWidget(self.chb_clear)
        self.verticalLayout_2.addWidget(self.w_clear)
        self.widget_5 = QtWidgets.QWidget(self.gb_dlDependency)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cb_depType = QtWidgets.QComboBox(self.widget_5)
        self.cb_depType.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_depType.setObjectName("cb_depType")
        self.horizontalLayout_3.addWidget(self.cb_depType)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.w_offset = QtWidgets.QWidget(self.gb_dlDependency)
        self.w_offset.setObjectName("w_offset")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.w_offset)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.w_offset)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sp_offset = QtWidgets.QSpinBox(self.w_offset)
        self.sp_offset.setSuffix("")
        self.sp_offset.setMinimum(-99999)
        self.sp_offset.setMaximum(99999)
        self.sp_offset.setObjectName("sp_offset")
        self.horizontalLayout.addWidget(self.sp_offset)
        self.verticalLayout_2.addWidget(self.w_offset)
        self.widget = QtWidgets.QWidget(self.gb_dlDependency)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tw_caches = QtWidgets.QTreeWidget(self.widget)
        self.tw_caches.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_caches.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw_caches.setItemsExpandable(True)
        self.tw_caches.setExpandsOnDoubleClick(True)
        self.tw_caches.setObjectName("tw_caches")
        self.tw_caches.headerItem().setText(0, "1")
        self.tw_caches.header().setVisible(True)
        self.verticalLayout_3.addWidget(self.tw_caches)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.gb_dlDependency)

        self.retranslateUi(wg_Dependency)
        QtCore.QMetaObject.connectSlotsByName(wg_Dependency)

    def retranslateUi(self, wg_Dependency):
        wg_Dependency.setWindowTitle(QtWidgets.QApplication.translate("", "Dependency", None, -1))
        self.l_name.setText(QtWidgets.QApplication.translate("", "Name:", None, -1))
        self.l_class.setText(QtWidgets.QApplication.translate("", "Dependency", None, -1))
        self.l_manager.setText(QtWidgets.QApplication.translate("", "Manager:", None, -1))
        self.gb_dlDependency.setTitle(QtWidgets.QApplication.translate("", " Dependency", None, -1))
        self.l_clear.setText(QtWidgets.QApplication.translate("", "Clear all existing dependencies:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("", "Release when:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "Start when next n frames exist", None, -1))

