# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hou_ImageRender.ui',
# licensing of 'hou_ImageRender.ui' applies.
#
# Created: Sat Jul 25 22:32:09 2020
#      by: pyside2-uic  running on PySide2 5.9.0a1.dev1528389443
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_wg_ImageRender(object):
    def setupUi(self, wg_ImageRender):
        wg_ImageRender.setObjectName("wg_ImageRender")
        wg_ImageRender.resize(340, 1206)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wg_ImageRender.sizePolicy().hasHeightForWidth())
        wg_ImageRender.setSizePolicy(sizePolicy)
        wg_ImageRender.setMinimumSize(QtCore.QSize(340, 0))
        wg_ImageRender.setMaximumSize(QtCore.QSize(340, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(wg_ImageRender)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(wg_ImageRender)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 18, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.l_name = QtWidgets.QLabel(self.widget_4)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_4.addWidget(self.l_name)
        self.e_name = QtWidgets.QLineEdit(self.widget_4)
        self.e_name.setObjectName("e_name")
        self.horizontalLayout_4.addWidget(self.e_name)
        self.l_class = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.l_class.setFont(font)
        self.l_class.setObjectName("l_class")
        self.horizontalLayout_4.addWidget(self.l_class)
        self.verticalLayout.addWidget(self.widget_4)
        self.groupBox = QtWidgets.QGroupBox(wg_ImageRender)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_10 = QtWidgets.QWidget(self.groupBox)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.widget_10)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.l_taskName = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_taskName.sizePolicy().hasHeightForWidth())
        self.l_taskName.setSizePolicy(sizePolicy)
        self.l_taskName.setText("")
        self.l_taskName.setAlignment(QtCore.Qt.AlignCenter)
        self.l_taskName.setObjectName("l_taskName")
        self.horizontalLayout_10.addWidget(self.l_taskName)
        self.b_changeTask = QtWidgets.QPushButton(self.widget_10)
        self.b_changeTask.setEnabled(True)
        self.b_changeTask.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_changeTask.setObjectName("b_changeTask")
        self.horizontalLayout_10.addWidget(self.b_changeTask)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb_rangeType = QtWidgets.QComboBox(self.widget_2)
        self.cb_rangeType.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_rangeType.setObjectName("cb_rangeType")
        self.horizontalLayout.addWidget(self.cb_rangeType)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.w_frameRangeValues = QtWidgets.QWidget(self.groupBox)
        self.w_frameRangeValues.setObjectName("w_frameRangeValues")
        self.gridLayout = QtWidgets.QGridLayout(self.w_frameRangeValues)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l_rangeEnd = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeEnd.setMinimumSize(QtCore.QSize(30, 0))
        self.l_rangeEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_rangeEnd.setObjectName("l_rangeEnd")
        self.gridLayout.addWidget(self.l_rangeEnd, 1, 5, 1, 1)
        self.sp_rangeEnd = QtWidgets.QSpinBox(self.w_frameRangeValues)
        self.sp_rangeEnd.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sp_rangeEnd.setMaximum(99999)
        self.sp_rangeEnd.setProperty("value", 1100)
        self.sp_rangeEnd.setObjectName("sp_rangeEnd")
        self.gridLayout.addWidget(self.sp_rangeEnd, 1, 6, 1, 1)
        self.sp_rangeStart = QtWidgets.QSpinBox(self.w_frameRangeValues)
        self.sp_rangeStart.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sp_rangeStart.setMaximum(99999)
        self.sp_rangeStart.setProperty("value", 1001)
        self.sp_rangeStart.setObjectName("sp_rangeStart")
        self.gridLayout.addWidget(self.sp_rangeStart, 0, 6, 1, 1)
        self.l_rangeStart = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeStart.setMinimumSize(QtCore.QSize(30, 0))
        self.l_rangeStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_rangeStart.setObjectName("l_rangeStart")
        self.gridLayout.addWidget(self.l_rangeStart, 0, 5, 1, 1)
        self.l_rangeStartInfo = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeStartInfo.setObjectName("l_rangeStartInfo")
        self.gridLayout.addWidget(self.l_rangeStartInfo, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.l_rangeEndInfo = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeEndInfo.setObjectName("l_rangeEndInfo")
        self.gridLayout.addWidget(self.l_rangeEndInfo, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.w_frameRangeValues)
        self.w_frameExpression = QtWidgets.QWidget(self.groupBox)
        self.w_frameExpression.setObjectName("w_frameExpression")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.w_frameExpression)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.l_frameExpression = QtWidgets.QLabel(self.w_frameExpression)
        self.l_frameExpression.setObjectName("l_frameExpression")
        self.horizontalLayout_17.addWidget(self.l_frameExpression)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.le_frameExpression = QtWidgets.QLineEdit(self.w_frameExpression)
        self.le_frameExpression.setMinimumSize(QtCore.QSize(150, 0))
        self.le_frameExpression.setObjectName("le_frameExpression")
        self.horizontalLayout_17.addWidget(self.le_frameExpression)
        self.verticalLayout_2.addWidget(self.w_frameExpression)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.chb_camOverride = QtWidgets.QCheckBox(self.widget)
        self.chb_camOverride.setText("")
        self.chb_camOverride.setObjectName("chb_camOverride")
        self.horizontalLayout_2.addWidget(self.chb_camOverride)
        self.cb_cams = QtWidgets.QComboBox(self.widget)
        self.cb_cams.setEnabled(False)
        self.cb_cams.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_cams.setObjectName("cb_cams")
        self.horizontalLayout_2.addWidget(self.cb_cams)
        self.verticalLayout_2.addWidget(self.widget)
        self.f_resolution = QtWidgets.QWidget(self.groupBox)
        self.f_resolution.setObjectName("f_resolution")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.f_resolution)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.f_resolution)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.chb_resOverride = QtWidgets.QCheckBox(self.f_resolution)
        self.chb_resOverride.setText("")
        self.chb_resOverride.setObjectName("chb_resOverride")
        self.horizontalLayout_9.addWidget(self.chb_resOverride)
        self.sp_resWidth = QtWidgets.QSpinBox(self.f_resolution)
        self.sp_resWidth.setEnabled(False)
        self.sp_resWidth.setMinimum(1)
        self.sp_resWidth.setMaximum(99999)
        self.sp_resWidth.setProperty("value", 1280)
        self.sp_resWidth.setObjectName("sp_resWidth")
        self.horizontalLayout_9.addWidget(self.sp_resWidth)
        self.sp_resHeight = QtWidgets.QSpinBox(self.f_resolution)
        self.sp_resHeight.setEnabled(False)
        self.sp_resHeight.setMinimum(1)
        self.sp_resHeight.setMaximum(99999)
        self.sp_resHeight.setProperty("value", 720)
        self.sp_resHeight.setObjectName("sp_resHeight")
        self.horizontalLayout_9.addWidget(self.sp_resHeight)
        self.b_resPresets = QtWidgets.QPushButton(self.f_resolution)
        self.b_resPresets.setEnabled(False)
        self.b_resPresets.setMinimumSize(QtCore.QSize(23, 23))
        self.b_resPresets.setMaximumSize(QtCore.QSize(23, 23))
        self.b_resPresets.setObjectName("b_resPresets")
        self.horizontalLayout_9.addWidget(self.b_resPresets)
        self.verticalLayout_2.addWidget(self.f_resolution)
        self.widget_7 = QtWidgets.QWidget(self.groupBox)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.chb_useTake = QtWidgets.QCheckBox(self.widget_7)
        self.chb_useTake.setText("")
        self.chb_useTake.setObjectName("chb_useTake")
        self.horizontalLayout_11.addWidget(self.chb_useTake)
        self.cb_take = QtWidgets.QComboBox(self.widget_7)
        self.cb_take.setEnabled(False)
        self.cb_take.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_take.setObjectName("cb_take")
        self.horizontalLayout_11.addWidget(self.cb_take)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.w_renderPreset = QtWidgets.QWidget(self.groupBox)
        self.w_renderPreset.setObjectName("w_renderPreset")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.w_renderPreset)
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_renderPreset = QtWidgets.QLabel(self.w_renderPreset)
        self.l_renderPreset.setObjectName("l_renderPreset")
        self.horizontalLayout_12.addWidget(self.l_renderPreset)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.chb_renderPreset = QtWidgets.QCheckBox(self.w_renderPreset)
        self.chb_renderPreset.setText("")
        self.chb_renderPreset.setObjectName("chb_renderPreset")
        self.horizontalLayout_12.addWidget(self.chb_renderPreset)
        self.cb_renderPreset = QtWidgets.QComboBox(self.w_renderPreset)
        self.cb_renderPreset.setEnabled(False)
        self.cb_renderPreset.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_renderPreset.setObjectName("cb_renderPreset")
        self.horizontalLayout_12.addWidget(self.cb_renderPreset)
        self.verticalLayout_2.addWidget(self.w_renderPreset)
        self.f_localOutput = QtWidgets.QWidget(self.groupBox)
        self.f_localOutput.setObjectName("f_localOutput")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.f_localOutput)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.l_localOutput = QtWidgets.QLabel(self.f_localOutput)
        self.l_localOutput.setObjectName("l_localOutput")
        self.horizontalLayout_16.addWidget(self.l_localOutput)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.chb_localOutput = QtWidgets.QCheckBox(self.f_localOutput)
        self.chb_localOutput.setText("")
        self.chb_localOutput.setObjectName("chb_localOutput")
        self.horizontalLayout_16.addWidget(self.chb_localOutput)
        self.verticalLayout_2.addWidget(self.f_localOutput)
        self.w_format = QtWidgets.QWidget(self.groupBox)
        self.w_format.setObjectName("w_format")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.w_format)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.w_format)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.cb_format = QtWidgets.QComboBox(self.w_format)
        self.cb_format.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_format.setObjectName("cb_format")
        self.horizontalLayout_13.addWidget(self.cb_format)
        self.verticalLayout_2.addWidget(self.w_format)
        self.f_renderer = QtWidgets.QWidget(self.groupBox)
        self.f_renderer.setObjectName("f_renderer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.f_renderer)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.f_renderer)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.cb_renderer = QtWidgets.QComboBox(self.f_renderer)
        self.cb_renderer.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_renderer.setObjectName("cb_renderer")
        self.horizontalLayout_3.addWidget(self.cb_renderer)
        self.verticalLayout_2.addWidget(self.f_renderer)
        self.f_status = QtWidgets.QWidget(self.groupBox)
        self.f_status.setObjectName("f_status")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.f_status)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.f_status)
        self.label_5.setMinimumSize(QtCore.QSize(40, 0))
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.l_status = QtWidgets.QLabel(self.f_status)
        self.l_status.setAlignment(QtCore.Qt.AlignCenter)
        self.l_status.setObjectName("l_status")
        self.horizontalLayout_5.addWidget(self.l_status)
        self.b_goTo = QtWidgets.QPushButton(self.f_status)
        self.b_goTo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_goTo.setObjectName("b_goTo")
        self.horizontalLayout_5.addWidget(self.b_goTo)
        self.verticalLayout_2.addWidget(self.f_status)
        self.f_connect = QtWidgets.QWidget(self.groupBox)
        self.f_connect.setObjectName("f_connect")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.f_connect)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.b_connect = QtWidgets.QPushButton(self.f_connect)
        self.b_connect.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_connect.setObjectName("b_connect")
        self.horizontalLayout_6.addWidget(self.b_connect)
        self.verticalLayout_2.addWidget(self.f_connect)
        self.verticalLayout.addWidget(self.groupBox)
        self.gb_submit = QtWidgets.QGroupBox(wg_ImageRender)
        self.gb_submit.setCheckable(True)
        self.gb_submit.setChecked(True)
        self.gb_submit.setObjectName("gb_submit")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gb_submit)
        self.verticalLayout_7.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.f_manager = QtWidgets.QWidget(self.gb_submit)
        self.f_manager.setObjectName("f_manager")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.f_manager)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_manager = QtWidgets.QLabel(self.f_manager)
        self.l_manager.setObjectName("l_manager")
        self.horizontalLayout_8.addWidget(self.l_manager)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.cb_manager = QtWidgets.QComboBox(self.f_manager)
        self.cb_manager.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_manager.setObjectName("cb_manager")
        self.horizontalLayout_8.addWidget(self.cb_manager)
        self.verticalLayout_7.addWidget(self.f_manager)
        self.f_rjPrio = QtWidgets.QWidget(self.gb_submit)
        self.f_rjPrio.setObjectName("f_rjPrio")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.f_rjPrio)
        self.horizontalLayout_21.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.l_rjPrio = QtWidgets.QLabel(self.f_rjPrio)
        self.l_rjPrio.setObjectName("l_rjPrio")
        self.horizontalLayout_21.addWidget(self.l_rjPrio)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem11)
        self.sp_rjPrio = QtWidgets.QSpinBox(self.f_rjPrio)
        self.sp_rjPrio.setMaximum(100)
        self.sp_rjPrio.setProperty("value", 50)
        self.sp_rjPrio.setObjectName("sp_rjPrio")
        self.horizontalLayout_21.addWidget(self.sp_rjPrio)
        self.verticalLayout_7.addWidget(self.f_rjPrio)
        self.f_rjWidgetsPerTask = QtWidgets.QWidget(self.gb_submit)
        self.f_rjWidgetsPerTask.setObjectName("f_rjWidgetsPerTask")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.f_rjWidgetsPerTask)
        self.horizontalLayout_22.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.f_rjWidgetsPerTask)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem12)
        self.sp_rjFramesPerTask = QtWidgets.QSpinBox(self.f_rjWidgetsPerTask)
        self.sp_rjFramesPerTask.setMaximum(9999)
        self.sp_rjFramesPerTask.setProperty("value", 5)
        self.sp_rjFramesPerTask.setObjectName("sp_rjFramesPerTask")
        self.horizontalLayout_22.addWidget(self.sp_rjFramesPerTask)
        self.verticalLayout_7.addWidget(self.f_rjWidgetsPerTask)
        self.f_rjTimeout = QtWidgets.QWidget(self.gb_submit)
        self.f_rjTimeout.setObjectName("f_rjTimeout")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.f_rjTimeout)
        self.horizontalLayout_28.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.l_rjTimeout = QtWidgets.QLabel(self.f_rjTimeout)
        self.l_rjTimeout.setObjectName("l_rjTimeout")
        self.horizontalLayout_28.addWidget(self.l_rjTimeout)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem13)
        self.sp_rjTimeout = QtWidgets.QSpinBox(self.f_rjTimeout)
        self.sp_rjTimeout.setMinimum(1)
        self.sp_rjTimeout.setMaximum(9999)
        self.sp_rjTimeout.setProperty("value", 180)
        self.sp_rjTimeout.setObjectName("sp_rjTimeout")
        self.horizontalLayout_28.addWidget(self.sp_rjTimeout)
        self.verticalLayout_7.addWidget(self.f_rjTimeout)
        self.f_rjSuspended = QtWidgets.QWidget(self.gb_submit)
        self.f_rjSuspended.setObjectName("f_rjSuspended")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.f_rjSuspended)
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_18 = QtWidgets.QLabel(self.f_rjSuspended)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_26.addWidget(self.label_18)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem14)
        self.chb_rjSuspended = QtWidgets.QCheckBox(self.f_rjSuspended)
        self.chb_rjSuspended.setText("")
        self.chb_rjSuspended.setChecked(False)
        self.chb_rjSuspended.setObjectName("chb_rjSuspended")
        self.horizontalLayout_26.addWidget(self.chb_rjSuspended)
        self.verticalLayout_7.addWidget(self.f_rjSuspended)
        self.w_renderNSIs = QtWidgets.QWidget(self.gb_submit)
        self.w_renderNSIs.setObjectName("w_renderNSIs")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.w_renderNSIs)
        self.horizontalLayout_32.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_20 = QtWidgets.QLabel(self.w_renderNSIs)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_32.addWidget(self.label_20)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem15)
        self.chb_rjNSIs = QtWidgets.QCheckBox(self.w_renderNSIs)
        self.chb_rjNSIs.setText("")
        self.chb_rjNSIs.setChecked(True)
        self.chb_rjNSIs.setObjectName("chb_rjNSIs")
        self.horizontalLayout_32.addWidget(self.chb_rjNSIs)
        self.verticalLayout_7.addWidget(self.w_renderNSIs)
        self.f_osDependencies = QtWidgets.QWidget(self.gb_submit)
        self.f_osDependencies.setObjectName("f_osDependencies")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.f_osDependencies)
        self.horizontalLayout_27.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.f_osDependencies)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem16)
        self.chb_osDependencies = QtWidgets.QCheckBox(self.f_osDependencies)
        self.chb_osDependencies.setText("")
        self.chb_osDependencies.setChecked(True)
        self.chb_osDependencies.setObjectName("chb_osDependencies")
        self.horizontalLayout_27.addWidget(self.chb_osDependencies)
        self.verticalLayout_7.addWidget(self.f_osDependencies)
        self.f_osUpload = QtWidgets.QWidget(self.gb_submit)
        self.f_osUpload.setObjectName("f_osUpload")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.f_osUpload)
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_16 = QtWidgets.QLabel(self.f_osUpload)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_23.addWidget(self.label_16)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.chb_osUpload = QtWidgets.QCheckBox(self.f_osUpload)
        self.chb_osUpload.setText("")
        self.chb_osUpload.setChecked(True)
        self.chb_osUpload.setObjectName("chb_osUpload")
        self.horizontalLayout_23.addWidget(self.chb_osUpload)
        self.verticalLayout_7.addWidget(self.f_osUpload)
        self.f_osPAssets = QtWidgets.QWidget(self.gb_submit)
        self.f_osPAssets.setObjectName("f_osPAssets")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.f_osPAssets)
        self.horizontalLayout_24.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_17 = QtWidgets.QLabel(self.f_osPAssets)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_24.addWidget(self.label_17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem18)
        self.chb_osPAssets = QtWidgets.QCheckBox(self.f_osPAssets)
        self.chb_osPAssets.setText("")
        self.chb_osPAssets.setChecked(True)
        self.chb_osPAssets.setObjectName("chb_osPAssets")
        self.horizontalLayout_24.addWidget(self.chb_osPAssets)
        self.verticalLayout_7.addWidget(self.f_osPAssets)
        self.gb_osSlaves = QtWidgets.QGroupBox(self.gb_submit)
        self.gb_osSlaves.setObjectName("gb_osSlaves")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.gb_osSlaves)
        self.horizontalLayout_25.setContentsMargins(9, 3, 9, 3)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.e_osSlaves = QtWidgets.QLineEdit(self.gb_osSlaves)
        self.e_osSlaves.setObjectName("e_osSlaves")
        self.horizontalLayout_25.addWidget(self.e_osSlaves)
        self.b_osSlaves = QtWidgets.QPushButton(self.gb_osSlaves)
        self.b_osSlaves.setMaximumSize(QtCore.QSize(25, 16777215))
        self.b_osSlaves.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_osSlaves.setObjectName("b_osSlaves")
        self.horizontalLayout_25.addWidget(self.b_osSlaves)
        self.verticalLayout_7.addWidget(self.gb_osSlaves)
        self.f_dlGroup = QtWidgets.QWidget(self.gb_submit)
        self.f_dlGroup.setObjectName("f_dlGroup")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.f_dlGroup)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.f_dlGroup)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.cb_dlGroup = QtWidgets.QComboBox(self.f_dlGroup)
        self.cb_dlGroup.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_dlGroup.setObjectName("cb_dlGroup")
        self.horizontalLayout_7.addWidget(self.cb_dlGroup)
        self.verticalLayout_7.addWidget(self.f_dlGroup)
        self.w_dlConcurrentTasks = QtWidgets.QWidget(self.gb_submit)
        self.w_dlConcurrentTasks.setObjectName("w_dlConcurrentTasks")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.w_dlConcurrentTasks)
        self.horizontalLayout_29.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.l_dlConcurrentTasks = QtWidgets.QLabel(self.w_dlConcurrentTasks)
        self.l_dlConcurrentTasks.setObjectName("l_dlConcurrentTasks")
        self.horizontalLayout_29.addWidget(self.l_dlConcurrentTasks)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem20)
        self.sp_dlConcurrentTasks = QtWidgets.QSpinBox(self.w_dlConcurrentTasks)
        self.sp_dlConcurrentTasks.setMinimum(1)
        self.sp_dlConcurrentTasks.setMaximum(99)
        self.sp_dlConcurrentTasks.setProperty("value", 1)
        self.sp_dlConcurrentTasks.setObjectName("sp_dlConcurrentTasks")
        self.horizontalLayout_29.addWidget(self.sp_dlConcurrentTasks)
        self.verticalLayout_7.addWidget(self.w_dlConcurrentTasks)
        self.w_dlGPUpt = QtWidgets.QWidget(self.gb_submit)
        self.w_dlGPUpt.setObjectName("w_dlGPUpt")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.w_dlGPUpt)
        self.horizontalLayout_30.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.l_dlGPUpt = QtWidgets.QLabel(self.w_dlGPUpt)
        self.l_dlGPUpt.setObjectName("l_dlGPUpt")
        self.horizontalLayout_30.addWidget(self.l_dlGPUpt)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem21)
        self.sp_dlGPUpt = QtWidgets.QSpinBox(self.w_dlGPUpt)
        self.sp_dlGPUpt.setMinimum(0)
        self.sp_dlGPUpt.setMaximum(99)
        self.sp_dlGPUpt.setProperty("value", 0)
        self.sp_dlGPUpt.setObjectName("sp_dlGPUpt")
        self.horizontalLayout_30.addWidget(self.sp_dlGPUpt)
        self.verticalLayout_7.addWidget(self.w_dlGPUpt)
        self.w_dlGPUdevices = QtWidgets.QWidget(self.gb_submit)
        self.w_dlGPUdevices.setObjectName("w_dlGPUdevices")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.w_dlGPUdevices)
        self.horizontalLayout_31.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.l_dlGPUdevices = QtWidgets.QLabel(self.w_dlGPUdevices)
        self.l_dlGPUdevices.setObjectName("l_dlGPUdevices")
        self.horizontalLayout_31.addWidget(self.l_dlGPUdevices)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem22)
        self.le_dlGPUdevices = QtWidgets.QLineEdit(self.w_dlGPUdevices)
        self.le_dlGPUdevices.setMinimumSize(QtCore.QSize(170, 0))
        self.le_dlGPUdevices.setObjectName("le_dlGPUdevices")
        self.horizontalLayout_31.addWidget(self.le_dlGPUdevices)
        self.verticalLayout_7.addWidget(self.w_dlGPUdevices)
        self.verticalLayout.addWidget(self.gb_submit)
        self.gb_passes = QtWidgets.QGroupBox(wg_ImageRender)
        self.gb_passes.setObjectName("gb_passes")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_passes)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_14 = QtWidgets.QWidget(self.gb_passes)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_14.setContentsMargins(-1, 9, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tw_passes = QtWidgets.QTableWidget(self.widget_14)
        self.tw_passes.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tw_passes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_passes.setObjectName("tw_passes")
        self.tw_passes.setColumnCount(2)
        self.tw_passes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_passes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_passes.setHorizontalHeaderItem(1, item)
        self.tw_passes.horizontalHeader().setVisible(True)
        self.tw_passes.horizontalHeader().setHighlightSections(False)
        self.tw_passes.horizontalHeader().setStretchLastSection(True)
        self.tw_passes.verticalHeader().setVisible(False)
        self.horizontalLayout_14.addWidget(self.tw_passes)
        self.verticalLayout_5.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.gb_passes)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.b_addPasses = QtWidgets.QPushButton(self.widget_15)
        self.b_addPasses.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addPasses.setObjectName("b_addPasses")
        self.horizontalLayout_15.addWidget(self.b_addPasses)
        self.verticalLayout_5.addWidget(self.widget_15)
        self.verticalLayout.addWidget(self.gb_passes)
        self.groupBox_3 = QtWidgets.QGroupBox(wg_ImageRender)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(18, -1, 18, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_pathLast = QtWidgets.QLabel(self.groupBox_3)
        self.l_pathLast.setObjectName("l_pathLast")
        self.verticalLayout_4.addWidget(self.l_pathLast)
        self.widget_21 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.b_openLast = QtWidgets.QPushButton(self.widget_21)
        self.b_openLast.setEnabled(False)
        self.b_openLast.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_openLast.setObjectName("b_openLast")
        self.horizontalLayout_19.addWidget(self.b_openLast)
        self.b_copyLast = QtWidgets.QPushButton(self.widget_21)
        self.b_copyLast.setEnabled(False)
        self.b_copyLast.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_copyLast.setObjectName("b_copyLast")
        self.horizontalLayout_19.addWidget(self.b_copyLast)
        self.verticalLayout_4.addWidget(self.widget_21)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(wg_ImageRender)
        QtCore.QMetaObject.connectSlotsByName(wg_ImageRender)

    def retranslateUi(self, wg_ImageRender):
        wg_ImageRender.setWindowTitle(QtWidgets.QApplication.translate("wg_ImageRender", "Image Render", None, -1))
        self.l_name.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Name:", None, -1))
        self.l_class.setText(QtWidgets.QApplication.translate("wg_ImageRender", "ImageRender", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("wg_ImageRender", "General", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Taskname:", None, -1))
        self.b_changeTask.setText(QtWidgets.QApplication.translate("wg_ImageRender", "change", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Framerange:", None, -1))
        self.l_rangeEnd.setText(QtWidgets.QApplication.translate("wg_ImageRender", "1100", None, -1))
        self.l_rangeStart.setText(QtWidgets.QApplication.translate("wg_ImageRender", "1001", None, -1))
        self.l_rangeStartInfo.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Start:", None, -1))
        self.l_rangeEndInfo.setText(QtWidgets.QApplication.translate("wg_ImageRender", "End:", None, -1))
        self.l_frameExpression.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Frame expression:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Camera override:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Resolution override:", None, -1))
        self.b_resPresets.setText(QtWidgets.QApplication.translate("wg_ImageRender", "▼", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Override take:", None, -1))
        self.l_renderPreset.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Rendersettings preset:", None, -1))
        self.l_localOutput.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Local output:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Format:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Renderer:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Status:", None, -1))
        self.l_status.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Not connected", None, -1))
        self.b_goTo.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Go to Node", None, -1))
        self.b_connect.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Connect to selected ROP", None, -1))
        self.gb_submit.setTitle(QtWidgets.QApplication.translate("wg_ImageRender", "Submit Render Job", None, -1))
        self.l_manager.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Manager:", None, -1))
        self.l_rjPrio.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Priority:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Frames per Task:", None, -1))
        self.l_rjTimeout.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Task Timeout (min)", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Submit suspended:", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Render NSIs:", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Submit dependent files:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Upload output:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Use Project Assets", None, -1))
        self.gb_osSlaves.setTitle(QtWidgets.QApplication.translate("wg_ImageRender", "Assign to slaves:", None, -1))
        self.b_osSlaves.setText(QtWidgets.QApplication.translate("wg_ImageRender", "...", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Assign to group:", None, -1))
        self.l_dlConcurrentTasks.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Concurrent Tasks:", None, -1))
        self.l_dlGPUpt.setText(QtWidgets.QApplication.translate("wg_ImageRender", "GPUs Per Task:", None, -1))
        self.l_dlGPUdevices.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Select GPU Devices:", None, -1))
        self.le_dlGPUdevices.setPlaceholderText(QtWidgets.QApplication.translate("wg_ImageRender", "Enter Valid GPU Device Id(s)", None, -1))
        self.gb_passes.setTitle(QtWidgets.QApplication.translate("wg_ImageRender", "Render Passes", None, -1))
        self.tw_passes.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("wg_ImageRender", "Name", None, -1))
        self.tw_passes.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("wg_ImageRender", "VEX Variable", None, -1))
        self.b_addPasses.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Add Passes", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("wg_ImageRender", "Last render", None, -1))
        self.l_pathLast.setText(QtWidgets.QApplication.translate("wg_ImageRender", "None", None, -1))
        self.b_openLast.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Open in explorer", None, -1))
        self.b_copyLast.setText(QtWidgets.QApplication.translate("wg_ImageRender", "Copy path to clipboard", None, -1))

