# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'default_ImportFile.ui'
#
# Created: Sun Dec 15 19:03:30 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_wg_ImportFile(object):
    def setupUi(self, wg_ImportFile):
        wg_ImportFile.setObjectName("wg_ImportFile")
        wg_ImportFile.resize(340, 706)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wg_ImportFile.sizePolicy().hasHeightForWidth())
        wg_ImportFile.setSizePolicy(sizePolicy)
        wg_ImportFile.setMinimumSize(QtCore.QSize(340, 0))
        wg_ImportFile.setMaximumSize(QtCore.QSize(340, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(wg_ImportFile)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_name = QtGui.QWidget(wg_ImportFile)
        self.f_name.setObjectName("f_name")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.f_name)
        self.horizontalLayout_2.setContentsMargins(9, 0, 18, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_name = QtGui.QLabel(self.f_name)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_2.addWidget(self.l_name)
        self.e_name = QtGui.QLineEdit(self.f_name)
        self.e_name.setMinimumSize(QtCore.QSize(0, 0))
        self.e_name.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.e_name.setObjectName("e_name")
        self.horizontalLayout_2.addWidget(self.e_name)
        self.l_class = QtGui.QLabel(self.f_name)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.l_class.setFont(font)
        self.l_class.setObjectName("l_class")
        self.horizontalLayout_2.addWidget(self.l_class)
        self.verticalLayout.addWidget(self.f_name)
        self.gb_import = QtGui.QGroupBox(wg_ImportFile)
        self.gb_import.setObjectName("gb_import")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_import)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.f_importPath = QtGui.QWidget(self.gb_import)
        self.f_importPath.setObjectName("f_importPath")
        self.horizontalLayout = QtGui.QHBoxLayout(self.f_importPath)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_file = QtGui.QLabel(self.f_importPath)
        self.l_file.setObjectName("l_file")
        self.horizontalLayout.addWidget(self.l_file)
        self.e_file = QtGui.QLineEdit(self.f_importPath)
        self.e_file.setReadOnly(False)
        self.e_file.setObjectName("e_file")
        self.horizontalLayout.addWidget(self.e_file)
        self.b_browse = QtGui.QPushButton(self.f_importPath)
        self.b_browse.setMinimumSize(QtCore.QSize(22, 0))
        self.b_browse.setMaximumSize(QtCore.QSize(22, 16777215))
        self.b_browse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browse.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browse.setObjectName("b_browse")
        self.horizontalLayout.addWidget(self.b_browse)
        self.verticalLayout_2.addWidget(self.f_importPath)
        self.f_importButton = QtGui.QWidget(self.gb_import)
        self.f_importButton.setObjectName("f_importButton")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.f_importButton)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_import = QtGui.QPushButton(self.f_importButton)
        self.b_import.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_import.setObjectName("b_import")
        self.horizontalLayout_3.addWidget(self.b_import)
        self.verticalLayout_2.addWidget(self.f_importButton)
        self.groupBox = QtGui.QGroupBox(self.gb_import)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.w_currentVersion = QtGui.QWidget(self.groupBox)
        self.w_currentVersion.setObjectName("w_currentVersion")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.w_currentVersion)
        self.horizontalLayout_5.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(self.w_currentVersion)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.l_curVersion = QtGui.QLabel(self.w_currentVersion)
        self.l_curVersion.setObjectName("l_curVersion")
        self.horizontalLayout_5.addWidget(self.l_curVersion)
        self.verticalLayout_3.addWidget(self.w_currentVersion)
        self.w_autoUpdate = QtGui.QWidget(self.groupBox)
        self.w_autoUpdate.setObjectName("w_autoUpdate")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.w_autoUpdate)
        self.horizontalLayout_14.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.l_autoUpdate = QtGui.QLabel(self.w_autoUpdate)
        self.l_autoUpdate.setObjectName("l_autoUpdate")
        self.horizontalLayout_14.addWidget(self.l_autoUpdate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.chb_autoUpdate = QtGui.QCheckBox(self.w_autoUpdate)
        self.chb_autoUpdate.setText("")
        self.chb_autoUpdate.setChecked(False)
        self.chb_autoUpdate.setObjectName("chb_autoUpdate")
        self.horizontalLayout_14.addWidget(self.chb_autoUpdate)
        self.verticalLayout_3.addWidget(self.w_autoUpdate)
        self.w_latestVersion = QtGui.QWidget(self.groupBox)
        self.w_latestVersion.setObjectName("w_latestVersion")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.w_latestVersion)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.w_latestVersion)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.l_latestVersion = QtGui.QLabel(self.w_latestVersion)
        self.l_latestVersion.setObjectName("l_latestVersion")
        self.horizontalLayout_6.addWidget(self.l_latestVersion)
        self.verticalLayout_3.addWidget(self.w_latestVersion)
        self.w_importLatest = QtGui.QWidget(self.groupBox)
        self.w_importLatest.setObjectName("w_importLatest")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.w_importLatest)
        self.horizontalLayout_7.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.b_importLatest = QtGui.QPushButton(self.w_importLatest)
        self.b_importLatest.setMinimumSize(QtCore.QSize(0, 0))
        self.b_importLatest.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.b_importLatest.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_importLatest.setObjectName("b_importLatest")
        self.horizontalLayout_7.addWidget(self.b_importLatest)
        self.verticalLayout_3.addWidget(self.w_importLatest)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gb_options = QtGui.QGroupBox(self.gb_import)
        self.gb_options.setObjectName("gb_options")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gb_options)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.f_keepRefEdits = QtGui.QWidget(self.gb_options)
        self.f_keepRefEdits.setObjectName("f_keepRefEdits")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.f_keepRefEdits)
        self.horizontalLayout_10.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.l_keepRefEdits = QtGui.QLabel(self.f_keepRefEdits)
        self.l_keepRefEdits.setObjectName("l_keepRefEdits")
        self.horizontalLayout_10.addWidget(self.l_keepRefEdits)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.chb_keepRefEdits = QtGui.QCheckBox(self.f_keepRefEdits)
        self.chb_keepRefEdits.setText("")
        self.chb_keepRefEdits.setChecked(True)
        self.chb_keepRefEdits.setObjectName("chb_keepRefEdits")
        self.horizontalLayout_10.addWidget(self.chb_keepRefEdits)
        self.verticalLayout_6.addWidget(self.f_keepRefEdits)
        self.f_nameSpaces = QtGui.QWidget(self.gb_options)
        self.f_nameSpaces.setObjectName("f_nameSpaces")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.f_nameSpaces)
        self.horizontalLayout_12.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_keepRefEdits_2 = QtGui.QLabel(self.f_nameSpaces)
        self.l_keepRefEdits_2.setObjectName("l_keepRefEdits_2")
        self.horizontalLayout_12.addWidget(self.l_keepRefEdits_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.chb_autoNameSpaces = QtGui.QCheckBox(self.f_nameSpaces)
        self.chb_autoNameSpaces.setChecked(False)
        self.chb_autoNameSpaces.setObjectName("chb_autoNameSpaces")
        self.horizontalLayout_12.addWidget(self.chb_autoNameSpaces)
        spacerItem5 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.b_nameSpaces = QtGui.QPushButton(self.f_nameSpaces)
        self.b_nameSpaces.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_nameSpaces.setObjectName("b_nameSpaces")
        self.horizontalLayout_12.addWidget(self.b_nameSpaces)
        self.verticalLayout_6.addWidget(self.f_nameSpaces)
        self.f_unitConversion = QtGui.QWidget(self.gb_options)
        self.f_unitConversion.setObjectName("f_unitConversion")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.f_unitConversion)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.l_keepRefEdits_3 = QtGui.QLabel(self.f_unitConversion)
        self.l_keepRefEdits_3.setObjectName("l_keepRefEdits_3")
        self.horizontalLayout_13.addWidget(self.l_keepRefEdits_3)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.b_unitConversion = QtGui.QPushButton(self.f_unitConversion)
        self.b_unitConversion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_unitConversion.setObjectName("b_unitConversion")
        self.horizontalLayout_13.addWidget(self.b_unitConversion)
        self.verticalLayout_6.addWidget(self.f_unitConversion)
        self.f_abcPath = QtGui.QWidget(self.gb_options)
        self.f_abcPath.setObjectName("f_abcPath")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.f_abcPath)
        self.horizontalLayout_11.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.l_abcPath = QtGui.QLabel(self.f_abcPath)
        self.l_abcPath.setObjectName("l_abcPath")
        self.horizontalLayout_11.addWidget(self.l_abcPath)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.chb_abcPath = QtGui.QCheckBox(self.f_abcPath)
        self.chb_abcPath.setText("")
        self.chb_abcPath.setChecked(True)
        self.chb_abcPath.setObjectName("chb_abcPath")
        self.horizontalLayout_11.addWidget(self.chb_abcPath)
        self.verticalLayout_6.addWidget(self.f_abcPath)
        self.w_preferUnit = QtGui.QWidget(self.gb_options)
        self.w_preferUnit.setObjectName("w_preferUnit")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.w_preferUnit)
        self.horizontalLayout_8.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_preferUnit = QtGui.QLabel(self.w_preferUnit)
        self.l_preferUnit.setObjectName("l_preferUnit")
        self.horizontalLayout_8.addWidget(self.l_preferUnit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.chb_preferUnit = QtGui.QCheckBox(self.w_preferUnit)
        self.chb_preferUnit.setText("")
        self.chb_preferUnit.setObjectName("chb_preferUnit")
        self.horizontalLayout_8.addWidget(self.chb_preferUnit)
        self.verticalLayout_6.addWidget(self.w_preferUnit)
        self.w_trackObjects = QtGui.QWidget(self.gb_options)
        self.w_trackObjects.setObjectName("w_trackObjects")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.w_trackObjects)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.l_trackObjects = QtGui.QLabel(self.w_trackObjects)
        self.l_trackObjects.setObjectName("l_trackObjects")
        self.horizontalLayout_9.addWidget(self.l_trackObjects)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.chb_trackObjects = QtGui.QCheckBox(self.w_trackObjects)
        self.chb_trackObjects.setText("")
        self.chb_trackObjects.setChecked(True)
        self.chb_trackObjects.setObjectName("chb_trackObjects")
        self.horizontalLayout_9.addWidget(self.chb_trackObjects)
        self.verticalLayout_6.addWidget(self.w_trackObjects)
        self.verticalLayout_2.addWidget(self.gb_options)
        self.gb_objects = QtGui.QGroupBox(self.gb_import)
        self.gb_objects.setObjectName("gb_objects")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gb_objects)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lw_objects = QtGui.QListWidget(self.gb_objects)
        self.lw_objects.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lw_objects.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_objects.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_objects.setObjectName("lw_objects")
        self.verticalLayout_4.addWidget(self.lw_objects)
        self.b_selectAll = QtGui.QPushButton(self.gb_objects)
        self.b_selectAll.setObjectName("b_selectAll")
        self.verticalLayout_4.addWidget(self.b_selectAll)
        self.verticalLayout_2.addWidget(self.gb_objects)
        self.verticalLayout.addWidget(self.gb_import)

        self.retranslateUi(wg_ImportFile)
        QtCore.QMetaObject.connectSlotsByName(wg_ImportFile)
        wg_ImportFile.setTabOrder(self.e_name, self.e_file)

    def retranslateUi(self, wg_ImportFile):
        wg_ImportFile.setWindowTitle(QtGui.QApplication.translate("wg_ImportFile", "ImportFile", None, QtGui.QApplication.UnicodeUTF8))
        self.l_name.setText(QtGui.QApplication.translate("wg_ImportFile", "State name:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_class.setText(QtGui.QApplication.translate("wg_ImportFile", "ImportFile", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_import.setTitle(QtGui.QApplication.translate("wg_ImportFile", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.l_file.setText(QtGui.QApplication.translate("wg_ImportFile", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browse.setText(QtGui.QApplication.translate("wg_ImportFile", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.b_import.setText(QtGui.QApplication.translate("wg_ImportFile", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("wg_ImportFile", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("wg_ImportFile", "Current Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_curVersion.setText(QtGui.QApplication.translate("wg_ImportFile", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.l_autoUpdate.setText(QtGui.QApplication.translate("wg_ImportFile", "Auto load latest version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("wg_ImportFile", "Latest Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_latestVersion.setText(QtGui.QApplication.translate("wg_ImportFile", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.b_importLatest.setText(QtGui.QApplication.translate("wg_ImportFile", "Import latest Version", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_options.setTitle(QtGui.QApplication.translate("wg_ImportFile", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.l_keepRefEdits.setText(QtGui.QApplication.translate("wg_ImportFile", "Keep Reference Edits:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_keepRefEdits_2.setText(QtGui.QApplication.translate("wg_ImportFile", "Maya Namespaces:", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_autoNameSpaces.setText(QtGui.QApplication.translate("wg_ImportFile", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.b_nameSpaces.setText(QtGui.QApplication.translate("wg_ImportFile", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.l_keepRefEdits_3.setText(QtGui.QApplication.translate("wg_ImportFile", "Unit conversion:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_unitConversion.setText(QtGui.QApplication.translate("wg_ImportFile", "cm -> m", None, QtGui.QApplication.UnicodeUTF8))
        self.l_abcPath.setText(QtGui.QApplication.translate("wg_ImportFile", "Alembic - Update path only (if exists)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_preferUnit.setText(QtGui.QApplication.translate("wg_ImportFile", "Prefer versions in meter:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_trackObjects.setText(QtGui.QApplication.translate("wg_ImportFile", "Keep track of connected objects:", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_objects.setTitle(QtGui.QApplication.translate("wg_ImportFile", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.b_selectAll.setText(QtGui.QApplication.translate("wg_ImportFile", "Select all", None, QtGui.QApplication.UnicodeUTF8))

