# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'default_ImageRender.ui'
#
# Created: Thu Sep 28 22:23:19 2023
#      by: qtpy-uic 2.0.5
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_wg_ImageRender(object):
    def setupUi(self, wg_ImageRender):
        wg_ImageRender.setObjectName("wg_ImageRender")
        wg_ImageRender.resize(340, 1103)
        self.verticalLayout = QtWidgets.QVBoxLayout(wg_ImageRender)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_name = QtWidgets.QWidget(wg_ImageRender)
        self.f_name.setObjectName("f_name")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.f_name)
        self.horizontalLayout_4.setContentsMargins(9, 0, 18, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.l_name = QtWidgets.QLabel(self.f_name)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_4.addWidget(self.l_name)
        self.e_name = QtWidgets.QLineEdit(self.f_name)
        self.e_name.setObjectName("e_name")
        self.horizontalLayout_4.addWidget(self.e_name)
        self.l_class = QtWidgets.QLabel(self.f_name)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.l_class.setFont(font)
        self.l_class.setObjectName("l_class")
        self.horizontalLayout_4.addWidget(self.l_class)
        self.verticalLayout.addWidget(self.f_name)
        self.gb_imageRender = QtWidgets.QGroupBox(wg_ImageRender)
        self.gb_imageRender.setObjectName("gb_imageRender")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_imageRender)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_context = QtWidgets.QWidget(self.gb_imageRender)
        self.w_context.setObjectName("w_context")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.w_context)
        self.horizontalLayout_11.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.w_context)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.l_context = QtWidgets.QLabel(self.w_context)
        self.l_context.setText("")
        self.l_context.setObjectName("l_context")
        self.horizontalLayout_11.addWidget(self.l_context)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.b_context = QtWidgets.QPushButton(self.w_context)
        self.b_context.setObjectName("b_context")
        self.horizontalLayout_11.addWidget(self.b_context)
        self.cb_context = QtWidgets.QComboBox(self.w_context)
        self.cb_context.setObjectName("cb_context")
        self.horizontalLayout_11.addWidget(self.cb_context)
        self.verticalLayout_2.addWidget(self.w_context)
        self.f_taskname = QtWidgets.QWidget(self.gb_imageRender)
        self.f_taskname.setObjectName("f_taskname")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.f_taskname)
        self.horizontalLayout_10.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.f_taskname)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.l_taskName = QtWidgets.QLabel(self.f_taskname)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_taskName.sizePolicy().hasHeightForWidth())
        self.l_taskName.setSizePolicy(sizePolicy)
        self.l_taskName.setText("")
        self.l_taskName.setAlignment(QtCore.Qt.AlignCenter)
        self.l_taskName.setObjectName("l_taskName")
        self.horizontalLayout_10.addWidget(self.l_taskName)
        self.b_changeTask = QtWidgets.QPushButton(self.f_taskname)
        self.b_changeTask.setEnabled(True)
        self.b_changeTask.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_changeTask.setObjectName("b_changeTask")
        self.horizontalLayout_10.addWidget(self.b_changeTask)
        self.verticalLayout_2.addWidget(self.f_taskname)
        self.f_range = QtWidgets.QWidget(self.gb_imageRender)
        self.f_range.setObjectName("f_range")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.f_range)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.f_range)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cb_rangeType = QtWidgets.QComboBox(self.f_range)
        self.cb_rangeType.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_rangeType.setObjectName("cb_rangeType")
        self.horizontalLayout.addWidget(self.cb_rangeType)
        self.verticalLayout_2.addWidget(self.f_range)
        self.w_frameRangeValues = QtWidgets.QWidget(self.gb_imageRender)
        self.w_frameRangeValues.setObjectName("w_frameRangeValues")
        self.gridLayout = QtWidgets.QGridLayout(self.w_frameRangeValues)
        self.gridLayout.setContentsMargins(9, 0, 9, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l_rangeEnd = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeEnd.setMinimumSize(QtCore.QSize(30, 0))
        self.l_rangeEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_rangeEnd.setObjectName("l_rangeEnd")
        self.gridLayout.addWidget(self.l_rangeEnd, 1, 5, 1, 1)
        self.sp_rangeEnd = QtWidgets.QSpinBox(self.w_frameRangeValues)
        self.sp_rangeEnd.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sp_rangeEnd.setMaximum(99999)
        self.sp_rangeEnd.setProperty("value", 1100)
        self.sp_rangeEnd.setObjectName("sp_rangeEnd")
        self.gridLayout.addWidget(self.sp_rangeEnd, 1, 6, 1, 1)
        self.sp_rangeStart = QtWidgets.QSpinBox(self.w_frameRangeValues)
        self.sp_rangeStart.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sp_rangeStart.setMaximum(99999)
        self.sp_rangeStart.setProperty("value", 1001)
        self.sp_rangeStart.setObjectName("sp_rangeStart")
        self.gridLayout.addWidget(self.sp_rangeStart, 0, 6, 1, 1)
        self.l_rangeStart = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeStart.setMinimumSize(QtCore.QSize(30, 0))
        self.l_rangeStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_rangeStart.setObjectName("l_rangeStart")
        self.gridLayout.addWidget(self.l_rangeStart, 0, 5, 1, 1)
        self.l_rangeStartInfo = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeStartInfo.setObjectName("l_rangeStartInfo")
        self.gridLayout.addWidget(self.l_rangeStartInfo, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.l_rangeEndInfo = QtWidgets.QLabel(self.w_frameRangeValues)
        self.l_rangeEndInfo.setObjectName("l_rangeEndInfo")
        self.gridLayout.addWidget(self.l_rangeEndInfo, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.w_frameRangeValues)
        self.w_frameExpression = QtWidgets.QWidget(self.gb_imageRender)
        self.w_frameExpression.setObjectName("w_frameExpression")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.w_frameExpression)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.l_frameExpression = QtWidgets.QLabel(self.w_frameExpression)
        self.l_frameExpression.setObjectName("l_frameExpression")
        self.horizontalLayout_15.addWidget(self.l_frameExpression)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.le_frameExpression = QtWidgets.QLineEdit(self.w_frameExpression)
        self.le_frameExpression.setMinimumSize(QtCore.QSize(150, 0))
        self.le_frameExpression.setObjectName("le_frameExpression")
        self.horizontalLayout_15.addWidget(self.le_frameExpression)
        self.verticalLayout_2.addWidget(self.w_frameExpression)
        self.f_cam = QtWidgets.QWidget(self.gb_imageRender)
        self.f_cam.setObjectName("f_cam")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.f_cam)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.f_cam)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.cb_cam = QtWidgets.QComboBox(self.f_cam)
        self.cb_cam.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_cam.setObjectName("cb_cam")
        self.horizontalLayout_2.addWidget(self.cb_cam)
        self.verticalLayout_2.addWidget(self.f_cam)
        self.f_resolution = QtWidgets.QWidget(self.gb_imageRender)
        self.f_resolution.setObjectName("f_resolution")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.f_resolution)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.f_resolution)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.chb_resOverride = QtWidgets.QCheckBox(self.f_resolution)
        self.chb_resOverride.setText("")
        self.chb_resOverride.setObjectName("chb_resOverride")
        self.horizontalLayout_9.addWidget(self.chb_resOverride)
        self.sp_resWidth = QtWidgets.QSpinBox(self.f_resolution)
        self.sp_resWidth.setEnabled(False)
        self.sp_resWidth.setMinimum(1)
        self.sp_resWidth.setMaximum(99999)
        self.sp_resWidth.setProperty("value", 1280)
        self.sp_resWidth.setObjectName("sp_resWidth")
        self.horizontalLayout_9.addWidget(self.sp_resWidth)
        self.sp_resHeight = QtWidgets.QSpinBox(self.f_resolution)
        self.sp_resHeight.setEnabled(False)
        self.sp_resHeight.setMinimum(1)
        self.sp_resHeight.setMaximum(99999)
        self.sp_resHeight.setProperty("value", 720)
        self.sp_resHeight.setObjectName("sp_resHeight")
        self.horizontalLayout_9.addWidget(self.sp_resHeight)
        self.b_resPresets = QtWidgets.QPushButton(self.f_resolution)
        self.b_resPresets.setEnabled(False)
        self.b_resPresets.setMinimumSize(QtCore.QSize(23, 23))
        self.b_resPresets.setMaximumSize(QtCore.QSize(23, 23))
        self.b_resPresets.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_resPresets.setObjectName("b_resPresets")
        self.horizontalLayout_9.addWidget(self.b_resPresets)
        self.verticalLayout_2.addWidget(self.f_resolution)
        self.w_renderPreset = QtWidgets.QWidget(self.gb_imageRender)
        self.w_renderPreset.setObjectName("w_renderPreset")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.w_renderPreset)
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.l_renderPreset = QtWidgets.QLabel(self.w_renderPreset)
        self.l_renderPreset.setObjectName("l_renderPreset")
        self.horizontalLayout_14.addWidget(self.l_renderPreset)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.chb_renderPreset = QtWidgets.QCheckBox(self.w_renderPreset)
        self.chb_renderPreset.setText("")
        self.chb_renderPreset.setObjectName("chb_renderPreset")
        self.horizontalLayout_14.addWidget(self.chb_renderPreset)
        self.cb_renderPreset = QtWidgets.QComboBox(self.w_renderPreset)
        self.cb_renderPreset.setEnabled(False)
        self.cb_renderPreset.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_renderPreset.setObjectName("cb_renderPreset")
        self.horizontalLayout_14.addWidget(self.cb_renderPreset)
        self.verticalLayout_2.addWidget(self.w_renderPreset)
        self.w_master = QtWidgets.QWidget(self.gb_imageRender)
        self.w_master.setObjectName("w_master")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.w_master)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.l_outPath_2 = QtWidgets.QLabel(self.w_master)
        self.l_outPath_2.setObjectName("l_outPath_2")
        self.horizontalLayout_17.addWidget(self.l_outPath_2)
        spacerItem8 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.cb_master = QtWidgets.QComboBox(self.w_master)
        self.cb_master.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_master.setObjectName("cb_master")
        self.horizontalLayout_17.addWidget(self.cb_master)
        self.verticalLayout_2.addWidget(self.w_master)
        self.w_outPath = QtWidgets.QWidget(self.gb_imageRender)
        self.w_outPath.setObjectName("w_outPath")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.w_outPath)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.l_outPath = QtWidgets.QLabel(self.w_outPath)
        self.l_outPath.setObjectName("l_outPath")
        self.horizontalLayout_16.addWidget(self.l_outPath)
        spacerItem9 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.cb_outPath = QtWidgets.QComboBox(self.w_outPath)
        self.cb_outPath.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_outPath.setObjectName("cb_outPath")
        self.horizontalLayout_16.addWidget(self.cb_outPath)
        self.verticalLayout_2.addWidget(self.w_outPath)
        self.f_renderLayer = QtWidgets.QWidget(self.gb_imageRender)
        self.f_renderLayer.setObjectName("f_renderLayer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.f_renderLayer)
        self.horizontalLayout_5.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.f_renderLayer)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.cb_renderLayer = QtWidgets.QComboBox(self.f_renderLayer)
        self.cb_renderLayer.setEnabled(True)
        self.cb_renderLayer.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_renderLayer.setObjectName("cb_renderLayer")
        self.horizontalLayout_5.addWidget(self.cb_renderLayer)
        self.verticalLayout_2.addWidget(self.f_renderLayer)
        self.w_format = QtWidgets.QWidget(self.gb_imageRender)
        self.w_format.setObjectName("w_format")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.w_format)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.w_format)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.cb_format = QtWidgets.QComboBox(self.w_format)
        self.cb_format.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_format.setObjectName("cb_format")
        self.horizontalLayout_6.addWidget(self.cb_format)
        self.verticalLayout_2.addWidget(self.w_format)
        self.verticalLayout.addWidget(self.gb_imageRender)
        self.gb_submit = QtWidgets.QGroupBox(wg_ImageRender)
        self.gb_submit.setCheckable(True)
        self.gb_submit.setChecked(True)
        self.gb_submit.setObjectName("gb_submit")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gb_submit)
        self.verticalLayout_8.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.f_manager = QtWidgets.QWidget(self.gb_submit)
        self.f_manager.setObjectName("f_manager")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.f_manager)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.l_manager = QtWidgets.QLabel(self.f_manager)
        self.l_manager.setObjectName("l_manager")
        self.horizontalLayout_13.addWidget(self.l_manager)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.cb_manager = QtWidgets.QComboBox(self.f_manager)
        self.cb_manager.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_manager.setObjectName("cb_manager")
        self.horizontalLayout_13.addWidget(self.cb_manager)
        self.verticalLayout_8.addWidget(self.f_manager)
        self.f_rjPrio = QtWidgets.QWidget(self.gb_submit)
        self.f_rjPrio.setObjectName("f_rjPrio")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.f_rjPrio)
        self.horizontalLayout_21.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.l_rjPrio = QtWidgets.QLabel(self.f_rjPrio)
        self.l_rjPrio.setObjectName("l_rjPrio")
        self.horizontalLayout_21.addWidget(self.l_rjPrio)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem13)
        self.sp_rjPrio = QtWidgets.QSpinBox(self.f_rjPrio)
        self.sp_rjPrio.setMaximum(100)
        self.sp_rjPrio.setProperty("value", 50)
        self.sp_rjPrio.setObjectName("sp_rjPrio")
        self.horizontalLayout_21.addWidget(self.sp_rjPrio)
        self.verticalLayout_8.addWidget(self.f_rjPrio)
        self.f_rjWidgetsPerTask = QtWidgets.QWidget(self.gb_submit)
        self.f_rjWidgetsPerTask.setObjectName("f_rjWidgetsPerTask")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.f_rjWidgetsPerTask)
        self.horizontalLayout_22.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.f_rjWidgetsPerTask)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem14)
        self.sp_rjFramesPerTask = QtWidgets.QSpinBox(self.f_rjWidgetsPerTask)
        self.sp_rjFramesPerTask.setMaximum(9999)
        self.sp_rjFramesPerTask.setProperty("value", 5)
        self.sp_rjFramesPerTask.setObjectName("sp_rjFramesPerTask")
        self.horizontalLayout_22.addWidget(self.sp_rjFramesPerTask)
        self.verticalLayout_8.addWidget(self.f_rjWidgetsPerTask)
        self.f_rjTimeout = QtWidgets.QWidget(self.gb_submit)
        self.f_rjTimeout.setObjectName("f_rjTimeout")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.f_rjTimeout)
        self.horizontalLayout_28.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.l_rjTimeout = QtWidgets.QLabel(self.f_rjTimeout)
        self.l_rjTimeout.setObjectName("l_rjTimeout")
        self.horizontalLayout_28.addWidget(self.l_rjTimeout)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem15)
        self.sp_rjTimeout = QtWidgets.QSpinBox(self.f_rjTimeout)
        self.sp_rjTimeout.setMinimum(1)
        self.sp_rjTimeout.setMaximum(9999)
        self.sp_rjTimeout.setProperty("value", 180)
        self.sp_rjTimeout.setObjectName("sp_rjTimeout")
        self.horizontalLayout_28.addWidget(self.sp_rjTimeout)
        self.verticalLayout_8.addWidget(self.f_rjTimeout)
        self.f_rjSuspended = QtWidgets.QWidget(self.gb_submit)
        self.f_rjSuspended.setObjectName("f_rjSuspended")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.f_rjSuspended)
        self.horizontalLayout_26.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_18 = QtWidgets.QLabel(self.f_rjSuspended)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_26.addWidget(self.label_18)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem16)
        self.chb_rjSuspended = QtWidgets.QCheckBox(self.f_rjSuspended)
        self.chb_rjSuspended.setText("")
        self.chb_rjSuspended.setChecked(False)
        self.chb_rjSuspended.setObjectName("chb_rjSuspended")
        self.horizontalLayout_26.addWidget(self.chb_rjSuspended)
        self.verticalLayout_8.addWidget(self.f_rjSuspended)
        self.f_osDependencies = QtWidgets.QWidget(self.gb_submit)
        self.f_osDependencies.setObjectName("f_osDependencies")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.f_osDependencies)
        self.horizontalLayout_27.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.f_osDependencies)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem17)
        self.chb_osDependencies = QtWidgets.QCheckBox(self.f_osDependencies)
        self.chb_osDependencies.setText("")
        self.chb_osDependencies.setChecked(True)
        self.chb_osDependencies.setObjectName("chb_osDependencies")
        self.horizontalLayout_27.addWidget(self.chb_osDependencies)
        self.verticalLayout_8.addWidget(self.f_osDependencies)
        self.f_osUpload = QtWidgets.QWidget(self.gb_submit)
        self.f_osUpload.setObjectName("f_osUpload")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.f_osUpload)
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_16 = QtWidgets.QLabel(self.f_osUpload)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_23.addWidget(self.label_16)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.chb_osUpload = QtWidgets.QCheckBox(self.f_osUpload)
        self.chb_osUpload.setText("")
        self.chb_osUpload.setChecked(True)
        self.chb_osUpload.setObjectName("chb_osUpload")
        self.horizontalLayout_23.addWidget(self.chb_osUpload)
        self.verticalLayout_8.addWidget(self.f_osUpload)
        self.f_osPAssets = QtWidgets.QWidget(self.gb_submit)
        self.f_osPAssets.setObjectName("f_osPAssets")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.f_osPAssets)
        self.horizontalLayout_24.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_17 = QtWidgets.QLabel(self.f_osPAssets)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_24.addWidget(self.label_17)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.chb_osPAssets = QtWidgets.QCheckBox(self.f_osPAssets)
        self.chb_osPAssets.setText("")
        self.chb_osPAssets.setChecked(True)
        self.chb_osPAssets.setObjectName("chb_osPAssets")
        self.horizontalLayout_24.addWidget(self.chb_osPAssets)
        self.verticalLayout_8.addWidget(self.f_osPAssets)
        self.gb_osSlaves = QtWidgets.QGroupBox(self.gb_submit)
        self.gb_osSlaves.setObjectName("gb_osSlaves")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.gb_osSlaves)
        self.horizontalLayout_25.setContentsMargins(9, 3, 9, 3)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.e_osSlaves = QtWidgets.QLineEdit(self.gb_osSlaves)
        self.e_osSlaves.setObjectName("e_osSlaves")
        self.horizontalLayout_25.addWidget(self.e_osSlaves)
        self.b_osSlaves = QtWidgets.QPushButton(self.gb_osSlaves)
        self.b_osSlaves.setMaximumSize(QtCore.QSize(25, 16777215))
        self.b_osSlaves.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_osSlaves.setObjectName("b_osSlaves")
        self.horizontalLayout_25.addWidget(self.b_osSlaves)
        self.verticalLayout_8.addWidget(self.gb_osSlaves)
        self.w_dlConcurrentTasks = QtWidgets.QWidget(self.gb_submit)
        self.w_dlConcurrentTasks.setObjectName("w_dlConcurrentTasks")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.w_dlConcurrentTasks)
        self.horizontalLayout_29.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.l_dlConcurrentTasks = QtWidgets.QLabel(self.w_dlConcurrentTasks)
        self.l_dlConcurrentTasks.setObjectName("l_dlConcurrentTasks")
        self.horizontalLayout_29.addWidget(self.l_dlConcurrentTasks)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem20)
        self.sp_dlConcurrentTasks = QtWidgets.QSpinBox(self.w_dlConcurrentTasks)
        self.sp_dlConcurrentTasks.setMinimum(1)
        self.sp_dlConcurrentTasks.setMaximum(99)
        self.sp_dlConcurrentTasks.setProperty("value", 1)
        self.sp_dlConcurrentTasks.setObjectName("sp_dlConcurrentTasks")
        self.horizontalLayout_29.addWidget(self.sp_dlConcurrentTasks)
        self.verticalLayout_8.addWidget(self.w_dlConcurrentTasks)
        self.w_dlGPUpt = QtWidgets.QWidget(self.gb_submit)
        self.w_dlGPUpt.setObjectName("w_dlGPUpt")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.w_dlGPUpt)
        self.horizontalLayout_30.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.l_dlGPUpt = QtWidgets.QLabel(self.w_dlGPUpt)
        self.l_dlGPUpt.setObjectName("l_dlGPUpt")
        self.horizontalLayout_30.addWidget(self.l_dlGPUpt)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem21)
        self.sp_dlGPUpt = QtWidgets.QSpinBox(self.w_dlGPUpt)
        self.sp_dlGPUpt.setMinimum(0)
        self.sp_dlGPUpt.setMaximum(99)
        self.sp_dlGPUpt.setProperty("value", 0)
        self.sp_dlGPUpt.setObjectName("sp_dlGPUpt")
        self.horizontalLayout_30.addWidget(self.sp_dlGPUpt)
        self.verticalLayout_8.addWidget(self.w_dlGPUpt)
        self.w_dlGPUdevices = QtWidgets.QWidget(self.gb_submit)
        self.w_dlGPUdevices.setObjectName("w_dlGPUdevices")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.w_dlGPUdevices)
        self.horizontalLayout_31.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.l_dlGPUdevices = QtWidgets.QLabel(self.w_dlGPUdevices)
        self.l_dlGPUdevices.setObjectName("l_dlGPUdevices")
        self.horizontalLayout_31.addWidget(self.l_dlGPUdevices)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem22)
        self.le_dlGPUdevices = QtWidgets.QLineEdit(self.w_dlGPUdevices)
        self.le_dlGPUdevices.setMinimumSize(QtCore.QSize(150, 0))
        self.le_dlGPUdevices.setObjectName("le_dlGPUdevices")
        self.horizontalLayout_31.addWidget(self.le_dlGPUdevices)
        self.verticalLayout_8.addWidget(self.w_dlGPUdevices)
        self.verticalLayout.addWidget(self.gb_submit)
        self.gb_passes = QtWidgets.QGroupBox(wg_ImageRender)
        self.gb_passes.setCheckable(True)
        self.gb_passes.setObjectName("gb_passes")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_passes)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lw_passes = QtWidgets.QListWidget(self.gb_passes)
        self.lw_passes.setMaximumSize(QtCore.QSize(16777215, 500))
        self.lw_passes.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_passes.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lw_passes.setObjectName("lw_passes")
        self.verticalLayout_5.addWidget(self.lw_passes)
        self.b_addPasses = QtWidgets.QPushButton(self.gb_passes)
        self.b_addPasses.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addPasses.setObjectName("b_addPasses")
        self.verticalLayout_5.addWidget(self.b_addPasses)
        self.verticalLayout.addWidget(self.gb_passes)
        self.gb_previous = QtWidgets.QGroupBox(wg_ImageRender)
        self.gb_previous.setCheckable(False)
        self.gb_previous.setChecked(False)
        self.gb_previous.setObjectName("gb_previous")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.gb_previous)
        self.horizontalLayout_18.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.scrollArea = QtWidgets.QScrollArea(self.gb_previous)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 289, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_pathLast = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.l_pathLast.setObjectName("l_pathLast")
        self.verticalLayout_3.addWidget(self.l_pathLast)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_18.addWidget(self.scrollArea)
        self.b_pathLast = QtWidgets.QToolButton(self.gb_previous)
        self.b_pathLast.setEnabled(True)
        self.b_pathLast.setArrowType(QtCore.Qt.DownArrow)
        self.b_pathLast.setObjectName("b_pathLast")
        self.horizontalLayout_18.addWidget(self.b_pathLast)
        self.verticalLayout.addWidget(self.gb_previous)

        self.retranslateUi(wg_ImageRender)
        QtCore.QMetaObject.connectSlotsByName(wg_ImageRender)
        wg_ImageRender.setTabOrder(self.e_name, self.b_context)
        wg_ImageRender.setTabOrder(self.b_context, self.cb_context)
        wg_ImageRender.setTabOrder(self.cb_context, self.cb_rangeType)
        wg_ImageRender.setTabOrder(self.cb_rangeType, self.sp_rangeStart)
        wg_ImageRender.setTabOrder(self.sp_rangeStart, self.sp_rangeEnd)
        wg_ImageRender.setTabOrder(self.sp_rangeEnd, self.le_frameExpression)
        wg_ImageRender.setTabOrder(self.le_frameExpression, self.cb_cam)
        wg_ImageRender.setTabOrder(self.cb_cam, self.chb_resOverride)
        wg_ImageRender.setTabOrder(self.chb_resOverride, self.sp_resWidth)
        wg_ImageRender.setTabOrder(self.sp_resWidth, self.sp_resHeight)
        wg_ImageRender.setTabOrder(self.sp_resHeight, self.chb_renderPreset)
        wg_ImageRender.setTabOrder(self.chb_renderPreset, self.cb_renderPreset)
        wg_ImageRender.setTabOrder(self.cb_renderPreset, self.cb_master)
        wg_ImageRender.setTabOrder(self.cb_master, self.cb_outPath)
        wg_ImageRender.setTabOrder(self.cb_outPath, self.cb_renderLayer)
        wg_ImageRender.setTabOrder(self.cb_renderLayer, self.cb_format)
        wg_ImageRender.setTabOrder(self.cb_format, self.gb_submit)
        wg_ImageRender.setTabOrder(self.gb_submit, self.cb_manager)
        wg_ImageRender.setTabOrder(self.cb_manager, self.sp_rjPrio)
        wg_ImageRender.setTabOrder(self.sp_rjPrio, self.sp_rjFramesPerTask)
        wg_ImageRender.setTabOrder(self.sp_rjFramesPerTask, self.sp_rjTimeout)
        wg_ImageRender.setTabOrder(self.sp_rjTimeout, self.chb_rjSuspended)
        wg_ImageRender.setTabOrder(self.chb_rjSuspended, self.chb_osDependencies)
        wg_ImageRender.setTabOrder(self.chb_osDependencies, self.chb_osUpload)
        wg_ImageRender.setTabOrder(self.chb_osUpload, self.chb_osPAssets)
        wg_ImageRender.setTabOrder(self.chb_osPAssets, self.e_osSlaves)
        wg_ImageRender.setTabOrder(self.e_osSlaves, self.sp_dlConcurrentTasks)
        wg_ImageRender.setTabOrder(self.sp_dlConcurrentTasks, self.sp_dlGPUpt)
        wg_ImageRender.setTabOrder(self.sp_dlGPUpt, self.le_dlGPUdevices)
        wg_ImageRender.setTabOrder(self.le_dlGPUdevices, self.gb_passes)
        wg_ImageRender.setTabOrder(self.gb_passes, self.lw_passes)
        wg_ImageRender.setTabOrder(self.lw_passes, self.scrollArea)
        wg_ImageRender.setTabOrder(self.scrollArea, self.b_pathLast)

    def retranslateUi(self, wg_ImageRender):
        wg_ImageRender.setWindowTitle(QtWidgets.QApplication.translate("", "Image Render", None, -1))
        self.l_name.setText(QtWidgets.QApplication.translate("", "Name:", None, -1))
        self.l_class.setText(QtWidgets.QApplication.translate("", "ImageRender", None, -1))
        self.gb_imageRender.setTitle(QtWidgets.QApplication.translate("", "General", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("", "Context:", None, -1))
        self.b_context.setText(QtWidgets.QApplication.translate("", "Select", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("", "Identifier:", None, -1))
        self.b_changeTask.setText(QtWidgets.QApplication.translate("", "change", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("", "Framerange:", None, -1))
        self.l_rangeEnd.setText(QtWidgets.QApplication.translate("", "1100", None, -1))
        self.l_rangeStart.setText(QtWidgets.QApplication.translate("", "1001", None, -1))
        self.l_rangeStartInfo.setText(QtWidgets.QApplication.translate("", "Start:", None, -1))
        self.l_rangeEndInfo.setText(QtWidgets.QApplication.translate("", "End:", None, -1))
        self.l_frameExpression.setText(QtWidgets.QApplication.translate("", "Frame expression:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "Camera:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("", "Resolution override:", None, -1))
        self.b_resPresets.setText(QtWidgets.QApplication.translate("", "▼", None, -1))
        self.l_renderPreset.setText(QtWidgets.QApplication.translate("", "Rendersettings preset:", None, -1))
        self.l_outPath_2.setText(QtWidgets.QApplication.translate("", "Master Version:", None, -1))
        self.l_outPath.setText(QtWidgets.QApplication.translate("", "Location:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("", "Render layer:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("", "Format:", None, -1))
        self.gb_submit.setTitle(QtWidgets.QApplication.translate("", "Submit Render Job", None, -1))
        self.l_manager.setText(QtWidgets.QApplication.translate("", "Manager:", None, -1))
        self.l_rjPrio.setText(QtWidgets.QApplication.translate("", "Priority:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("", "Frames per Task:", None, -1))
        self.l_rjTimeout.setText(QtWidgets.QApplication.translate("", "Task Timeout (min)", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("", "Submit suspended:", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("", "Submit dependent files:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("", "Upload output:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("", "Use Project Assets", None, -1))
        self.gb_osSlaves.setTitle(QtWidgets.QApplication.translate("", "Assign to slaves:", None, -1))
        self.b_osSlaves.setText(QtWidgets.QApplication.translate("", "...", None, -1))
        self.l_dlConcurrentTasks.setText(QtWidgets.QApplication.translate("", "Concurrent Tasks:", None, -1))
        self.l_dlGPUpt.setText(QtWidgets.QApplication.translate("", "GPUs Per Task:", None, -1))
        self.l_dlGPUdevices.setText(QtWidgets.QApplication.translate("", "Select GPU Devices:", None, -1))
        self.le_dlGPUdevices.setPlaceholderText(QtWidgets.QApplication.translate("", "Enter Valid GPU Device Id(s)", None, -1))
        self.gb_passes.setTitle(QtWidgets.QApplication.translate("", "Render Passes", None, -1))
        self.b_addPasses.setText(QtWidgets.QApplication.translate("", "Add Passes", None, -1))
        self.gb_previous.setTitle(QtWidgets.QApplication.translate("", "Previous render", None, -1))
        self.l_pathLast.setText(QtWidgets.QApplication.translate("", "None", None, -1))
        self.b_pathLast.setText(QtWidgets.QApplication.translate("", "...", None, -1))

