# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'default_Export.ui'
#
# Created: Wed Jan 13 11:55:24 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_wg_Export(object):
    def setupUi(self, wg_Export):
        wg_Export.setObjectName("wg_Export")
        wg_Export.resize(340, 712)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wg_Export.sizePolicy().hasHeightForWidth())
        wg_Export.setSizePolicy(sizePolicy)
        wg_Export.setMinimumSize(QtCore.QSize(340, 0))
        wg_Export.setMaximumSize(QtCore.QSize(340, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(wg_Export)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_name = QtGui.QWidget(wg_Export)
        self.w_name.setObjectName("w_name")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.w_name)
        self.horizontalLayout_5.setContentsMargins(9, 0, 18, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.l_name = QtGui.QLabel(self.w_name)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_5.addWidget(self.l_name)
        self.e_name = QtGui.QLineEdit(self.w_name)
        self.e_name.setMinimumSize(QtCore.QSize(0, 0))
        self.e_name.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.e_name.setObjectName("e_name")
        self.horizontalLayout_5.addWidget(self.e_name)
        self.l_class = QtGui.QLabel(self.w_name)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.l_class.setFont(font)
        self.l_class.setObjectName("l_class")
        self.horizontalLayout_5.addWidget(self.l_class)
        self.verticalLayout.addWidget(self.w_name)
        self.gb_export = QtGui.QGroupBox(wg_Export)
        self.gb_export.setObjectName("gb_export")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_export)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_taskname = QtGui.QWidget(self.gb_export)
        self.w_taskname.setObjectName("w_taskname")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.w_taskname)
        self.horizontalLayout_4.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.l_tasklabel = QtGui.QLabel(self.w_taskname)
        self.l_tasklabel.setObjectName("l_tasklabel")
        self.horizontalLayout_4.addWidget(self.l_tasklabel)
        self.l_taskName = QtGui.QLabel(self.w_taskname)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_taskName.sizePolicy().hasHeightForWidth())
        self.l_taskName.setSizePolicy(sizePolicy)
        self.l_taskName.setText("")
        self.l_taskName.setAlignment(QtCore.Qt.AlignCenter)
        self.l_taskName.setObjectName("l_taskName")
        self.horizontalLayout_4.addWidget(self.l_taskName)
        self.b_changeTask = QtGui.QPushButton(self.w_taskname)
        self.b_changeTask.setEnabled(True)
        self.b_changeTask.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_changeTask.setObjectName("b_changeTask")
        self.horizontalLayout_4.addWidget(self.b_changeTask)
        self.verticalLayout_2.addWidget(self.w_taskname)
        self.w_range = QtGui.QWidget(self.gb_export)
        self.w_range.setObjectName("w_range")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.w_range)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtGui.QLabel(self.w_range)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(37, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.cb_rangeType = QtGui.QComboBox(self.w_range)
        self.cb_rangeType.setObjectName("cb_rangeType")
        self.horizontalLayout_6.addWidget(self.cb_rangeType)
        self.verticalLayout_2.addWidget(self.w_range)
        self.f_frameRange_2 = QtGui.QWidget(self.gb_export)
        self.f_frameRange_2.setObjectName("f_frameRange_2")
        self.gridLayout = QtGui.QGridLayout(self.f_frameRange_2)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l_rangeEnd = QtGui.QLabel(self.f_frameRange_2)
        self.l_rangeEnd.setMinimumSize(QtCore.QSize(30, 0))
        self.l_rangeEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_rangeEnd.setObjectName("l_rangeEnd")
        self.gridLayout.addWidget(self.l_rangeEnd, 1, 5, 1, 1)
        self.sp_rangeEnd = QtGui.QSpinBox(self.f_frameRange_2)
        self.sp_rangeEnd.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sp_rangeEnd.setMaximum(99999)
        self.sp_rangeEnd.setProperty("value", 1100)
        self.sp_rangeEnd.setObjectName("sp_rangeEnd")
        self.gridLayout.addWidget(self.sp_rangeEnd, 1, 6, 1, 1)
        self.sp_rangeStart = QtGui.QSpinBox(self.f_frameRange_2)
        self.sp_rangeStart.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sp_rangeStart.setMaximum(99999)
        self.sp_rangeStart.setProperty("value", 1001)
        self.sp_rangeStart.setObjectName("sp_rangeStart")
        self.gridLayout.addWidget(self.sp_rangeStart, 0, 6, 1, 1)
        self.l_rangeStart = QtGui.QLabel(self.f_frameRange_2)
        self.l_rangeStart.setMinimumSize(QtCore.QSize(30, 0))
        self.l_rangeStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_rangeStart.setObjectName("l_rangeStart")
        self.gridLayout.addWidget(self.l_rangeStart, 0, 5, 1, 1)
        self.l_rangeStartInfo = QtGui.QLabel(self.f_frameRange_2)
        self.l_rangeStartInfo.setObjectName("l_rangeStartInfo")
        self.gridLayout.addWidget(self.l_rangeStartInfo, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.l_rangeEndInfo = QtGui.QLabel(self.f_frameRange_2)
        self.l_rangeEndInfo.setObjectName("l_rangeEndInfo")
        self.gridLayout.addWidget(self.l_rangeEndInfo, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.f_frameRange_2)
        self.w_outPath = QtGui.QWidget(self.gb_export)
        self.w_outPath.setObjectName("w_outPath")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.w_outPath)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.l_outPath = QtGui.QLabel(self.w_outPath)
        self.l_outPath.setObjectName("l_outPath")
        self.horizontalLayout_11.addWidget(self.l_outPath)
        spacerItem2 = QtGui.QSpacerItem(113, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.cb_outPath = QtGui.QComboBox(self.w_outPath)
        self.cb_outPath.setMinimumSize(QtCore.QSize(124, 0))
        self.cb_outPath.setObjectName("cb_outPath")
        self.horizontalLayout_11.addWidget(self.cb_outPath)
        self.verticalLayout_2.addWidget(self.w_outPath)
        self.w_outType = QtGui.QWidget(self.gb_export)
        self.w_outType.setObjectName("w_outType")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.w_outType)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.l_outType = QtGui.QLabel(self.w_outType)
        self.l_outType.setObjectName("l_outType")
        self.horizontalLayout_9.addWidget(self.l_outType)
        spacerItem3 = QtGui.QSpacerItem(113, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.cb_outType = QtGui.QComboBox(self.w_outType)
        self.cb_outType.setMinimumSize(QtCore.QSize(124, 0))
        self.cb_outType.setObjectName("cb_outType")
        self.horizontalLayout_9.addWidget(self.cb_outType)
        self.verticalLayout_2.addWidget(self.w_outType)
        self.w_cam = QtGui.QWidget(self.gb_export)
        self.w_cam.setObjectName("w_cam")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.w_cam)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l_cam = QtGui.QLabel(self.w_cam)
        self.l_cam.setMinimumSize(QtCore.QSize(40, 0))
        self.l_cam.setMaximumSize(QtCore.QSize(95, 16777215))
        self.l_cam.setObjectName("l_cam")
        self.horizontalLayout_3.addWidget(self.l_cam)
        self.cb_cam = QtGui.QComboBox(self.w_cam)
        self.cb_cam.setObjectName("cb_cam")
        self.horizontalLayout_3.addWidget(self.cb_cam)
        self.verticalLayout_2.addWidget(self.w_cam)
        self.w_sCamShot = QtGui.QWidget(self.gb_export)
        self.w_sCamShot.setObjectName("w_sCamShot")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.w_sCamShot)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.l_sCamShot = QtGui.QLabel(self.w_sCamShot)
        self.l_sCamShot.setMinimumSize(QtCore.QSize(40, 0))
        self.l_sCamShot.setMaximumSize(QtCore.QSize(95, 16777215))
        self.l_sCamShot.setObjectName("l_sCamShot")
        self.horizontalLayout_7.addWidget(self.l_sCamShot)
        self.cb_sCamShot = QtGui.QComboBox(self.w_sCamShot)
        self.cb_sCamShot.setObjectName("cb_sCamShot")
        self.horizontalLayout_7.addWidget(self.cb_sCamShot)
        self.verticalLayout_2.addWidget(self.w_sCamShot)
        self.w_selectCam = QtGui.QWidget(self.gb_export)
        self.w_selectCam.setObjectName("w_selectCam")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.w_selectCam)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_selectCam = QtGui.QPushButton(self.w_selectCam)
        self.b_selectCam.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_selectCam.setObjectName("b_selectCam")
        self.horizontalLayout_2.addWidget(self.b_selectCam)
        self.verticalLayout_2.addWidget(self.w_selectCam)
        self.w_convertExport = QtGui.QWidget(self.gb_export)
        self.w_convertExport.setObjectName("w_convertExport")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.w_convertExport)
        self.horizontalLayout_14.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.l_convertExport = QtGui.QLabel(self.w_convertExport)
        self.l_convertExport.setObjectName("l_convertExport")
        self.horizontalLayout_14.addWidget(self.l_convertExport)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.chb_convertExport = QtGui.QCheckBox(self.w_convertExport)
        self.chb_convertExport.setText("")
        self.chb_convertExport.setChecked(False)
        self.chb_convertExport.setObjectName("chb_convertExport")
        self.horizontalLayout_14.addWidget(self.chb_convertExport)
        self.verticalLayout_2.addWidget(self.w_convertExport)
        self.w_additionalOptions = QtGui.QWidget(self.gb_export)
        self.w_additionalOptions.setObjectName("w_additionalOptions")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.w_additionalOptions)
        self.horizontalLayout_15.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.l_additionalOptions = QtGui.QLabel(self.w_additionalOptions)
        self.l_additionalOptions.setObjectName("l_additionalOptions")
        self.horizontalLayout_15.addWidget(self.l_additionalOptions)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.chb_additionalOptions = QtGui.QCheckBox(self.w_additionalOptions)
        self.chb_additionalOptions.setText("")
        self.chb_additionalOptions.setChecked(False)
        self.chb_additionalOptions.setObjectName("chb_additionalOptions")
        self.horizontalLayout_15.addWidget(self.chb_additionalOptions)
        self.verticalLayout_2.addWidget(self.w_additionalOptions)
        self.w_wholeScene = QtGui.QWidget(self.gb_export)
        self.w_wholeScene.setObjectName("w_wholeScene")
        self.horizontalLayout = QtGui.QHBoxLayout(self.w_wholeScene)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_wholeScene = QtGui.QLabel(self.w_wholeScene)
        self.l_wholeScene.setObjectName("l_wholeScene")
        self.horizontalLayout.addWidget(self.l_wholeScene)
        spacerItem6 = QtGui.QSpacerItem(185, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.chb_wholeScene = QtGui.QCheckBox(self.w_wholeScene)
        self.chb_wholeScene.setText("")
        self.chb_wholeScene.setChecked(False)
        self.chb_wholeScene.setObjectName("chb_wholeScene")
        self.horizontalLayout.addWidget(self.chb_wholeScene)
        self.verticalLayout_2.addWidget(self.w_wholeScene)
        self.gb_objects = QtGui.QGroupBox(self.gb_export)
        self.gb_objects.setEnabled(True)
        self.gb_objects.setObjectName("gb_objects")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gb_objects)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.f_objectList = QtGui.QFrame(self.gb_objects)
        self.f_objectList.setObjectName("f_objectList")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.f_objectList)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lw_objects = QtGui.QListWidget(self.f_objectList)
        self.lw_objects.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_objects.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lw_objects.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_objects.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lw_objects.setObjectName("lw_objects")
        self.horizontalLayout_8.addWidget(self.lw_objects)
        self.verticalLayout_3.addWidget(self.f_objectList)
        self.b_add = QtGui.QPushButton(self.gb_objects)
        self.b_add.setMinimumSize(QtCore.QSize(0, 0))
        self.b_add.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.b_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_add.setObjectName("b_add")
        self.verticalLayout_3.addWidget(self.b_add)
        self.verticalLayout_2.addWidget(self.gb_objects)
        self.groupBox = QtGui.QGroupBox(self.gb_export)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_pathLast = QtGui.QLabel(self.groupBox)
        self.l_pathLast.setObjectName("l_pathLast")
        self.verticalLayout_4.addWidget(self.l_pathLast)
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.b_openLast = QtGui.QPushButton(self.widget)
        self.b_openLast.setEnabled(False)
        self.b_openLast.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_openLast.setObjectName("b_openLast")
        self.horizontalLayout_10.addWidget(self.b_openLast)
        self.b_copyLast = QtGui.QPushButton(self.widget)
        self.b_copyLast.setEnabled(False)
        self.b_copyLast.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_copyLast.setObjectName("b_copyLast")
        self.horizontalLayout_10.addWidget(self.b_copyLast)
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.gb_export)

        self.retranslateUi(wg_Export)
        QtCore.QMetaObject.connectSlotsByName(wg_Export)

    def retranslateUi(self, wg_Export):
        wg_Export.setWindowTitle(QtGui.QApplication.translate("wg_Export", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.l_name.setText(QtGui.QApplication.translate("wg_Export", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_class.setText(QtGui.QApplication.translate("wg_Export", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_export.setTitle(QtGui.QApplication.translate("wg_Export", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.l_tasklabel.setText(QtGui.QApplication.translate("wg_Export", "Taskname:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_changeTask.setText(QtGui.QApplication.translate("wg_Export", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("wg_Export", "Framerange:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rangeEnd.setText(QtGui.QApplication.translate("wg_Export", "1100", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rangeStart.setText(QtGui.QApplication.translate("wg_Export", "1001", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rangeStartInfo.setText(QtGui.QApplication.translate("wg_Export", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rangeEndInfo.setText(QtGui.QApplication.translate("wg_Export", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_outPath.setText(QtGui.QApplication.translate("wg_Export", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_outType.setText(QtGui.QApplication.translate("wg_Export", "Outputtype:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cam.setText(QtGui.QApplication.translate("wg_Export", "Camera:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_sCamShot.setText(QtGui.QApplication.translate("wg_Export", "Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_selectCam.setText(QtGui.QApplication.translate("wg_Export", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.l_convertExport.setText(QtGui.QApplication.translate("wg_Export", "Additional export in meters:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_additionalOptions.setText(QtGui.QApplication.translate("wg_Export", "Show additional options on publish:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_wholeScene.setText(QtGui.QApplication.translate("wg_Export", "Export whole Scene:", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_objects.setTitle(QtGui.QApplication.translate("wg_Export", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add.setText(QtGui.QApplication.translate("wg_Export", "Add selected", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("wg_Export", "Last export", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pathLast.setText(QtGui.QApplication.translate("wg_Export", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.b_openLast.setText(QtGui.QApplication.translate("wg_Export", "Open in explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.b_copyLast.setText(QtGui.QApplication.translate("wg_Export", "Copy path to clipboard", None, QtGui.QApplication.UnicodeUTF8))

