# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditShot.ui'
#
# Created: Wed Sep 26 13:06:40 2018
#      by: pyside2-uic @pyside_tools_VERSION@ running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dlg_EditShot(object):
    def setupUi(self, dlg_EditShot):
        dlg_EditShot.setObjectName("dlg_EditShot")
        dlg_EditShot.resize(436, 401)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_EditShot)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_shotName = QtWidgets.QWidget(dlg_EditShot)
        self.w_shotName.setObjectName("w_shotName")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.w_shotName)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.w_shotName)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.e_sequence = QtWidgets.QLineEdit(self.w_shotName)
        self.e_sequence.setObjectName("e_sequence")
        self.horizontalLayout_3.addWidget(self.e_sequence)
        self.b_showSeq = QtWidgets.QPushButton(self.w_shotName)
        self.b_showSeq.setMaximumSize(QtCore.QSize(25, 16777215))
        self.b_showSeq.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_showSeq.setObjectName("b_showSeq")
        self.horizontalLayout_3.addWidget(self.b_showSeq)
        self.l_item = QtWidgets.QLabel(self.w_shotName)
        self.l_item.setObjectName("l_item")
        self.horizontalLayout_3.addWidget(self.l_item)
        self.e_shotName = QtWidgets.QLineEdit(self.w_shotName)
        self.e_shotName.setObjectName("e_shotName")
        self.horizontalLayout_3.addWidget(self.e_shotName)
        self.verticalLayout.addWidget(self.w_shotName)
        self.w_range = QtWidgets.QWidget(dlg_EditShot)
        self.w_range.setObjectName("w_range")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.w_range)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.w_range)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.w_range)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sp_startFrame = QtWidgets.QSpinBox(self.w_range)
        self.sp_startFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_startFrame.setMaximum(99999)
        self.sp_startFrame.setProperty("value", 1001)
        self.sp_startFrame.setObjectName("sp_startFrame")
        self.horizontalLayout.addWidget(self.sp_startFrame)
        self.label_3 = QtWidgets.QLabel(self.w_range)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sp_endFrame = QtWidgets.QSpinBox(self.w_range)
        self.sp_endFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_endFrame.setMaximum(99999)
        self.sp_endFrame.setProperty("value", 1100)
        self.sp_endFrame.setObjectName("sp_endFrame")
        self.horizontalLayout.addWidget(self.sp_endFrame)
        self.verticalLayout.addWidget(self.w_range)
        self.b_changePreview = QtWidgets.QPushButton(dlg_EditShot)
        self.b_changePreview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_changePreview.setObjectName("b_changePreview")
        self.verticalLayout.addWidget(self.b_changePreview)
        self.w_preview = QtWidgets.QWidget(dlg_EditShot)
        self.w_preview.setObjectName("w_preview")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.w_preview)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.l_shotPreview = QtWidgets.QLabel(self.w_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_shotPreview.sizePolicy().hasHeightForWidth())
        self.l_shotPreview.setSizePolicy(sizePolicy)
        self.l_shotPreview.setMinimumSize(QtCore.QSize(300, 169))
        self.l_shotPreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_shotPreview.setObjectName("l_shotPreview")
        self.horizontalLayout_2.addWidget(self.l_shotPreview)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.w_preview)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.widget = QtWidgets.QWidget(dlg_EditShot)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_deleteShot = QtWidgets.QPushButton(self.widget)
        self.b_deleteShot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteShot.setObjectName("b_deleteShot")
        self.horizontalLayout_4.addWidget(self.b_deleteShot)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(dlg_EditShot)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlg_EditShot.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlg_EditShot.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_EditShot)
        dlg_EditShot.setTabOrder(self.e_sequence, self.b_showSeq)
        dlg_EditShot.setTabOrder(self.b_showSeq, self.e_shotName)
        dlg_EditShot.setTabOrder(self.e_shotName, self.sp_startFrame)
        dlg_EditShot.setTabOrder(self.sp_startFrame, self.sp_endFrame)
        dlg_EditShot.setTabOrder(self.sp_endFrame, self.b_changePreview)

    def retranslateUi(self, dlg_EditShot):
        dlg_EditShot.setWindowTitle(QtWidgets.QApplication.translate("dlg_EditShot", "Edit shot", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("dlg_EditShot", "Sequence:", None, -1))
        self.b_showSeq.setToolTip(QtWidgets.QApplication.translate("dlg_EditShot", "existing sequences", None, -1))
        self.b_showSeq.setText(QtWidgets.QApplication.translate("dlg_EditShot", "▼", None, -1))
        self.l_item.setText(QtWidgets.QApplication.translate("dlg_EditShot", "Shotname:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dlg_EditShot", "Framerange:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dlg_EditShot", "start:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("dlg_EditShot", "end:", None, -1))
        self.b_changePreview.setText(QtWidgets.QApplication.translate("dlg_EditShot", "Change preview image", None, -1))
        self.l_shotPreview.setText(QtWidgets.QApplication.translate("dlg_EditShot", "Preview image", None, -1))
        self.b_deleteShot.setText(QtWidgets.QApplication.translate("dlg_EditShot", "Delete shot", None, -1))

