# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditShot.ui'
#
# Created: Wed Sep 26 13:06:40 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlg_EditShot(object):
    def setupUi(self, dlg_EditShot):
        dlg_EditShot.setObjectName("dlg_EditShot")
        dlg_EditShot.resize(436, 401)
        self.verticalLayout = QtGui.QVBoxLayout(dlg_EditShot)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_shotName = QtGui.QWidget(dlg_EditShot)
        self.w_shotName.setObjectName("w_shotName")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.w_shotName)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.w_shotName)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.e_sequence = QtGui.QLineEdit(self.w_shotName)
        self.e_sequence.setObjectName("e_sequence")
        self.horizontalLayout_3.addWidget(self.e_sequence)
        self.b_showSeq = QtGui.QPushButton(self.w_shotName)
        self.b_showSeq.setMaximumSize(QtCore.QSize(25, 16777215))
        self.b_showSeq.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_showSeq.setObjectName("b_showSeq")
        self.horizontalLayout_3.addWidget(self.b_showSeq)
        self.l_item = QtGui.QLabel(self.w_shotName)
        self.l_item.setObjectName("l_item")
        self.horizontalLayout_3.addWidget(self.l_item)
        self.e_shotName = QtGui.QLineEdit(self.w_shotName)
        self.e_shotName.setObjectName("e_shotName")
        self.horizontalLayout_3.addWidget(self.e_shotName)
        self.verticalLayout.addWidget(self.w_shotName)
        self.w_range = QtGui.QWidget(dlg_EditShot)
        self.w_range.setObjectName("w_range")
        self.horizontalLayout = QtGui.QHBoxLayout(self.w_range)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.w_range)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.w_range)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sp_startFrame = QtGui.QSpinBox(self.w_range)
        self.sp_startFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_startFrame.setMaximum(99999)
        self.sp_startFrame.setProperty("value", 1001)
        self.sp_startFrame.setObjectName("sp_startFrame")
        self.horizontalLayout.addWidget(self.sp_startFrame)
        self.label_3 = QtGui.QLabel(self.w_range)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sp_endFrame = QtGui.QSpinBox(self.w_range)
        self.sp_endFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_endFrame.setMaximum(99999)
        self.sp_endFrame.setProperty("value", 1100)
        self.sp_endFrame.setObjectName("sp_endFrame")
        self.horizontalLayout.addWidget(self.sp_endFrame)
        self.verticalLayout.addWidget(self.w_range)
        self.b_changePreview = QtGui.QPushButton(dlg_EditShot)
        self.b_changePreview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_changePreview.setObjectName("b_changePreview")
        self.verticalLayout.addWidget(self.b_changePreview)
        self.w_preview = QtGui.QWidget(dlg_EditShot)
        self.w_preview.setObjectName("w_preview")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.w_preview)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.l_shotPreview = QtGui.QLabel(self.w_preview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_shotPreview.sizePolicy().hasHeightForWidth())
        self.l_shotPreview.setSizePolicy(sizePolicy)
        self.l_shotPreview.setMinimumSize(QtCore.QSize(300, 169))
        self.l_shotPreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.l_shotPreview.setObjectName("l_shotPreview")
        self.horizontalLayout_2.addWidget(self.l_shotPreview)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.w_preview)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.widget = QtGui.QWidget(dlg_EditShot)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_deleteShot = QtGui.QPushButton(self.widget)
        self.b_deleteShot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteShot.setObjectName("b_deleteShot")
        self.horizontalLayout_4.addWidget(self.b_deleteShot)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(dlg_EditShot)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlg_EditShot.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlg_EditShot.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_EditShot)
        dlg_EditShot.setTabOrder(self.e_sequence, self.b_showSeq)
        dlg_EditShot.setTabOrder(self.b_showSeq, self.e_shotName)
        dlg_EditShot.setTabOrder(self.e_shotName, self.sp_startFrame)
        dlg_EditShot.setTabOrder(self.sp_startFrame, self.sp_endFrame)
        dlg_EditShot.setTabOrder(self.sp_endFrame, self.b_changePreview)

    def retranslateUi(self, dlg_EditShot):
        dlg_EditShot.setWindowTitle(QtGui.QApplication.translate("dlg_EditShot", "Edit shot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlg_EditShot", "Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_showSeq.setToolTip(QtGui.QApplication.translate("dlg_EditShot", "existing sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.b_showSeq.setText(QtGui.QApplication.translate("dlg_EditShot", "▼", None, QtGui.QApplication.UnicodeUTF8))
        self.l_item.setText(QtGui.QApplication.translate("dlg_EditShot", "Shotname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlg_EditShot", "Framerange:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlg_EditShot", "start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlg_EditShot", "end:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_changePreview.setText(QtGui.QApplication.translate("dlg_EditShot", "Change preview image", None, QtGui.QApplication.UnicodeUTF8))
        self.l_shotPreview.setText(QtGui.QApplication.translate("dlg_EditShot", "Preview image", None, QtGui.QApplication.UnicodeUTF8))
        self.b_deleteShot.setText(QtGui.QApplication.translate("dlg_EditShot", "Delete shot", None, QtGui.QApplication.UnicodeUTF8))

