# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShotgunPublish.ui'
#
# Created: Sun Jan 07 20:22:31 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlg_sgPublish(object):
    def setupUi(self, dlg_sgPublish):
        dlg_sgPublish.setObjectName("dlg_sgPublish")
        dlg_sgPublish.resize(292, 450)
        self.verticalLayout = QtGui.QVBoxLayout(dlg_sgPublish)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(dlg_sgPublish)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_asset = QtGui.QRadioButton(self.widget)
        self.rb_asset.setObjectName("rb_asset")
        self.horizontalLayout.addWidget(self.rb_asset)
        self.rb_shot = QtGui.QRadioButton(self.widget)
        self.rb_shot.setObjectName("rb_shot")
        self.horizontalLayout.addWidget(self.rb_shot)
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(dlg_sgPublish)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_shot = QtGui.QComboBox(self.widget_2)
        self.cb_shot.setObjectName("cb_shot")
        self.horizontalLayout_3.addWidget(self.cb_shot)
        self.verticalLayout.addWidget(self.widget_2)
        self.l_task = QtGui.QLabel(dlg_sgPublish)
        self.l_task.setObjectName("l_task")
        self.verticalLayout.addWidget(self.l_task)
        self.widget_3 = QtGui.QWidget(dlg_sgPublish)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_task = QtGui.QComboBox(self.widget_3)
        self.cb_task.setObjectName("cb_task")
        self.horizontalLayout_2.addWidget(self.cb_task)
        self.b_addTask = QtGui.QPushButton(self.widget_3)
        self.b_addTask.setMaximumSize(QtCore.QSize(23, 16777215))
        self.b_addTask.setObjectName("b_addTask")
        self.horizontalLayout_2.addWidget(self.b_addTask)
        self.verticalLayout.addWidget(self.widget_3)
        self.l_description = QtGui.QLabel(dlg_sgPublish)
        self.l_description.setObjectName("l_description")
        self.verticalLayout.addWidget(self.l_description)
        self.te_description = QtGui.QPlainTextEdit(dlg_sgPublish)
        self.te_description.setObjectName("te_description")
        self.verticalLayout.addWidget(self.te_description)
        self.chb_proxyVid = QtGui.QCheckBox(dlg_sgPublish)
        self.chb_proxyVid.setChecked(True)
        self.chb_proxyVid.setObjectName("chb_proxyVid")
        self.verticalLayout.addWidget(self.chb_proxyVid)
        self.gb_playlist = QtGui.QGroupBox(dlg_sgPublish)
        self.gb_playlist.setCheckable(True)
        self.gb_playlist.setChecked(False)
        self.gb_playlist.setObjectName("gb_playlist")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_playlist)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_playlist = QtGui.QComboBox(self.gb_playlist)
        self.cb_playlist.setObjectName("cb_playlist")
        self.verticalLayout_2.addWidget(self.cb_playlist)
        self.verticalLayout.addWidget(self.gb_playlist)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.b_sgPublish = QtGui.QPushButton(dlg_sgPublish)
        self.b_sgPublish.setMinimumSize(QtCore.QSize(0, 35))
        self.b_sgPublish.setObjectName("b_sgPublish")
        self.verticalLayout.addWidget(self.b_sgPublish)

        self.retranslateUi(dlg_sgPublish)
        QtCore.QMetaObject.connectSlotsByName(dlg_sgPublish)

    def retranslateUi(self, dlg_sgPublish):
        dlg_sgPublish.setWindowTitle(QtGui.QApplication.translate("dlg_sgPublish", "Shotgun Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_asset.setText(QtGui.QApplication.translate("dlg_sgPublish", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_shot.setText(QtGui.QApplication.translate("dlg_sgPublish", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.l_task.setText(QtGui.QApplication.translate("dlg_sgPublish", "Task:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addTask.setText(QtGui.QApplication.translate("dlg_sgPublish", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.l_description.setText(QtGui.QApplication.translate("dlg_sgPublish", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_proxyVid.setText(QtGui.QApplication.translate("dlg_sgPublish", "Upload proxy video", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_playlist.setTitle(QtGui.QApplication.translate("dlg_sgPublish", "Add to dailies playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.b_sgPublish.setText(QtGui.QApplication.translate("dlg_sgPublish", "Publish to Shotgun", None, QtGui.QApplication.UnicodeUTF8))

