# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hou_Dependency.ui'
#
# Created: Mon May 07 02:55:31 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_wg_Dependency(object):
    def setupUi(self, wg_Dependency):
        wg_Dependency.setObjectName("wg_Dependency")
        wg_Dependency.resize(340, 643)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wg_Dependency.sizePolicy().hasHeightForWidth())
        wg_Dependency.setSizePolicy(sizePolicy)
        wg_Dependency.setMinimumSize(QtCore.QSize(340, 0))
        wg_Dependency.setMaximumSize(QtCore.QSize(340, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(wg_Dependency)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtGui.QWidget(wg_Dependency)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 18, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_name = QtGui.QLabel(self.widget_4)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_2.addWidget(self.l_name)
        self.e_name = QtGui.QLineEdit(self.widget_4)
        self.e_name.setObjectName("e_name")
        self.horizontalLayout_2.addWidget(self.e_name)
        self.l_class = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.l_class.setFont(font)
        self.l_class.setObjectName("l_class")
        self.horizontalLayout_2.addWidget(self.l_class)
        self.verticalLayout.addWidget(self.widget_4)
        self.f_manager = QtGui.QWidget(wg_Dependency)
        self.f_manager.setObjectName("f_manager")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.f_manager)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_manager = QtGui.QLabel(self.f_manager)
        self.l_manager.setObjectName("l_manager")
        self.horizontalLayout_8.addWidget(self.l_manager)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.cb_manager = QtGui.QComboBox(self.f_manager)
        self.cb_manager.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_manager.setObjectName("cb_manager")
        self.horizontalLayout_8.addWidget(self.cb_manager)
        self.verticalLayout.addWidget(self.f_manager)
        self.gb_osDependency = QtGui.QGroupBox(wg_Dependency)
        self.gb_osDependency.setObjectName("gb_osDependency")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gb_osDependency)
        self.verticalLayout_4.setContentsMargins(-1, 18, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.gb_osDependency)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(0, 9, 0, 9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.w_status = QtGui.QWidget(self.groupBox_2)
        self.w_status.setObjectName("w_status")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.w_status)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(self.w_status)
        self.label_6.setMinimumSize(QtCore.QSize(40, 0))
        self.label_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.l_status = QtGui.QLabel(self.w_status)
        self.l_status.setAlignment(QtCore.Qt.AlignCenter)
        self.l_status.setObjectName("l_status")
        self.horizontalLayout_5.addWidget(self.l_status)
        self.b_goTo = QtGui.QPushButton(self.w_status)
        self.b_goTo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_goTo.setObjectName("b_goTo")
        self.horizontalLayout_5.addWidget(self.b_goTo)
        self.verticalLayout_5.addWidget(self.w_status)
        self.w_connect = QtGui.QWidget(self.groupBox_2)
        self.w_connect.setObjectName("w_connect")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.w_connect)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.b_connect = QtGui.QPushButton(self.w_connect)
        self.b_connect.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_connect.setObjectName("b_connect")
        self.horizontalLayout_6.addWidget(self.b_connect)
        self.verticalLayout_5.addWidget(self.w_connect)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.lw_osStates = QtGui.QListWidget(self.gb_osDependency)
        self.lw_osStates.setObjectName("lw_osStates")
        self.verticalLayout_4.addWidget(self.lw_osStates)
        self.verticalLayout.addWidget(self.gb_osDependency)
        self.gb_dlDependency = QtGui.QGroupBox(wg_Dependency)
        self.gb_dlDependency.setObjectName("gb_dlDependency")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_dlDependency)
        self.verticalLayout_2.setContentsMargins(-1, 18, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtGui.QWidget(self.gb_dlDependency)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sp_offset = QtGui.QSpinBox(self.widget_2)
        self.sp_offset.setSuffix("")
        self.sp_offset.setMinimum(-99999)
        self.sp_offset.setMaximum(99999)
        self.sp_offset.setObjectName("sp_offset")
        self.horizontalLayout.addWidget(self.sp_offset)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtGui.QWidget(self.gb_dlDependency)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tw_caches = QtGui.QTreeWidget(self.widget)
        self.tw_caches.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_caches.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tw_caches.setItemsExpandable(True)
        self.tw_caches.setExpandsOnDoubleClick(True)
        self.tw_caches.setObjectName("tw_caches")
        self.tw_caches.headerItem().setText(0, "1")
        self.tw_caches.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.tw_caches)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.gb_dlDependency)

        self.retranslateUi(wg_Dependency)
        QtCore.QMetaObject.connectSlotsByName(wg_Dependency)

    def retranslateUi(self, wg_Dependency):
        wg_Dependency.setWindowTitle(QtGui.QApplication.translate("wg_Dependency", "Dependency", None, QtGui.QApplication.UnicodeUTF8))
        self.l_name.setText(QtGui.QApplication.translate("wg_Dependency", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_class.setText(QtGui.QApplication.translate("wg_Dependency", "Dependency", None, QtGui.QApplication.UnicodeUTF8))
        self.l_manager.setText(QtGui.QApplication.translate("wg_Dependency", "Manager:", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_osDependency.setTitle(QtGui.QApplication.translate("wg_Dependency", "Dependency", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("wg_Dependency", "Dependent node", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("wg_Dependency", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_status.setText(QtGui.QApplication.translate("wg_Dependency", "Not connected", None, QtGui.QApplication.UnicodeUTF8))
        self.b_goTo.setText(QtGui.QApplication.translate("wg_Dependency", "Go to Node", None, QtGui.QApplication.UnicodeUTF8))
        self.b_connect.setText(QtGui.QApplication.translate("wg_Dependency", "Connect with selected Node", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_dlDependency.setTitle(QtGui.QApplication.translate("wg_Dependency", "Dependency", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("wg_Dependency", "Start when next n frames exist", None, QtGui.QApplication.UnicodeUTF8))

