name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_book_theme myst_parser PySide2 qtpy

      - name: Sphinx build
        env:
          PRISM_NO_LIBS: "1"
        run: |
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/core Prism/Scripts/ Prism/Scripts//UserInterfacesPrism Prism/Scripts/OSX_Post-Install* Prism/Scripts/OSX_Pre-Install*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/3dsMax Prism/Plugins/Apps/3dsMax/Scripts Prism/Plugins/Apps/3dsMax/Scripts/*_init* Prism/Plugins/Apps/3dsMax/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Blender Prism/Plugins/Apps/Blender/Scripts Prism/Plugins/Apps/Blender/Scripts/*_init* Prism/Plugins/Apps/Blender/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Houdini Prism/Plugins/Apps/Houdini/Scripts Prism/Plugins/Apps/Houdini/Scripts/*_init* Prism/Plugins/Apps/Houdini/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Maya Prism/Plugins/Apps/Maya/Scripts Prism/Plugins/Apps/Maya/Scripts/*_init* Prism/Plugins/Apps/Maya/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Nuke Prism/Plugins/Apps/Nuke/Scripts Prism/Plugins/Apps/Nuke/Scripts/*_init* Prism/Plugins/Apps/Nuke/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Photoshop Prism/Plugins/Apps/Photoshop/Scripts Prism/Plugins/Apps/Photoshop/Scripts/*_init* Prism/Plugins/Apps/Photoshop/Scripts/*_Variables* Prism/Plugins/Apps/Photoshop/Scripts/*_MenuTools*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/PureRef Prism/Plugins/Apps/PureRef/Scripts Prism/Plugins/Apps/PureRef/Scripts/*_init* Prism/Plugins/Apps/PureRef/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Deadline Prism/Plugins/Custom/Deadline/Scripts Prism/Plugins/Custom/Deadline/Scripts/*_init* Prism/Plugins/Custom/Deadline/Scripts/*_Variables*
          sphinx-apidoc --no-toc --module-first -o doc/autodoc/plugins/Standalone Prism/Plugins/Apps/Standalone/Scripts Prism/Plugins/Apps/Standalone/Scripts/*_init* Prism/Plugins/Apps/Standalone/Scripts/*_Variables*
          sphinx-build doc _build -b dirhtml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
